/* tslint:disable */
/* eslint-disable */
/**
 * Horse Reservation API
 * 마장 예약 서비스 API
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type AdminReservationPageResponse,
    AdminReservationPageResponseFromJSON,
    AdminReservationPageResponseToJSON,
} from '../models/AdminReservationPageResponse';
import {
    type AdminReservationResponse,
    AdminReservationResponseFromJSON,
    AdminReservationResponseToJSON,
} from '../models/AdminReservationResponse';

export interface GetReservationRequest {
    reservationId: number;
}

export interface GetReservationsRequest {
    status?: string;
    lessonDateFrom?: Date;
    lessonDateTo?: Date;
    classType?: string;
    keyword?: string;
    page?: number;
    size?: number;
}

/**
 *
 */
export class AdminReservationQueryControllerApi extends runtime.BaseAPI {

    /**
     * Creates request options for getReservation without sending the request
     */
    async getReservationRequestOpts(requestParameters: GetReservationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['reservationId'] == null) {
            throw new runtime.RequiredError(
                'reservationId',
                'Required parameter "reservationId" was null or undefined when calling getReservation().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/admin/reservations/{reservationId}`;
        urlPath = urlPath.replace('{reservationId}', encodeURIComponent(String(requestParameters['reservationId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async getReservationRaw(requestParameters: GetReservationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AdminReservationResponse>> {
        const requestOptions = await this.getReservationRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AdminReservationResponseFromJSON(jsonValue));
    }

    /**
     */
    async getReservation(requestParameters: GetReservationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AdminReservationResponse> {
        const response = await this.getReservationRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getReservations without sending the request
     */
    async getReservationsRequestOpts(requestParameters: GetReservationsRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['status'] != null) {
            queryParameters['status'] = requestParameters['status'];
        }

        if (requestParameters['lessonDateFrom'] != null) {
            queryParameters['lessonDateFrom'] = (requestParameters['lessonDateFrom'] as any).toISOString().substring(0,10);
        }

        if (requestParameters['lessonDateTo'] != null) {
            queryParameters['lessonDateTo'] = (requestParameters['lessonDateTo'] as any).toISOString().substring(0,10);
        }

        if (requestParameters['classType'] != null) {
            queryParameters['classType'] = requestParameters['classType'];
        }

        if (requestParameters['keyword'] != null) {
            queryParameters['keyword'] = requestParameters['keyword'];
        }

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['size'] != null) {
            queryParameters['size'] = requestParameters['size'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/admin/reservations`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async getReservationsRaw(requestParameters: GetReservationsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AdminReservationPageResponse>> {
        const requestOptions = await this.getReservationsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AdminReservationPageResponseFromJSON(jsonValue));
    }

    /**
     */
    async getReservations(requestParameters: GetReservationsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AdminReservationPageResponse> {
        const response = await this.getReservationsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
