/* tslint:disable */
/* eslint-disable */
/**
 * Horse Reservation API
 * 마장 예약 서비스 API
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type ApprovalExpiryResponse,
    ApprovalExpiryResponseFromJSON,
    ApprovalExpiryResponseToJSON,
} from '../models/ApprovalExpiryResponse';

/**
 *
 */
export class AdminApprovalExpiryJobControllerApi extends runtime.BaseAPI {

    /**
     * Creates request options for expirePendingApprovals without sending the request
     */
    async expirePendingApprovalsRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/admin/jobs/expire-pending-approvals`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async expirePendingApprovalsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApprovalExpiryResponse>> {
        const requestOptions = await this.expirePendingApprovalsRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApprovalExpiryResponseFromJSON(jsonValue));
    }

    /**
     */
    async expirePendingApprovals(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApprovalExpiryResponse> {
        const response = await this.expirePendingApprovalsRaw(initOverrides);
        return await response.value();
    }

}
