/* tslint:disable */
/* eslint-disable */
/**
 * Horse Reservation API
 * 마장 예약 서비스 API
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type FamilyGroupAuditPageResponse,
    FamilyGroupAuditPageResponseFromJSON,
    FamilyGroupAuditPageResponseToJSON,
} from '../models/FamilyGroupAuditPageResponse';
import {
    type FamilyGroupMemberPageResponse,
    FamilyGroupMemberPageResponseFromJSON,
    FamilyGroupMemberPageResponseToJSON,
} from '../models/FamilyGroupMemberPageResponse';
import {
    type FamilyGroupPageResponse,
    FamilyGroupPageResponseFromJSON,
    FamilyGroupPageResponseToJSON,
} from '../models/FamilyGroupPageResponse';
import {
    type FamilyMemberCandidatePageResponse,
    FamilyMemberCandidatePageResponseFromJSON,
    FamilyMemberCandidatePageResponseToJSON,
} from '../models/FamilyMemberCandidatePageResponse';

export interface GetFamilyGroupAuditLogsRequest {
    groupId: number;
    page?: number;
    size?: number;
}

export interface GetFamilyGroupMembersRequest {
    groupId: number;
    page?: number;
    size?: number;
}

export interface GetFamilyGroupsRequest {
    query?: string;
    status?: GetFamilyGroupsStatusEnum;
    page?: number;
    size?: number;
}

export interface GetFamilyMemberCandidatesRequest {
    query?: string;
    page?: number;
    size?: number;
}

/**
 *
 */
export class AdminFamilyGroupQueryControllerApi extends runtime.BaseAPI {

    /**
     * Creates request options for getFamilyGroupAuditLogs without sending the request
     */
    async getFamilyGroupAuditLogsRequestOpts(requestParameters: GetFamilyGroupAuditLogsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['groupId'] == null) {
            throw new runtime.RequiredError(
                'groupId',
                'Required parameter "groupId" was null or undefined when calling getFamilyGroupAuditLogs().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['size'] != null) {
            queryParameters['size'] = requestParameters['size'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/admin/family-groups/{groupId}/audit-logs`;
        urlPath = urlPath.replace('{groupId}', encodeURIComponent(String(requestParameters['groupId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async getFamilyGroupAuditLogsRaw(requestParameters: GetFamilyGroupAuditLogsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<FamilyGroupAuditPageResponse>> {
        const requestOptions = await this.getFamilyGroupAuditLogsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => FamilyGroupAuditPageResponseFromJSON(jsonValue));
    }

    /**
     */
    async getFamilyGroupAuditLogs(requestParameters: GetFamilyGroupAuditLogsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<FamilyGroupAuditPageResponse> {
        const response = await this.getFamilyGroupAuditLogsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getFamilyGroupMembers without sending the request
     */
    async getFamilyGroupMembersRequestOpts(requestParameters: GetFamilyGroupMembersRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['groupId'] == null) {
            throw new runtime.RequiredError(
                'groupId',
                'Required parameter "groupId" was null or undefined when calling getFamilyGroupMembers().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['size'] != null) {
            queryParameters['size'] = requestParameters['size'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/admin/family-groups/{groupId}/members`;
        urlPath = urlPath.replace('{groupId}', encodeURIComponent(String(requestParameters['groupId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async getFamilyGroupMembersRaw(requestParameters: GetFamilyGroupMembersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<FamilyGroupMemberPageResponse>> {
        const requestOptions = await this.getFamilyGroupMembersRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => FamilyGroupMemberPageResponseFromJSON(jsonValue));
    }

    /**
     */
    async getFamilyGroupMembers(requestParameters: GetFamilyGroupMembersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<FamilyGroupMemberPageResponse> {
        const response = await this.getFamilyGroupMembersRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getFamilyGroups without sending the request
     */
    async getFamilyGroupsRequestOpts(requestParameters: GetFamilyGroupsRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['query'] != null) {
            queryParameters['query'] = requestParameters['query'];
        }

        if (requestParameters['status'] != null) {
            queryParameters['status'] = requestParameters['status'];
        }

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['size'] != null) {
            queryParameters['size'] = requestParameters['size'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/admin/family-groups`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async getFamilyGroupsRaw(requestParameters: GetFamilyGroupsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<FamilyGroupPageResponse>> {
        const requestOptions = await this.getFamilyGroupsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => FamilyGroupPageResponseFromJSON(jsonValue));
    }

    /**
     */
    async getFamilyGroups(requestParameters: GetFamilyGroupsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<FamilyGroupPageResponse> {
        const response = await this.getFamilyGroupsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getFamilyMemberCandidates without sending the request
     */
    async getFamilyMemberCandidatesRequestOpts(requestParameters: GetFamilyMemberCandidatesRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['query'] != null) {
            queryParameters['query'] = requestParameters['query'];
        }

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['size'] != null) {
            queryParameters['size'] = requestParameters['size'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/admin/family-groups/member-candidates`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async getFamilyMemberCandidatesRaw(requestParameters: GetFamilyMemberCandidatesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<FamilyMemberCandidatePageResponse>> {
        const requestOptions = await this.getFamilyMemberCandidatesRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => FamilyMemberCandidatePageResponseFromJSON(jsonValue));
    }

    /**
     */
    async getFamilyMemberCandidates(requestParameters: GetFamilyMemberCandidatesRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<FamilyMemberCandidatePageResponse> {
        const response = await this.getFamilyMemberCandidatesRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const GetFamilyGroupsStatusEnum = {
    Active: 'ACTIVE',
    Dissolved: 'DISSOLVED'
} as const;
export type GetFamilyGroupsStatusEnum = typeof GetFamilyGroupsStatusEnum[keyof typeof GetFamilyGroupsStatusEnum];
