/* tslint:disable */
/* eslint-disable */
/**
 * Horse Reservation API
 * 마장 예약 서비스 API
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type ErrorResponse,
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
} from '../models/ErrorResponse';
import {
    type ReservationCancelResponse,
    ReservationCancelResponseFromJSON,
    ReservationCancelResponseToJSON,
} from '../models/ReservationCancelResponse';
import {
    type ScheduleClosureCancelRequest,
    ScheduleClosureCancelRequestFromJSON,
    ScheduleClosureCancelRequestToJSON,
} from '../models/ScheduleClosureCancelRequest';
import {
    type TimeSlotClosureActionRequest,
    TimeSlotClosureActionRequestFromJSON,
    TimeSlotClosureActionRequestToJSON,
} from '../models/TimeSlotClosureActionRequest';
import {
    type TimeSlotClosureResponse,
    TimeSlotClosureResponseFromJSON,
    TimeSlotClosureResponseToJSON,
} from '../models/TimeSlotClosureResponse';
import {
    type TimeSlotClosureStartRequest,
    TimeSlotClosureStartRequestFromJSON,
    TimeSlotClosureStartRequestToJSON,
} from '../models/TimeSlotClosureStartRequest';

export interface CancelReservationRequest {
    timeSlotId: number;
    reservationId: number;
    scheduleClosureCancelRequest: ScheduleClosureCancelRequest;
}

export interface CompleteRequest {
    timeSlotId: number;
    timeSlotClosureActionRequest: TimeSlotClosureActionRequest;
}

export interface GetClosureRequest {
    timeSlotId: number;
}

export interface ReopenRequest {
    timeSlotId: number;
    timeSlotClosureActionRequest: TimeSlotClosureActionRequest;
}

export interface StartRequest {
    timeSlotId: number;
    timeSlotClosureStartRequest: TimeSlotClosureStartRequest;
}

export interface WithdrawRequest {
    timeSlotId: number;
    timeSlotClosureActionRequest: TimeSlotClosureActionRequest;
}

/**
 *
 */
export class AdminTimeSlotClosureControllerApi extends runtime.BaseAPI {

    /**
     * Creates request options for cancelReservation without sending the request
     */
    async cancelReservationRequestOpts(requestParameters: CancelReservationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['timeSlotId'] == null) {
            throw new runtime.RequiredError(
                'timeSlotId',
                'Required parameter "timeSlotId" was null or undefined when calling cancelReservation().'
            );
        }

        if (requestParameters['reservationId'] == null) {
            throw new runtime.RequiredError(
                'reservationId',
                'Required parameter "reservationId" was null or undefined when calling cancelReservation().'
            );
        }

        if (requestParameters['scheduleClosureCancelRequest'] == null) {
            throw new runtime.RequiredError(
                'scheduleClosureCancelRequest',
                'Required parameter "scheduleClosureCancelRequest" was null or undefined when calling cancelReservation().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/admin/timeslots/{timeSlotId}/reservations/{reservationId}/cancel-for-closure`;
        urlPath = urlPath.replace('{timeSlotId}', encodeURIComponent(String(requestParameters['timeSlotId'])));
        urlPath = urlPath.replace('{reservationId}', encodeURIComponent(String(requestParameters['reservationId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ScheduleClosureCancelRequestToJSON(requestParameters['scheduleClosureCancelRequest']),
        };
    }

    /**
     */
    async cancelReservationRaw(requestParameters: CancelReservationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ReservationCancelResponse>> {
        const requestOptions = await this.cancelReservationRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ReservationCancelResponseFromJSON(jsonValue));
    }

    /**
     */
    async cancelReservation(requestParameters: CancelReservationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ReservationCancelResponse> {
        const response = await this.cancelReservationRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for complete without sending the request
     */
    async completeRequestOpts(requestParameters: CompleteRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['timeSlotId'] == null) {
            throw new runtime.RequiredError(
                'timeSlotId',
                'Required parameter "timeSlotId" was null or undefined when calling complete().'
            );
        }

        if (requestParameters['timeSlotClosureActionRequest'] == null) {
            throw new runtime.RequiredError(
                'timeSlotClosureActionRequest',
                'Required parameter "timeSlotClosureActionRequest" was null or undefined when calling complete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/admin/timeslots/{timeSlotId}/closure/complete`;
        urlPath = urlPath.replace('{timeSlotId}', encodeURIComponent(String(requestParameters['timeSlotId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: TimeSlotClosureActionRequestToJSON(requestParameters['timeSlotClosureActionRequest']),
        };
    }

    /**
     */
    async completeRaw(requestParameters: CompleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TimeSlotClosureResponse>> {
        const requestOptions = await this.completeRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TimeSlotClosureResponseFromJSON(jsonValue));
    }

    /**
     */
    async complete(requestParameters: CompleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TimeSlotClosureResponse> {
        const response = await this.completeRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getClosure without sending the request
     */
    async getClosureRequestOpts(requestParameters: GetClosureRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['timeSlotId'] == null) {
            throw new runtime.RequiredError(
                'timeSlotId',
                'Required parameter "timeSlotId" was null or undefined when calling getClosure().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/admin/timeslots/{timeSlotId}/closure-impact`;
        urlPath = urlPath.replace('{timeSlotId}', encodeURIComponent(String(requestParameters['timeSlotId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async getClosureRaw(requestParameters: GetClosureRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TimeSlotClosureResponse>> {
        const requestOptions = await this.getClosureRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TimeSlotClosureResponseFromJSON(jsonValue));
    }

    /**
     */
    async getClosure(requestParameters: GetClosureRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TimeSlotClosureResponse> {
        const response = await this.getClosureRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for reopen without sending the request
     */
    async reopenRequestOpts(requestParameters: ReopenRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['timeSlotId'] == null) {
            throw new runtime.RequiredError(
                'timeSlotId',
                'Required parameter "timeSlotId" was null or undefined when calling reopen().'
            );
        }

        if (requestParameters['timeSlotClosureActionRequest'] == null) {
            throw new runtime.RequiredError(
                'timeSlotClosureActionRequest',
                'Required parameter "timeSlotClosureActionRequest" was null or undefined when calling reopen().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/admin/timeslots/{timeSlotId}/closure/reopen`;
        urlPath = urlPath.replace('{timeSlotId}', encodeURIComponent(String(requestParameters['timeSlotId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: TimeSlotClosureActionRequestToJSON(requestParameters['timeSlotClosureActionRequest']),
        };
    }

    /**
     */
    async reopenRaw(requestParameters: ReopenRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TimeSlotClosureResponse>> {
        const requestOptions = await this.reopenRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TimeSlotClosureResponseFromJSON(jsonValue));
    }

    /**
     */
    async reopen(requestParameters: ReopenRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TimeSlotClosureResponse> {
        const response = await this.reopenRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for start without sending the request
     */
    async startRequestOpts(requestParameters: StartRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['timeSlotId'] == null) {
            throw new runtime.RequiredError(
                'timeSlotId',
                'Required parameter "timeSlotId" was null or undefined when calling start().'
            );
        }

        if (requestParameters['timeSlotClosureStartRequest'] == null) {
            throw new runtime.RequiredError(
                'timeSlotClosureStartRequest',
                'Required parameter "timeSlotClosureStartRequest" was null or undefined when calling start().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/admin/timeslots/{timeSlotId}/closure`;
        urlPath = urlPath.replace('{timeSlotId}', encodeURIComponent(String(requestParameters['timeSlotId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: TimeSlotClosureStartRequestToJSON(requestParameters['timeSlotClosureStartRequest']),
        };
    }

    /**
     */
    async startRaw(requestParameters: StartRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TimeSlotClosureResponse>> {
        const requestOptions = await this.startRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TimeSlotClosureResponseFromJSON(jsonValue));
    }

    /**
     */
    async start(requestParameters: StartRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TimeSlotClosureResponse> {
        const response = await this.startRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for withdraw without sending the request
     */
    async withdrawRequestOpts(requestParameters: WithdrawRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['timeSlotId'] == null) {
            throw new runtime.RequiredError(
                'timeSlotId',
                'Required parameter "timeSlotId" was null or undefined when calling withdraw().'
            );
        }

        if (requestParameters['timeSlotClosureActionRequest'] == null) {
            throw new runtime.RequiredError(
                'timeSlotClosureActionRequest',
                'Required parameter "timeSlotClosureActionRequest" was null or undefined when calling withdraw().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/admin/timeslots/{timeSlotId}/closure/withdraw`;
        urlPath = urlPath.replace('{timeSlotId}', encodeURIComponent(String(requestParameters['timeSlotId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: TimeSlotClosureActionRequestToJSON(requestParameters['timeSlotClosureActionRequest']),
        };
    }

    /**
     */
    async withdrawRaw(requestParameters: WithdrawRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TimeSlotClosureResponse>> {
        const requestOptions = await this.withdrawRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TimeSlotClosureResponseFromJSON(jsonValue));
    }

    /**
     */
    async withdraw(requestParameters: WithdrawRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TimeSlotClosureResponse> {
        const response = await this.withdrawRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
