/* tslint:disable */
/* eslint-disable */
/**
 * Horse Reservation API
 * 마장 예약 서비스 API
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type ErrorResponse,
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
} from '../models/ErrorResponse';
import {
    type RecurringHolidayImpactResponse,
    RecurringHolidayImpactResponseFromJSON,
    RecurringHolidayImpactResponseToJSON,
} from '../models/RecurringHolidayImpactResponse';
import {
    type RecurringHolidayMutationResponse,
    RecurringHolidayMutationResponseFromJSON,
    RecurringHolidayMutationResponseToJSON,
} from '../models/RecurringHolidayMutationResponse';
import {
    type RecurringHolidayPreviewRequest,
    RecurringHolidayPreviewRequestFromJSON,
    RecurringHolidayPreviewRequestToJSON,
} from '../models/RecurringHolidayPreviewRequest';
import {
    type RecurringHolidayRequest,
    RecurringHolidayRequestFromJSON,
    RecurringHolidayRequestToJSON,
} from '../models/RecurringHolidayRequest';
import {
    type RecurringHolidayResponse,
    RecurringHolidayResponseFromJSON,
    RecurringHolidayResponseToJSON,
} from '../models/RecurringHolidayResponse';
import {
    type ScheduleActivationRequest,
    ScheduleActivationRequestFromJSON,
    ScheduleActivationRequestToJSON,
} from '../models/ScheduleActivationRequest';

export interface ChangeActivation1Request {
    holidayId: number;
    scheduleActivationRequest: ScheduleActivationRequest;
}

export interface Create1Request {
    recurringHolidayRequest: RecurringHolidayRequest;
}

export interface Preview1Request {
    recurringHolidayPreviewRequest: RecurringHolidayPreviewRequest;
}

export interface Update1Request {
    holidayId: number;
    recurringHolidayRequest: RecurringHolidayRequest;
}

/**
 *
 */
export class AdminRecurringHolidayControllerApi extends runtime.BaseAPI {

    /**
     * Creates request options for changeActivation1 without sending the request
     */
    async changeActivation1RequestOpts(requestParameters: ChangeActivation1Request): Promise<runtime.RequestOpts> {
        if (requestParameters['holidayId'] == null) {
            throw new runtime.RequiredError(
                'holidayId',
                'Required parameter "holidayId" was null or undefined when calling changeActivation1().'
            );
        }

        if (requestParameters['scheduleActivationRequest'] == null) {
            throw new runtime.RequiredError(
                'scheduleActivationRequest',
                'Required parameter "scheduleActivationRequest" was null or undefined when calling changeActivation1().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/admin/recurring-holidays/{holidayId}/activation`;
        urlPath = urlPath.replace('{holidayId}', encodeURIComponent(String(requestParameters['holidayId'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: ScheduleActivationRequestToJSON(requestParameters['scheduleActivationRequest']),
        };
    }

    /**
     */
    async changeActivation1Raw(requestParameters: ChangeActivation1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RecurringHolidayMutationResponse>> {
        const requestOptions = await this.changeActivation1RequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RecurringHolidayMutationResponseFromJSON(jsonValue));
    }

    /**
     */
    async changeActivation1(requestParameters: ChangeActivation1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RecurringHolidayMutationResponse> {
        const response = await this.changeActivation1Raw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for create1 without sending the request
     */
    async create1RequestOpts(requestParameters: Create1Request): Promise<runtime.RequestOpts> {
        if (requestParameters['recurringHolidayRequest'] == null) {
            throw new runtime.RequiredError(
                'recurringHolidayRequest',
                'Required parameter "recurringHolidayRequest" was null or undefined when calling create1().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/admin/recurring-holidays`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: RecurringHolidayRequestToJSON(requestParameters['recurringHolidayRequest']),
        };
    }

    /**
     */
    async create1Raw(requestParameters: Create1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RecurringHolidayMutationResponse>> {
        const requestOptions = await this.create1RequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RecurringHolidayMutationResponseFromJSON(jsonValue));
    }

    /**
     */
    async create1(requestParameters: Create1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RecurringHolidayMutationResponse> {
        const response = await this.create1Raw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getHolidays without sending the request
     */
    async getHolidaysRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/admin/recurring-holidays`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async getHolidaysRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<RecurringHolidayResponse>>> {
        const requestOptions = await this.getHolidaysRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(RecurringHolidayResponseFromJSON));
    }

    /**
     */
    async getHolidays(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<RecurringHolidayResponse>> {
        const response = await this.getHolidaysRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for preview1 without sending the request
     */
    async preview1RequestOpts(requestParameters: Preview1Request): Promise<runtime.RequestOpts> {
        if (requestParameters['recurringHolidayPreviewRequest'] == null) {
            throw new runtime.RequiredError(
                'recurringHolidayPreviewRequest',
                'Required parameter "recurringHolidayPreviewRequest" was null or undefined when calling preview1().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/admin/recurring-holidays/preview`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: RecurringHolidayPreviewRequestToJSON(requestParameters['recurringHolidayPreviewRequest']),
        };
    }

    /**
     */
    async preview1Raw(requestParameters: Preview1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RecurringHolidayImpactResponse>> {
        const requestOptions = await this.preview1RequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RecurringHolidayImpactResponseFromJSON(jsonValue));
    }

    /**
     */
    async preview1(requestParameters: Preview1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RecurringHolidayImpactResponse> {
        const response = await this.preview1Raw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for update1 without sending the request
     */
    async update1RequestOpts(requestParameters: Update1Request): Promise<runtime.RequestOpts> {
        if (requestParameters['holidayId'] == null) {
            throw new runtime.RequiredError(
                'holidayId',
                'Required parameter "holidayId" was null or undefined when calling update1().'
            );
        }

        if (requestParameters['recurringHolidayRequest'] == null) {
            throw new runtime.RequiredError(
                'recurringHolidayRequest',
                'Required parameter "recurringHolidayRequest" was null or undefined when calling update1().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/admin/recurring-holidays/{holidayId}`;
        urlPath = urlPath.replace('{holidayId}', encodeURIComponent(String(requestParameters['holidayId'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: RecurringHolidayRequestToJSON(requestParameters['recurringHolidayRequest']),
        };
    }

    /**
     */
    async update1Raw(requestParameters: Update1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RecurringHolidayMutationResponse>> {
        const requestOptions = await this.update1RequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RecurringHolidayMutationResponseFromJSON(jsonValue));
    }

    /**
     */
    async update1(requestParameters: Update1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RecurringHolidayMutationResponse> {
        const response = await this.update1Raw(requestParameters, initOverrides);
        return await response.value();
    }

}
