/* tslint:disable */
/* eslint-disable */
/**
 * Horse Reservation API
 * 마장 예약 서비스 API
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type ErrorResponse,
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
} from '../models/ErrorResponse';
import {
    type ScheduleActivationRequest,
    ScheduleActivationRequestFromJSON,
    ScheduleActivationRequestToJSON,
} from '../models/ScheduleActivationRequest';
import {
    type ScheduleTemplateImpactResponse,
    ScheduleTemplateImpactResponseFromJSON,
    ScheduleTemplateImpactResponseToJSON,
} from '../models/ScheduleTemplateImpactResponse';
import {
    type ScheduleTemplateMutationResponse,
    ScheduleTemplateMutationResponseFromJSON,
    ScheduleTemplateMutationResponseToJSON,
} from '../models/ScheduleTemplateMutationResponse';
import {
    type ScheduleTemplatePreviewRequest,
    ScheduleTemplatePreviewRequestFromJSON,
    ScheduleTemplatePreviewRequestToJSON,
} from '../models/ScheduleTemplatePreviewRequest';
import {
    type ScheduleTemplateRequest,
    ScheduleTemplateRequestFromJSON,
    ScheduleTemplateRequestToJSON,
} from '../models/ScheduleTemplateRequest';
import {
    type ScheduleTemplateResponse,
    ScheduleTemplateResponseFromJSON,
    ScheduleTemplateResponseToJSON,
} from '../models/ScheduleTemplateResponse';

export interface ChangeActivationRequest {
    templateId: number;
    scheduleActivationRequest: ScheduleActivationRequest;
}

export interface CreateRequest {
    scheduleTemplateRequest: ScheduleTemplateRequest;
}

export interface PreviewRequest {
    scheduleTemplatePreviewRequest: ScheduleTemplatePreviewRequest;
}

export interface UpdateRequest {
    templateId: number;
    scheduleTemplateRequest: ScheduleTemplateRequest;
}

/**
 *
 */
export class AdminScheduleTemplateControllerApi extends runtime.BaseAPI {

    /**
     * Creates request options for changeActivation without sending the request
     */
    async changeActivationRequestOpts(requestParameters: ChangeActivationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['templateId'] == null) {
            throw new runtime.RequiredError(
                'templateId',
                'Required parameter "templateId" was null or undefined when calling changeActivation().'
            );
        }

        if (requestParameters['scheduleActivationRequest'] == null) {
            throw new runtime.RequiredError(
                'scheduleActivationRequest',
                'Required parameter "scheduleActivationRequest" was null or undefined when calling changeActivation().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/admin/schedule-templates/{templateId}/activation`;
        urlPath = urlPath.replace('{templateId}', encodeURIComponent(String(requestParameters['templateId'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: ScheduleActivationRequestToJSON(requestParameters['scheduleActivationRequest']),
        };
    }

    /**
     */
    async changeActivationRaw(requestParameters: ChangeActivationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ScheduleTemplateMutationResponse>> {
        const requestOptions = await this.changeActivationRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ScheduleTemplateMutationResponseFromJSON(jsonValue));
    }

    /**
     */
    async changeActivation(requestParameters: ChangeActivationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ScheduleTemplateMutationResponse> {
        const response = await this.changeActivationRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for create without sending the request
     */
    async createRequestOpts(requestParameters: CreateRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['scheduleTemplateRequest'] == null) {
            throw new runtime.RequiredError(
                'scheduleTemplateRequest',
                'Required parameter "scheduleTemplateRequest" was null or undefined when calling create().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/admin/schedule-templates`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ScheduleTemplateRequestToJSON(requestParameters['scheduleTemplateRequest']),
        };
    }

    /**
     */
    async createRaw(requestParameters: CreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ScheduleTemplateMutationResponse>> {
        const requestOptions = await this.createRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ScheduleTemplateMutationResponseFromJSON(jsonValue));
    }

    /**
     */
    async create(requestParameters: CreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ScheduleTemplateMutationResponse> {
        const response = await this.createRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getTemplates without sending the request
     */
    async getTemplatesRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/admin/schedule-templates`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async getTemplatesRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ScheduleTemplateResponse>>> {
        const requestOptions = await this.getTemplatesRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ScheduleTemplateResponseFromJSON));
    }

    /**
     */
    async getTemplates(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ScheduleTemplateResponse>> {
        const response = await this.getTemplatesRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for preview without sending the request
     */
    async previewRequestOpts(requestParameters: PreviewRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['scheduleTemplatePreviewRequest'] == null) {
            throw new runtime.RequiredError(
                'scheduleTemplatePreviewRequest',
                'Required parameter "scheduleTemplatePreviewRequest" was null or undefined when calling preview().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/admin/schedule-templates/preview`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ScheduleTemplatePreviewRequestToJSON(requestParameters['scheduleTemplatePreviewRequest']),
        };
    }

    /**
     */
    async previewRaw(requestParameters: PreviewRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ScheduleTemplateImpactResponse>> {
        const requestOptions = await this.previewRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ScheduleTemplateImpactResponseFromJSON(jsonValue));
    }

    /**
     */
    async preview(requestParameters: PreviewRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ScheduleTemplateImpactResponse> {
        const response = await this.previewRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for update without sending the request
     */
    async updateRequestOpts(requestParameters: UpdateRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['templateId'] == null) {
            throw new runtime.RequiredError(
                'templateId',
                'Required parameter "templateId" was null or undefined when calling update().'
            );
        }

        if (requestParameters['scheduleTemplateRequest'] == null) {
            throw new runtime.RequiredError(
                'scheduleTemplateRequest',
                'Required parameter "scheduleTemplateRequest" was null or undefined when calling update().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/admin/schedule-templates/{templateId}`;
        urlPath = urlPath.replace('{templateId}', encodeURIComponent(String(requestParameters['templateId'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: ScheduleTemplateRequestToJSON(requestParameters['scheduleTemplateRequest']),
        };
    }

    /**
     */
    async updateRaw(requestParameters: UpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ScheduleTemplateMutationResponse>> {
        const requestOptions = await this.updateRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ScheduleTemplateMutationResponseFromJSON(jsonValue));
    }

    /**
     */
    async update(requestParameters: UpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ScheduleTemplateMutationResponse> {
        const response = await this.updateRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
