/* tslint:disable */
/* eslint-disable */
/**
 * Horse Reservation API
 * 마장 예약 서비스 API
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type AdminPendingPaymentResponse,
    AdminPendingPaymentResponseFromJSON,
    AdminPendingPaymentResponseToJSON,
} from '../models/AdminPendingPaymentResponse';

/**
 *
 */
export class AdminPendingPaymentQueryControllerApi extends runtime.BaseAPI {

    /**
     * Creates request options for getPendingPayments without sending the request
     */
    async getPendingPaymentsRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/admin/pending-payments`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async getPendingPaymentsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<AdminPendingPaymentResponse>>> {
        const requestOptions = await this.getPendingPaymentsRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(AdminPendingPaymentResponseFromJSON));
    }

    /**
     */
    async getPendingPayments(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<AdminPendingPaymentResponse>> {
        const response = await this.getPendingPaymentsRaw(initOverrides);
        return await response.value();
    }

}
