/* tslint:disable */
/* eslint-disable */
/**
 * Horse Reservation API
 * 마장 예약 서비스 API
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type ErrorResponse,
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
} from '../models/ErrorResponse';
import {
    type TimeSlotCapacityUpdateRequest,
    TimeSlotCapacityUpdateRequestFromJSON,
    TimeSlotCapacityUpdateRequestToJSON,
} from '../models/TimeSlotCapacityUpdateRequest';
import {
    type TimeSlotCreateRequest,
    TimeSlotCreateRequestFromJSON,
    TimeSlotCreateRequestToJSON,
} from '../models/TimeSlotCreateRequest';
import {
    type TimeSlotResponse,
    TimeSlotResponseFromJSON,
    TimeSlotResponseToJSON,
} from '../models/TimeSlotResponse';
import {
    type TimeSlotStatusUpdateRequest,
    TimeSlotStatusUpdateRequestFromJSON,
    TimeSlotStatusUpdateRequestToJSON,
} from '../models/TimeSlotStatusUpdateRequest';

export interface ChangeCapacityRequest {
    timeSlotId: number;
    timeSlotCapacityUpdateRequest: TimeSlotCapacityUpdateRequest;
}

export interface ChangeClosedStatusRequest {
    timeSlotId: number;
    timeSlotStatusUpdateRequest: TimeSlotStatusUpdateRequest;
}

export interface CreateTimeSlotRequest {
    timeSlotCreateRequest: TimeSlotCreateRequest;
}

export interface DeleteTimeSlotRequest {
    timeSlotId: number;
}

/**
 *
 */
export class AdminTimeSlotControllerApi extends runtime.BaseAPI {

    /**
     * Creates request options for changeCapacity without sending the request
     */
    async changeCapacityRequestOpts(requestParameters: ChangeCapacityRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['timeSlotId'] == null) {
            throw new runtime.RequiredError(
                'timeSlotId',
                'Required parameter "timeSlotId" was null or undefined when calling changeCapacity().'
            );
        }

        if (requestParameters['timeSlotCapacityUpdateRequest'] == null) {
            throw new runtime.RequiredError(
                'timeSlotCapacityUpdateRequest',
                'Required parameter "timeSlotCapacityUpdateRequest" was null or undefined when calling changeCapacity().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/admin/timeslots/{timeSlotId}/capacity`;
        urlPath = urlPath.replace('{timeSlotId}', encodeURIComponent(String(requestParameters['timeSlotId'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: TimeSlotCapacityUpdateRequestToJSON(requestParameters['timeSlotCapacityUpdateRequest']),
        };
    }

    /**
     */
    async changeCapacityRaw(requestParameters: ChangeCapacityRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TimeSlotResponse>> {
        const requestOptions = await this.changeCapacityRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TimeSlotResponseFromJSON(jsonValue));
    }

    /**
     */
    async changeCapacity(requestParameters: ChangeCapacityRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TimeSlotResponse> {
        const response = await this.changeCapacityRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for changeClosedStatus without sending the request
     */
    async changeClosedStatusRequestOpts(requestParameters: ChangeClosedStatusRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['timeSlotId'] == null) {
            throw new runtime.RequiredError(
                'timeSlotId',
                'Required parameter "timeSlotId" was null or undefined when calling changeClosedStatus().'
            );
        }

        if (requestParameters['timeSlotStatusUpdateRequest'] == null) {
            throw new runtime.RequiredError(
                'timeSlotStatusUpdateRequest',
                'Required parameter "timeSlotStatusUpdateRequest" was null or undefined when calling changeClosedStatus().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/admin/timeslots/{timeSlotId}`;
        urlPath = urlPath.replace('{timeSlotId}', encodeURIComponent(String(requestParameters['timeSlotId'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: TimeSlotStatusUpdateRequestToJSON(requestParameters['timeSlotStatusUpdateRequest']),
        };
    }

    /**
     */
    async changeClosedStatusRaw(requestParameters: ChangeClosedStatusRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TimeSlotResponse>> {
        const requestOptions = await this.changeClosedStatusRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TimeSlotResponseFromJSON(jsonValue));
    }

    /**
     */
    async changeClosedStatus(requestParameters: ChangeClosedStatusRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TimeSlotResponse> {
        const response = await this.changeClosedStatusRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for createTimeSlot without sending the request
     */
    async createTimeSlotRequestOpts(requestParameters: CreateTimeSlotRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['timeSlotCreateRequest'] == null) {
            throw new runtime.RequiredError(
                'timeSlotCreateRequest',
                'Required parameter "timeSlotCreateRequest" was null or undefined when calling createTimeSlot().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/admin/timeslots`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: TimeSlotCreateRequestToJSON(requestParameters['timeSlotCreateRequest']),
        };
    }

    /**
     */
    async createTimeSlotRaw(requestParameters: CreateTimeSlotRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TimeSlotResponse>> {
        const requestOptions = await this.createTimeSlotRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TimeSlotResponseFromJSON(jsonValue));
    }

    /**
     */
    async createTimeSlot(requestParameters: CreateTimeSlotRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TimeSlotResponse> {
        const response = await this.createTimeSlotRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for deleteTimeSlot without sending the request
     */
    async deleteTimeSlotRequestOpts(requestParameters: DeleteTimeSlotRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['timeSlotId'] == null) {
            throw new runtime.RequiredError(
                'timeSlotId',
                'Required parameter "timeSlotId" was null or undefined when calling deleteTimeSlot().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/admin/timeslots/{timeSlotId}`;
        urlPath = urlPath.replace('{timeSlotId}', encodeURIComponent(String(requestParameters['timeSlotId'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async deleteTimeSlotRaw(requestParameters: DeleteTimeSlotRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.deleteTimeSlotRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async deleteTimeSlot(requestParameters: DeleteTimeSlotRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteTimeSlotRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for getTimeSlotHistory without sending the request
     */
    async getTimeSlotHistoryRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/admin/timeslots/history`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async getTimeSlotHistoryRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<TimeSlotResponse>>> {
        const requestOptions = await this.getTimeSlotHistoryRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(TimeSlotResponseFromJSON));
    }

    /**
     */
    async getTimeSlotHistory(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<TimeSlotResponse>> {
        const response = await this.getTimeSlotHistoryRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getTimeSlots without sending the request
     */
    async getTimeSlotsRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/admin/timeslots`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async getTimeSlotsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<TimeSlotResponse>>> {
        const requestOptions = await this.getTimeSlotsRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(TimeSlotResponseFromJSON));
    }

    /**
     */
    async getTimeSlots(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<TimeSlotResponse>> {
        const response = await this.getTimeSlotsRaw(initOverrides);
        return await response.value();
    }

}
