/* tslint:disable */
/* eslint-disable */
/**
 * Horse Reservation API
 * 마장 예약 서비스 API
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type ReservationCompletionResponse,
    ReservationCompletionResponseFromJSON,
    ReservationCompletionResponseToJSON,
} from '../models/ReservationCompletionResponse';

export interface Complete1Request {
    reservationId: number;
}

/**
 *
 */
export class AdminReservationCompletionControllerApi extends runtime.BaseAPI {

    /**
     * Creates request options for complete1 without sending the request
     */
    async complete1RequestOpts(requestParameters: Complete1Request): Promise<runtime.RequestOpts> {
        if (requestParameters['reservationId'] == null) {
            throw new runtime.RequiredError(
                'reservationId',
                'Required parameter "reservationId" was null or undefined when calling complete1().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/admin/reservations/{reservationId}/complete`;
        urlPath = urlPath.replace('{reservationId}', encodeURIComponent(String(requestParameters['reservationId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async complete1Raw(requestParameters: Complete1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ReservationCompletionResponse>> {
        const requestOptions = await this.complete1RequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ReservationCompletionResponseFromJSON(jsonValue));
    }

    /**
     */
    async complete1(requestParameters: Complete1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ReservationCompletionResponse> {
        const response = await this.complete1Raw(requestParameters, initOverrides);
        return await response.value();
    }

}
