/* tslint:disable */
/* eslint-disable */
/**
 * Horse Reservation API
 * 마장 예약 서비스 API
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type BulkReservationAttendanceRequest,
    BulkReservationAttendanceRequestFromJSON,
    BulkReservationAttendanceRequestToJSON,
} from '../models/BulkReservationAttendanceRequest';
import {
    type BulkReservationAttendanceResponse,
    BulkReservationAttendanceResponseFromJSON,
    BulkReservationAttendanceResponseToJSON,
} from '../models/BulkReservationAttendanceResponse';

export interface ProcessBulkAttendanceRequest {
    bulkReservationAttendanceRequest: BulkReservationAttendanceRequest;
}

/**
 *
 */
export class AdminBulkReservationAttendanceControllerApi extends runtime.BaseAPI {

    /**
     * Creates request options for processBulkAttendance without sending the request
     */
    async processBulkAttendanceRequestOpts(requestParameters: ProcessBulkAttendanceRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['bulkReservationAttendanceRequest'] == null) {
            throw new runtime.RequiredError(
                'bulkReservationAttendanceRequest',
                'Required parameter "bulkReservationAttendanceRequest" was null or undefined when calling processBulkAttendance().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/admin/reservations/complete-bulk`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: BulkReservationAttendanceRequestToJSON(requestParameters['bulkReservationAttendanceRequest']),
        };
    }

    /**
     */
    async processBulkAttendanceRaw(requestParameters: ProcessBulkAttendanceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BulkReservationAttendanceResponse>> {
        const requestOptions = await this.processBulkAttendanceRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BulkReservationAttendanceResponseFromJSON(jsonValue));
    }

    /**
     */
    async processBulkAttendance(requestParameters: ProcessBulkAttendanceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BulkReservationAttendanceResponse> {
        const response = await this.processBulkAttendanceRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
