/* tslint:disable */
/* eslint-disable */
/**
 * Horse Reservation API
 * 마장 예약 서비스 API
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type ErrorResponse,
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
} from '../models/ErrorResponse';
import {
    type ScheduleActivationRequest,
    ScheduleActivationRequestFromJSON,
    ScheduleActivationRequestToJSON,
} from '../models/ScheduleActivationRequest';
import {
    type ScheduleTemplateDeleteRequest,
    ScheduleTemplateDeleteRequestFromJSON,
    ScheduleTemplateDeleteRequestToJSON,
} from '../models/ScheduleTemplateDeleteRequest';
import {
    type ScheduleTemplateFutureReservationsResponse,
    ScheduleTemplateFutureReservationsResponseFromJSON,
    ScheduleTemplateFutureReservationsResponseToJSON,
} from '../models/ScheduleTemplateFutureReservationsResponse';
import {
    type ScheduleTemplateImpactResponse,
    ScheduleTemplateImpactResponseFromJSON,
    ScheduleTemplateImpactResponseToJSON,
} from '../models/ScheduleTemplateImpactResponse';
import {
    type ScheduleTemplateMutationConflictResponse,
    ScheduleTemplateMutationConflictResponseFromJSON,
    ScheduleTemplateMutationConflictResponseToJSON,
} from '../models/ScheduleTemplateMutationConflictResponse';
import {
    type ScheduleTemplateMutationResponse,
    ScheduleTemplateMutationResponseFromJSON,
    ScheduleTemplateMutationResponseToJSON,
} from '../models/ScheduleTemplateMutationResponse';
import {
    type ScheduleTemplatePreviewRequest,
    ScheduleTemplatePreviewRequestFromJSON,
    ScheduleTemplatePreviewRequestToJSON,
} from '../models/ScheduleTemplatePreviewRequest';
import {
    type ScheduleTemplateRequest,
    ScheduleTemplateRequestFromJSON,
    ScheduleTemplateRequestToJSON,
} from '../models/ScheduleTemplateRequest';
import {
    type ScheduleTemplateResponse,
    ScheduleTemplateResponseFromJSON,
    ScheduleTemplateResponseToJSON,
} from '../models/ScheduleTemplateResponse';

export interface DeleteRequest {
    templateId: number;
    scheduleTemplateDeleteRequest: ScheduleTemplateDeleteRequest;
}

export interface ChangeActivationRequest {
    templateId: number;
    scheduleActivationRequest: ScheduleActivationRequest;
}

export interface CreateRequest {
    scheduleTemplateRequest: ScheduleTemplateRequest;
}

export interface GetFutureOccupyingReservationsRequest {
    templateId: number;
}

export interface PreviewRequest {
    scheduleTemplatePreviewRequest: ScheduleTemplatePreviewRequest;
}

export interface UpdateRequest {
    templateId: number;
    scheduleTemplateRequest: ScheduleTemplateRequest;
}

/**
 *
 */
export class AdminScheduleTemplateControllerApi extends runtime.BaseAPI {

    /**
     * Creates request options for _delete without sending the request
     */
    async _deleteRequestOpts(requestParameters: DeleteRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['templateId'] == null) {
            throw new runtime.RequiredError(
                'templateId',
                'Required parameter "templateId" was null or undefined when calling _delete().'
            );
        }

        if (requestParameters['scheduleTemplateDeleteRequest'] == null) {
            throw new runtime.RequiredError(
                'scheduleTemplateDeleteRequest',
                'Required parameter "scheduleTemplateDeleteRequest" was null or undefined when calling _delete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/admin/schedule-templates/{templateId}`;
        urlPath = urlPath.replace('{templateId}', encodeURIComponent(String(requestParameters['templateId'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
            body: ScheduleTemplateDeleteRequestToJSON(requestParameters['scheduleTemplateDeleteRequest']),
        };
    }

    /**
     * 정규 시간표를 물리 삭제하지 않고 향후 운영을 종료한다.
     */
    async _deleteRaw(requestParameters: DeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ScheduleTemplateMutationResponse>> {
        const requestOptions = await this._deleteRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ScheduleTemplateMutationResponseFromJSON(jsonValue));
    }

    /**
     * 정규 시간표를 물리 삭제하지 않고 향후 운영을 종료한다.
     */
    async _delete(requestParameters: DeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ScheduleTemplateMutationResponse> {
        const response = await this._deleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for changeActivation without sending the request
     */
    async changeActivationRequestOpts(requestParameters: ChangeActivationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['templateId'] == null) {
            throw new runtime.RequiredError(
                'templateId',
                'Required parameter "templateId" was null or undefined when calling changeActivation().'
            );
        }

        if (requestParameters['scheduleActivationRequest'] == null) {
            throw new runtime.RequiredError(
                'scheduleActivationRequest',
                'Required parameter "scheduleActivationRequest" was null or undefined when calling changeActivation().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/admin/schedule-templates/{templateId}/activation`;
        urlPath = urlPath.replace('{templateId}', encodeURIComponent(String(requestParameters['templateId'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: ScheduleActivationRequestToJSON(requestParameters['scheduleActivationRequest']),
        };
    }

    /**
     */
    async changeActivationRaw(requestParameters: ChangeActivationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ScheduleTemplateMutationResponse>> {
        const requestOptions = await this.changeActivationRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ScheduleTemplateMutationResponseFromJSON(jsonValue));
    }

    /**
     */
    async changeActivation(requestParameters: ChangeActivationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ScheduleTemplateMutationResponse> {
        const response = await this.changeActivationRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for create without sending the request
     */
    async createRequestOpts(requestParameters: CreateRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['scheduleTemplateRequest'] == null) {
            throw new runtime.RequiredError(
                'scheduleTemplateRequest',
                'Required parameter "scheduleTemplateRequest" was null or undefined when calling create().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/admin/schedule-templates`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ScheduleTemplateRequestToJSON(requestParameters['scheduleTemplateRequest']),
        };
    }

    /**
     * 동일 요일과 시작 시각의 inactive Template이 있으면 해당 ID를 재사용해 운영을 재개한다. 정원 충돌 시 ErrorResponse.details는 lessonDate, startTime, totalOccupied, roundArenaOccupied, classOccupied, requestedTotalCapacity, requestedRoundArenaCapacity, requestedClassCapacities를 제공한다.
     */
    async createRaw(requestParameters: CreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ScheduleTemplateMutationResponse>> {
        const requestOptions = await this.createRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ScheduleTemplateMutationResponseFromJSON(jsonValue));
    }

    /**
     * 동일 요일과 시작 시각의 inactive Template이 있으면 해당 ID를 재사용해 운영을 재개한다. 정원 충돌 시 ErrorResponse.details는 lessonDate, startTime, totalOccupied, roundArenaOccupied, classOccupied, requestedTotalCapacity, requestedRoundArenaCapacity, requestedClassCapacities를 제공한다.
     */
    async create(requestParameters: CreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ScheduleTemplateMutationResponse> {
        const response = await this.createRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getFutureOccupyingReservations without sending the request
     */
    async getFutureOccupyingReservationsRequestOpts(requestParameters: GetFutureOccupyingReservationsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['templateId'] == null) {
            throw new runtime.RequiredError(
                'templateId',
                'Required parameter "templateId" was null or undefined when calling getFutureOccupyingReservations().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/admin/schedule-templates/{templateId}/future-occupying-reservations`;
        urlPath = urlPath.replace('{templateId}', encodeURIComponent(String(requestParameters['templateId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * 정규 시간표에 연결된 미래 점유 Reservation을 조회한다.
     */
    async getFutureOccupyingReservationsRaw(requestParameters: GetFutureOccupyingReservationsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ScheduleTemplateFutureReservationsResponse>> {
        const requestOptions = await this.getFutureOccupyingReservationsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ScheduleTemplateFutureReservationsResponseFromJSON(jsonValue));
    }

    /**
     * 정규 시간표에 연결된 미래 점유 Reservation을 조회한다.
     */
    async getFutureOccupyingReservations(requestParameters: GetFutureOccupyingReservationsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ScheduleTemplateFutureReservationsResponse> {
        const response = await this.getFutureOccupyingReservationsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getTemplates without sending the request
     */
    async getTemplatesRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/admin/schedule-templates`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async getTemplatesRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ScheduleTemplateResponse>>> {
        const requestOptions = await this.getTemplatesRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ScheduleTemplateResponseFromJSON));
    }

    /**
     */
    async getTemplates(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ScheduleTemplateResponse>> {
        const response = await this.getTemplatesRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for preview without sending the request
     */
    async previewRequestOpts(requestParameters: PreviewRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['scheduleTemplatePreviewRequest'] == null) {
            throw new runtime.RequiredError(
                'scheduleTemplatePreviewRequest',
                'Required parameter "scheduleTemplatePreviewRequest" was null or undefined when calling preview().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/admin/schedule-templates/preview`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ScheduleTemplatePreviewRequestToJSON(requestParameters['scheduleTemplatePreviewRequest']),
        };
    }

    /**
     */
    async previewRaw(requestParameters: PreviewRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ScheduleTemplateImpactResponse>> {
        const requestOptions = await this.previewRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ScheduleTemplateImpactResponseFromJSON(jsonValue));
    }

    /**
     */
    async preview(requestParameters: PreviewRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ScheduleTemplateImpactResponse> {
        const response = await this.previewRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for update without sending the request
     */
    async updateRequestOpts(requestParameters: UpdateRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['templateId'] == null) {
            throw new runtime.RequiredError(
                'templateId',
                'Required parameter "templateId" was null or undefined when calling update().'
            );
        }

        if (requestParameters['scheduleTemplateRequest'] == null) {
            throw new runtime.RequiredError(
                'scheduleTemplateRequest',
                'Required parameter "scheduleTemplateRequest" was null or undefined when calling update().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/admin/schedule-templates/{templateId}`;
        urlPath = urlPath.replace('{templateId}', encodeURIComponent(String(requestParameters['templateId'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: ScheduleTemplateRequestToJSON(requestParameters['scheduleTemplateRequest']),
        };
    }

    /**
     * 정규 시간표 설정을 변경한다. 정원 충돌 시 ErrorResponse.details는 lessonDate, startTime, totalOccupied, roundArenaOccupied, classOccupied, requestedTotalCapacity, requestedRoundArenaCapacity, requestedClassCapacities를 제공한다.
     */
    async updateRaw(requestParameters: UpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ScheduleTemplateMutationResponse>> {
        const requestOptions = await this.updateRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ScheduleTemplateMutationResponseFromJSON(jsonValue));
    }

    /**
     * 정규 시간표 설정을 변경한다. 정원 충돌 시 ErrorResponse.details는 lessonDate, startTime, totalOccupied, roundArenaOccupied, classOccupied, requestedTotalCapacity, requestedRoundArenaCapacity, requestedClassCapacities를 제공한다.
     */
    async update(requestParameters: UpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ScheduleTemplateMutationResponse> {
        const response = await this.updateRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
