/* tslint:disable */
/* eslint-disable */
/**
 * Horse Reservation API
 * 마장 예약 서비스 API
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type ErrorResponse,
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
} from '../models/ErrorResponse';
import {
    type ReservationCancelResponse,
    ReservationCancelResponseFromJSON,
    ReservationCancelResponseToJSON,
} from '../models/ReservationCancelResponse';
import {
    type ScheduleClosureCancelRequest,
    ScheduleClosureCancelRequestFromJSON,
    ScheduleClosureCancelRequestToJSON,
} from '../models/ScheduleClosureCancelRequest';
import {
    type ScheduleDateActionRequest,
    ScheduleDateActionRequestFromJSON,
    ScheduleDateActionRequestToJSON,
} from '../models/ScheduleDateActionRequest';
import {
    type ScheduleDateClosureImpactResponse,
    ScheduleDateClosureImpactResponseFromJSON,
    ScheduleDateClosureImpactResponseToJSON,
} from '../models/ScheduleDateClosureImpactResponse';
import {
    type ScheduleDateResponse,
    ScheduleDateResponseFromJSON,
    ScheduleDateResponseToJSON,
} from '../models/ScheduleDateResponse';

export interface CancelClosingRequest {
    scheduleDate: Date;
    scheduleDateActionRequest: ScheduleDateActionRequest;
}

export interface CancelReservation1Request {
    scheduleDate: Date;
    reservationId: number;
    scheduleClosureCancelRequest: ScheduleClosureCancelRequest;
}

export interface CloseRequest {
    scheduleDate: Date;
    scheduleDateActionRequest: ScheduleDateActionRequest;
}

export interface GetClosureImpactRequest {
    scheduleDate: Date;
}

export interface GetScheduleDateRequest {
    scheduleDate: Date;
}

export interface GetScheduleDatesRequest {
    dateFrom: Date;
    dateTo: Date;
}

export interface StartClosingRequest {
    scheduleDate: Date;
    scheduleDateActionRequest: ScheduleDateActionRequest;
}

/**
 *
 */
export class AdminScheduleDateControllerApi extends runtime.BaseAPI {

    /**
     * Creates request options for cancelClosing without sending the request
     */
    async cancelClosingRequestOpts(requestParameters: CancelClosingRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['scheduleDate'] == null) {
            throw new runtime.RequiredError(
                'scheduleDate',
                'Required parameter "scheduleDate" was null or undefined when calling cancelClosing().'
            );
        }

        if (requestParameters['scheduleDateActionRequest'] == null) {
            throw new runtime.RequiredError(
                'scheduleDateActionRequest',
                'Required parameter "scheduleDateActionRequest" was null or undefined when calling cancelClosing().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/admin/schedule-dates/{scheduleDate}/closing/cancel`;
        if (requestParameters['scheduleDate'] instanceof Date) {
            urlPath = urlPath.replace('{scheduleDate}', encodeURIComponent(requestParameters['scheduleDate'].toISOString().substring(0,10)));
        } else {
            urlPath = urlPath.replace('{scheduleDate}', encodeURIComponent(String(requestParameters['scheduleDate'])));
        }

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ScheduleDateActionRequestToJSON(requestParameters['scheduleDateActionRequest']),
        };
    }

    /**
     */
    async cancelClosingRaw(requestParameters: CancelClosingRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ScheduleDateClosureImpactResponse>> {
        const requestOptions = await this.cancelClosingRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ScheduleDateClosureImpactResponseFromJSON(jsonValue));
    }

    /**
     */
    async cancelClosing(requestParameters: CancelClosingRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ScheduleDateClosureImpactResponse> {
        const response = await this.cancelClosingRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for cancelReservation1 without sending the request
     */
    async cancelReservation1RequestOpts(requestParameters: CancelReservation1Request): Promise<runtime.RequestOpts> {
        if (requestParameters['scheduleDate'] == null) {
            throw new runtime.RequiredError(
                'scheduleDate',
                'Required parameter "scheduleDate" was null or undefined when calling cancelReservation1().'
            );
        }

        if (requestParameters['reservationId'] == null) {
            throw new runtime.RequiredError(
                'reservationId',
                'Required parameter "reservationId" was null or undefined when calling cancelReservation1().'
            );
        }

        if (requestParameters['scheduleClosureCancelRequest'] == null) {
            throw new runtime.RequiredError(
                'scheduleClosureCancelRequest',
                'Required parameter "scheduleClosureCancelRequest" was null or undefined when calling cancelReservation1().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/admin/schedule-dates/{scheduleDate}/reservations/{reservationId}/cancel-for-closure`;
        if (requestParameters['scheduleDate'] instanceof Date) {
            urlPath = urlPath.replace('{scheduleDate}', encodeURIComponent(requestParameters['scheduleDate'].toISOString().substring(0,10)));
        } else {
            urlPath = urlPath.replace('{scheduleDate}', encodeURIComponent(String(requestParameters['scheduleDate'])));
        }
        urlPath = urlPath.replace('{reservationId}', encodeURIComponent(String(requestParameters['reservationId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ScheduleClosureCancelRequestToJSON(requestParameters['scheduleClosureCancelRequest']),
        };
    }

    /**
     */
    async cancelReservation1Raw(requestParameters: CancelReservation1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ReservationCancelResponse>> {
        const requestOptions = await this.cancelReservation1RequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ReservationCancelResponseFromJSON(jsonValue));
    }

    /**
     */
    async cancelReservation1(requestParameters: CancelReservation1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ReservationCancelResponse> {
        const response = await this.cancelReservation1Raw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for close without sending the request
     */
    async closeRequestOpts(requestParameters: CloseRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['scheduleDate'] == null) {
            throw new runtime.RequiredError(
                'scheduleDate',
                'Required parameter "scheduleDate" was null or undefined when calling close().'
            );
        }

        if (requestParameters['scheduleDateActionRequest'] == null) {
            throw new runtime.RequiredError(
                'scheduleDateActionRequest',
                'Required parameter "scheduleDateActionRequest" was null or undefined when calling close().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/admin/schedule-dates/{scheduleDate}/close`;
        if (requestParameters['scheduleDate'] instanceof Date) {
            urlPath = urlPath.replace('{scheduleDate}', encodeURIComponent(requestParameters['scheduleDate'].toISOString().substring(0,10)));
        } else {
            urlPath = urlPath.replace('{scheduleDate}', encodeURIComponent(String(requestParameters['scheduleDate'])));
        }

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ScheduleDateActionRequestToJSON(requestParameters['scheduleDateActionRequest']),
        };
    }

    /**
     */
    async closeRaw(requestParameters: CloseRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ScheduleDateClosureImpactResponse>> {
        const requestOptions = await this.closeRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ScheduleDateClosureImpactResponseFromJSON(jsonValue));
    }

    /**
     */
    async close(requestParameters: CloseRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ScheduleDateClosureImpactResponse> {
        const response = await this.closeRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getClosureImpact without sending the request
     */
    async getClosureImpactRequestOpts(requestParameters: GetClosureImpactRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['scheduleDate'] == null) {
            throw new runtime.RequiredError(
                'scheduleDate',
                'Required parameter "scheduleDate" was null or undefined when calling getClosureImpact().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/admin/schedule-dates/{scheduleDate}/closure-impact`;
        if (requestParameters['scheduleDate'] instanceof Date) {
            urlPath = urlPath.replace('{scheduleDate}', encodeURIComponent(requestParameters['scheduleDate'].toISOString().substring(0,10)));
        } else {
            urlPath = urlPath.replace('{scheduleDate}', encodeURIComponent(String(requestParameters['scheduleDate'])));
        }

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async getClosureImpactRaw(requestParameters: GetClosureImpactRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ScheduleDateClosureImpactResponse>> {
        const requestOptions = await this.getClosureImpactRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ScheduleDateClosureImpactResponseFromJSON(jsonValue));
    }

    /**
     */
    async getClosureImpact(requestParameters: GetClosureImpactRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ScheduleDateClosureImpactResponse> {
        const response = await this.getClosureImpactRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getScheduleDate without sending the request
     */
    async getScheduleDateRequestOpts(requestParameters: GetScheduleDateRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['scheduleDate'] == null) {
            throw new runtime.RequiredError(
                'scheduleDate',
                'Required parameter "scheduleDate" was null or undefined when calling getScheduleDate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/admin/schedule-dates/{scheduleDate}`;
        if (requestParameters['scheduleDate'] instanceof Date) {
            urlPath = urlPath.replace('{scheduleDate}', encodeURIComponent(requestParameters['scheduleDate'].toISOString().substring(0,10)));
        } else {
            urlPath = urlPath.replace('{scheduleDate}', encodeURIComponent(String(requestParameters['scheduleDate'])));
        }

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async getScheduleDateRaw(requestParameters: GetScheduleDateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ScheduleDateResponse>> {
        const requestOptions = await this.getScheduleDateRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ScheduleDateResponseFromJSON(jsonValue));
    }

    /**
     */
    async getScheduleDate(requestParameters: GetScheduleDateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ScheduleDateResponse> {
        const response = await this.getScheduleDateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getScheduleDates without sending the request
     */
    async getScheduleDatesRequestOpts(requestParameters: GetScheduleDatesRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['dateFrom'] == null) {
            throw new runtime.RequiredError(
                'dateFrom',
                'Required parameter "dateFrom" was null or undefined when calling getScheduleDates().'
            );
        }

        if (requestParameters['dateTo'] == null) {
            throw new runtime.RequiredError(
                'dateTo',
                'Required parameter "dateTo" was null or undefined when calling getScheduleDates().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['dateFrom'] != null) {
            queryParameters['dateFrom'] = (requestParameters['dateFrom'] as any).toISOString().substring(0,10);
        }

        if (requestParameters['dateTo'] != null) {
            queryParameters['dateTo'] = (requestParameters['dateTo'] as any).toISOString().substring(0,10);
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/admin/schedule-dates`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async getScheduleDatesRaw(requestParameters: GetScheduleDatesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ScheduleDateResponse>>> {
        const requestOptions = await this.getScheduleDatesRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ScheduleDateResponseFromJSON));
    }

    /**
     */
    async getScheduleDates(requestParameters: GetScheduleDatesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ScheduleDateResponse>> {
        const response = await this.getScheduleDatesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for startClosing without sending the request
     */
    async startClosingRequestOpts(requestParameters: StartClosingRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['scheduleDate'] == null) {
            throw new runtime.RequiredError(
                'scheduleDate',
                'Required parameter "scheduleDate" was null or undefined when calling startClosing().'
            );
        }

        if (requestParameters['scheduleDateActionRequest'] == null) {
            throw new runtime.RequiredError(
                'scheduleDateActionRequest',
                'Required parameter "scheduleDateActionRequest" was null or undefined when calling startClosing().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/admin/schedule-dates/{scheduleDate}/closing`;
        if (requestParameters['scheduleDate'] instanceof Date) {
            urlPath = urlPath.replace('{scheduleDate}', encodeURIComponent(requestParameters['scheduleDate'].toISOString().substring(0,10)));
        } else {
            urlPath = urlPath.replace('{scheduleDate}', encodeURIComponent(String(requestParameters['scheduleDate'])));
        }

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ScheduleDateActionRequestToJSON(requestParameters['scheduleDateActionRequest']),
        };
    }

    /**
     */
    async startClosingRaw(requestParameters: StartClosingRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ScheduleDateClosureImpactResponse>> {
        const requestOptions = await this.startClosingRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ScheduleDateClosureImpactResponseFromJSON(jsonValue));
    }

    /**
     */
    async startClosing(requestParameters: StartClosingRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ScheduleDateClosureImpactResponse> {
        const response = await this.startClosingRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
