/* tslint:disable */
/* eslint-disable */
/**
 * Horse Reservation API
 * 마장 예약 서비스 API
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type ReservationRejectRequest,
    ReservationRejectRequestFromJSON,
    ReservationRejectRequestToJSON,
} from '../models/ReservationRejectRequest';
import {
    type ReservationRejectResponse,
    ReservationRejectResponseFromJSON,
    ReservationRejectResponseToJSON,
} from '../models/ReservationRejectResponse';

export interface RejectRequest {
    reservationId: number;
    reservationRejectRequest: ReservationRejectRequest;
}

/**
 *
 */
export class AdminReservationRejectControllerApi extends runtime.BaseAPI {

    /**
     * Creates request options for reject without sending the request
     */
    async rejectRequestOpts(requestParameters: RejectRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['reservationId'] == null) {
            throw new runtime.RequiredError(
                'reservationId',
                'Required parameter "reservationId" was null or undefined when calling reject().'
            );
        }

        if (requestParameters['reservationRejectRequest'] == null) {
            throw new runtime.RequiredError(
                'reservationRejectRequest',
                'Required parameter "reservationRejectRequest" was null or undefined when calling reject().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/admin/reservations/{reservationId}/reject`;
        urlPath = urlPath.replace('{reservationId}', encodeURIComponent(String(requestParameters['reservationId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ReservationRejectRequestToJSON(requestParameters['reservationRejectRequest']),
        };
    }

    /**
     */
    async rejectRaw(requestParameters: RejectRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ReservationRejectResponse>> {
        const requestOptions = await this.rejectRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ReservationRejectResponseFromJSON(jsonValue));
    }

    /**
     */
    async reject(requestParameters: RejectRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ReservationRejectResponse> {
        const response = await this.rejectRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
