/* tslint:disable */
/* eslint-disable */
/**
 * Horse Reservation API
 * 마장 예약 서비스 API
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type AdminMemberResponse,
    AdminMemberResponseFromJSON,
    AdminMemberResponseToJSON,
} from '../models/AdminMemberResponse';
import {
    type MemberClassChangeReasonRequest,
    MemberClassChangeReasonRequestFromJSON,
    MemberClassChangeReasonRequestToJSON,
} from '../models/MemberClassChangeReasonRequest';
import {
    type MemberProgressionBaselineRequest,
    MemberProgressionBaselineRequestFromJSON,
    MemberProgressionBaselineRequestToJSON,
} from '../models/MemberProgressionBaselineRequest';
import {
    type MemberProgressionCreditCorrectionRequest,
    MemberProgressionCreditCorrectionRequestFromJSON,
    MemberProgressionCreditCorrectionRequestToJSON,
} from '../models/MemberProgressionCreditCorrectionRequest';
import {
    type MemberPromotionHoldRequest,
    MemberPromotionHoldRequestFromJSON,
    MemberPromotionHoldRequestToJSON,
} from '../models/MemberPromotionHoldRequest';
import {
    type MemberRideCountAdjustmentRequest,
    MemberRideCountAdjustmentRequestFromJSON,
    MemberRideCountAdjustmentRequestToJSON,
} from '../models/MemberRideCountAdjustmentRequest';

export interface AdjustMemberActualCompletedRideCountRequest {
    memberId: number;
    memberRideCountAdjustmentRequest: MemberRideCountAdjustmentRequest;
    ifMatch?: string;
}

export interface CorrectMemberSpecialApprovalCreditRequest {
    memberId: number;
    memberProgressionCreditCorrectionRequest: MemberProgressionCreditCorrectionRequest;
    ifMatch?: string;
}

export interface RemoveMemberProgressionBaselineRequest {
    memberId: number;
    memberClassChangeReasonRequest: MemberClassChangeReasonRequest;
    ifMatch?: string;
}

export interface RemoveMemberPromotionHoldRequest {
    memberId: number;
    memberClassChangeReasonRequest: MemberClassChangeReasonRequest;
    ifMatch?: string;
}

export interface SetMemberProgressionBaselineRequest {
    memberId: number;
    memberProgressionBaselineRequest: MemberProgressionBaselineRequest;
    ifMatch?: string;
}

export interface SetMemberPromotionHoldRequest {
    memberId: number;
    memberPromotionHoldRequest: MemberPromotionHoldRequest;
    ifMatch?: string;
}

/**
 *
 */
export class AdminMemberClassProgressionControllerApi extends runtime.BaseAPI {

    /**
     * Creates request options for adjustMemberActualCompletedRideCount without sending the request
     */
    async adjustMemberActualCompletedRideCountRequestOpts(requestParameters: AdjustMemberActualCompletedRideCountRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['memberId'] == null) {
            throw new runtime.RequiredError(
                'memberId',
                'Required parameter "memberId" was null or undefined when calling adjustMemberActualCompletedRideCount().'
            );
        }

        if (requestParameters['memberRideCountAdjustmentRequest'] == null) {
            throw new runtime.RequiredError(
                'memberRideCountAdjustmentRequest',
                'Required parameter "memberRideCountAdjustmentRequest" was null or undefined when calling adjustMemberActualCompletedRideCount().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['ifMatch'] != null) {
            headerParameters['If-Match'] = String(requestParameters['ifMatch']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/admin/members/{memberId}/class-progression/ride-count-adjustments`;
        urlPath = urlPath.replace('{memberId}', encodeURIComponent(String(requestParameters['memberId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: MemberRideCountAdjustmentRequestToJSON(requestParameters['memberRideCountAdjustmentRequest']),
        };
    }

    /**
     */
    async adjustMemberActualCompletedRideCountRaw(requestParameters: AdjustMemberActualCompletedRideCountRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AdminMemberResponse>> {
        const requestOptions = await this.adjustMemberActualCompletedRideCountRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AdminMemberResponseFromJSON(jsonValue));
    }

    /**
     */
    async adjustMemberActualCompletedRideCount(requestParameters: AdjustMemberActualCompletedRideCountRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AdminMemberResponse> {
        const response = await this.adjustMemberActualCompletedRideCountRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for correctMemberSpecialApprovalCredit without sending the request
     */
    async correctMemberSpecialApprovalCreditRequestOpts(requestParameters: CorrectMemberSpecialApprovalCreditRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['memberId'] == null) {
            throw new runtime.RequiredError(
                'memberId',
                'Required parameter "memberId" was null or undefined when calling correctMemberSpecialApprovalCredit().'
            );
        }

        if (requestParameters['memberProgressionCreditCorrectionRequest'] == null) {
            throw new runtime.RequiredError(
                'memberProgressionCreditCorrectionRequest',
                'Required parameter "memberProgressionCreditCorrectionRequest" was null or undefined when calling correctMemberSpecialApprovalCredit().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['ifMatch'] != null) {
            headerParameters['If-Match'] = String(requestParameters['ifMatch']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/admin/members/{memberId}/class-progression/special-approval-credit`;
        urlPath = urlPath.replace('{memberId}', encodeURIComponent(String(requestParameters['memberId'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: MemberProgressionCreditCorrectionRequestToJSON(requestParameters['memberProgressionCreditCorrectionRequest']),
        };
    }

    /**
     */
    async correctMemberSpecialApprovalCreditRaw(requestParameters: CorrectMemberSpecialApprovalCreditRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AdminMemberResponse>> {
        const requestOptions = await this.correctMemberSpecialApprovalCreditRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AdminMemberResponseFromJSON(jsonValue));
    }

    /**
     */
    async correctMemberSpecialApprovalCredit(requestParameters: CorrectMemberSpecialApprovalCreditRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AdminMemberResponse> {
        const response = await this.correctMemberSpecialApprovalCreditRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for removeMemberProgressionBaseline without sending the request
     */
    async removeMemberProgressionBaselineRequestOpts(requestParameters: RemoveMemberProgressionBaselineRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['memberId'] == null) {
            throw new runtime.RequiredError(
                'memberId',
                'Required parameter "memberId" was null or undefined when calling removeMemberProgressionBaseline().'
            );
        }

        if (requestParameters['memberClassChangeReasonRequest'] == null) {
            throw new runtime.RequiredError(
                'memberClassChangeReasonRequest',
                'Required parameter "memberClassChangeReasonRequest" was null or undefined when calling removeMemberProgressionBaseline().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['ifMatch'] != null) {
            headerParameters['If-Match'] = String(requestParameters['ifMatch']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/admin/members/{memberId}/class-progression/baseline`;
        urlPath = urlPath.replace('{memberId}', encodeURIComponent(String(requestParameters['memberId'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
            body: MemberClassChangeReasonRequestToJSON(requestParameters['memberClassChangeReasonRequest']),
        };
    }

    /**
     */
    async removeMemberProgressionBaselineRaw(requestParameters: RemoveMemberProgressionBaselineRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AdminMemberResponse>> {
        const requestOptions = await this.removeMemberProgressionBaselineRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AdminMemberResponseFromJSON(jsonValue));
    }

    /**
     */
    async removeMemberProgressionBaseline(requestParameters: RemoveMemberProgressionBaselineRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AdminMemberResponse> {
        const response = await this.removeMemberProgressionBaselineRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for removeMemberPromotionHold without sending the request
     */
    async removeMemberPromotionHoldRequestOpts(requestParameters: RemoveMemberPromotionHoldRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['memberId'] == null) {
            throw new runtime.RequiredError(
                'memberId',
                'Required parameter "memberId" was null or undefined when calling removeMemberPromotionHold().'
            );
        }

        if (requestParameters['memberClassChangeReasonRequest'] == null) {
            throw new runtime.RequiredError(
                'memberClassChangeReasonRequest',
                'Required parameter "memberClassChangeReasonRequest" was null or undefined when calling removeMemberPromotionHold().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['ifMatch'] != null) {
            headerParameters['If-Match'] = String(requestParameters['ifMatch']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/admin/members/{memberId}/class-progression/promotion-hold`;
        urlPath = urlPath.replace('{memberId}', encodeURIComponent(String(requestParameters['memberId'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
            body: MemberClassChangeReasonRequestToJSON(requestParameters['memberClassChangeReasonRequest']),
        };
    }

    /**
     */
    async removeMemberPromotionHoldRaw(requestParameters: RemoveMemberPromotionHoldRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AdminMemberResponse>> {
        const requestOptions = await this.removeMemberPromotionHoldRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AdminMemberResponseFromJSON(jsonValue));
    }

    /**
     */
    async removeMemberPromotionHold(requestParameters: RemoveMemberPromotionHoldRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AdminMemberResponse> {
        const response = await this.removeMemberPromotionHoldRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for setMemberProgressionBaseline without sending the request
     */
    async setMemberProgressionBaselineRequestOpts(requestParameters: SetMemberProgressionBaselineRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['memberId'] == null) {
            throw new runtime.RequiredError(
                'memberId',
                'Required parameter "memberId" was null or undefined when calling setMemberProgressionBaseline().'
            );
        }

        if (requestParameters['memberProgressionBaselineRequest'] == null) {
            throw new runtime.RequiredError(
                'memberProgressionBaselineRequest',
                'Required parameter "memberProgressionBaselineRequest" was null or undefined when calling setMemberProgressionBaseline().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['ifMatch'] != null) {
            headerParameters['If-Match'] = String(requestParameters['ifMatch']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/admin/members/{memberId}/class-progression/baseline`;
        urlPath = urlPath.replace('{memberId}', encodeURIComponent(String(requestParameters['memberId'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: MemberProgressionBaselineRequestToJSON(requestParameters['memberProgressionBaselineRequest']),
        };
    }

    /**
     */
    async setMemberProgressionBaselineRaw(requestParameters: SetMemberProgressionBaselineRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AdminMemberResponse>> {
        const requestOptions = await this.setMemberProgressionBaselineRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AdminMemberResponseFromJSON(jsonValue));
    }

    /**
     */
    async setMemberProgressionBaseline(requestParameters: SetMemberProgressionBaselineRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AdminMemberResponse> {
        const response = await this.setMemberProgressionBaselineRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for setMemberPromotionHold without sending the request
     */
    async setMemberPromotionHoldRequestOpts(requestParameters: SetMemberPromotionHoldRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['memberId'] == null) {
            throw new runtime.RequiredError(
                'memberId',
                'Required parameter "memberId" was null or undefined when calling setMemberPromotionHold().'
            );
        }

        if (requestParameters['memberPromotionHoldRequest'] == null) {
            throw new runtime.RequiredError(
                'memberPromotionHoldRequest',
                'Required parameter "memberPromotionHoldRequest" was null or undefined when calling setMemberPromotionHold().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['ifMatch'] != null) {
            headerParameters['If-Match'] = String(requestParameters['ifMatch']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/admin/members/{memberId}/class-progression/promotion-hold`;
        urlPath = urlPath.replace('{memberId}', encodeURIComponent(String(requestParameters['memberId'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: MemberPromotionHoldRequestToJSON(requestParameters['memberPromotionHoldRequest']),
        };
    }

    /**
     */
    async setMemberPromotionHoldRaw(requestParameters: SetMemberPromotionHoldRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AdminMemberResponse>> {
        const requestOptions = await this.setMemberPromotionHoldRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AdminMemberResponseFromJSON(jsonValue));
    }

    /**
     */
    async setMemberPromotionHold(requestParameters: SetMemberPromotionHoldRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AdminMemberResponse> {
        const response = await this.setMemberPromotionHoldRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
