/* tslint:disable */
/* eslint-disable */
/**
 * Horse Reservation API
 * 마장 예약 서비스 API
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type AdminReservationAuditPageResponse,
    AdminReservationAuditPageResponseFromJSON,
    AdminReservationAuditPageResponseToJSON,
} from '../models/AdminReservationAuditPageResponse';

export interface GetAuditLogsRequest {
    keyword?: string;
    reservationId?: number;
    occurredDateFrom?: Date;
    occurredDateTo?: Date;
    actorType?: string;
    changeType?: string;
    page?: number;
    size?: number;
}

/**
 *
 */
export class AdminReservationAuditQueryControllerApi extends runtime.BaseAPI {

    /**
     * Creates request options for getAuditLogs without sending the request
     */
    async getAuditLogsRequestOpts(requestParameters: GetAuditLogsRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['keyword'] != null) {
            queryParameters['keyword'] = requestParameters['keyword'];
        }

        if (requestParameters['reservationId'] != null) {
            queryParameters['reservationId'] = requestParameters['reservationId'];
        }

        if (requestParameters['occurredDateFrom'] != null) {
            queryParameters['occurredDateFrom'] = (requestParameters['occurredDateFrom'] as any).toISOString().substring(0,10);
        }

        if (requestParameters['occurredDateTo'] != null) {
            queryParameters['occurredDateTo'] = (requestParameters['occurredDateTo'] as any).toISOString().substring(0,10);
        }

        if (requestParameters['actorType'] != null) {
            queryParameters['actorType'] = requestParameters['actorType'];
        }

        if (requestParameters['changeType'] != null) {
            queryParameters['changeType'] = requestParameters['changeType'];
        }

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['size'] != null) {
            queryParameters['size'] = requestParameters['size'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/admin/audit-logs`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async getAuditLogsRaw(requestParameters: GetAuditLogsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AdminReservationAuditPageResponse>> {
        const requestOptions = await this.getAuditLogsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AdminReservationAuditPageResponseFromJSON(jsonValue));
    }

    /**
     */
    async getAuditLogs(requestParameters: GetAuditLogsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AdminReservationAuditPageResponse> {
        const response = await this.getAuditLogsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
