/* tslint:disable */
/* eslint-disable */
/**
 * Horse Reservation API
 * 마장 예약 서비스 API
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type AdminMemberResponse,
    AdminMemberResponseFromJSON,
    AdminMemberResponseToJSON,
} from '../models/AdminMemberResponse';
import {
    type MemberRidingPermissionUpdateRequest,
    MemberRidingPermissionUpdateRequestFromJSON,
    MemberRidingPermissionUpdateRequestToJSON,
} from '../models/MemberRidingPermissionUpdateRequest';

export interface ChangeRidingPermissionsRequest {
    memberId: number;
    memberRidingPermissionUpdateRequest: MemberRidingPermissionUpdateRequest;
}

/**
 *
 */
export class AdminMemberRidingPermissionControllerApi extends runtime.BaseAPI {

    /**
     * Creates request options for changeRidingPermissions without sending the request
     */
    async changeRidingPermissionsRequestOpts(requestParameters: ChangeRidingPermissionsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['memberId'] == null) {
            throw new runtime.RequiredError(
                'memberId',
                'Required parameter "memberId" was null or undefined when calling changeRidingPermissions().'
            );
        }

        if (requestParameters['memberRidingPermissionUpdateRequest'] == null) {
            throw new runtime.RequiredError(
                'memberRidingPermissionUpdateRequest',
                'Required parameter "memberRidingPermissionUpdateRequest" was null or undefined when calling changeRidingPermissions().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/admin/members/{memberId}/riding-permissions`;
        urlPath = urlPath.replace('{memberId}', encodeURIComponent(String(requestParameters['memberId'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: MemberRidingPermissionUpdateRequestToJSON(requestParameters['memberRidingPermissionUpdateRequest']),
        };
    }

    /**
     */
    async changeRidingPermissionsRaw(requestParameters: ChangeRidingPermissionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AdminMemberResponse>> {
        const requestOptions = await this.changeRidingPermissionsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AdminMemberResponseFromJSON(jsonValue));
    }

    /**
     */
    async changeRidingPermissions(requestParameters: ChangeRidingPermissionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AdminMemberResponse> {
        const response = await this.changeRidingPermissionsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
