/* tslint:disable */
/* eslint-disable */
/**
 * Horse Reservation API
 * 마장 예약 서비스 API
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type ErrorResponse,
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
} from '../models/ErrorResponse';
import {
    type ScheduleSynchronizationResponse,
    ScheduleSynchronizationResponseFromJSON,
    ScheduleSynchronizationResponseToJSON,
} from '../models/ScheduleSynchronizationResponse';
import {
    type ScheduleSynchronizationResultResponse,
    ScheduleSynchronizationResultResponseFromJSON,
    ScheduleSynchronizationResultResponseToJSON,
} from '../models/ScheduleSynchronizationResultResponse';
import {
    type ScheduleSynchronizationRetryRequest,
    ScheduleSynchronizationRetryRequestFromJSON,
    ScheduleSynchronizationRetryRequestToJSON,
} from '../models/ScheduleSynchronizationRetryRequest';

export interface RetryRequest {
    scheduleSynchronizationRetryRequest: ScheduleSynchronizationRetryRequest;
}

/**
 *
 */
export class AdminScheduleSynchronizationControllerApi extends runtime.BaseAPI {

    /**
     * Creates request options for getStatus without sending the request
     */
    async getStatusRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/admin/schedule-sync`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async getStatusRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ScheduleSynchronizationResponse>> {
        const requestOptions = await this.getStatusRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ScheduleSynchronizationResponseFromJSON(jsonValue));
    }

    /**
     */
    async getStatus(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ScheduleSynchronizationResponse> {
        const response = await this.getStatusRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for retry without sending the request
     */
    async retryRequestOpts(requestParameters: RetryRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['scheduleSynchronizationRetryRequest'] == null) {
            throw new runtime.RequiredError(
                'scheduleSynchronizationRetryRequest',
                'Required parameter "scheduleSynchronizationRetryRequest" was null or undefined when calling retry().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/admin/jobs/sync-schedule-occurrences/retry`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ScheduleSynchronizationRetryRequestToJSON(requestParameters['scheduleSynchronizationRetryRequest']),
        };
    }

    /**
     */
    async retryRaw(requestParameters: RetryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ScheduleSynchronizationResultResponse>> {
        const requestOptions = await this.retryRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ScheduleSynchronizationResultResponseFromJSON(jsonValue));
    }

    /**
     */
    async retry(requestParameters: RetryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ScheduleSynchronizationResultResponse> {
        const response = await this.retryRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
