/* tslint:disable */
/* eslint-disable */
/**
 * Horse Reservation API
 * 마장 예약 서비스 API
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type AdminMemberPageResponse,
    AdminMemberPageResponseFromJSON,
    AdminMemberPageResponseToJSON,
} from '../models/AdminMemberPageResponse';
import {
    type AdminMemberResponse,
    AdminMemberResponseFromJSON,
    AdminMemberResponseToJSON,
} from '../models/AdminMemberResponse';

export interface GetMemberRequest {
    memberId: number;
}

export interface GetMembersRequest {
    page?: number;
    size?: number;
}

/**
 *
 */
export class AdminMemberQueryControllerApi extends runtime.BaseAPI {

    /**
     * Creates request options for getMember without sending the request
     */
    async getMemberRequestOpts(requestParameters: GetMemberRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['memberId'] == null) {
            throw new runtime.RequiredError(
                'memberId',
                'Required parameter "memberId" was null or undefined when calling getMember().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/admin/members/{memberId}`;
        urlPath = urlPath.replace('{memberId}', encodeURIComponent(String(requestParameters['memberId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async getMemberRaw(requestParameters: GetMemberRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AdminMemberResponse>> {
        const requestOptions = await this.getMemberRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AdminMemberResponseFromJSON(jsonValue));
    }

    /**
     */
    async getMember(requestParameters: GetMemberRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AdminMemberResponse> {
        const response = await this.getMemberRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getMembers without sending the request
     */
    async getMembersRequestOpts(requestParameters: GetMembersRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['size'] != null) {
            queryParameters['size'] = requestParameters['size'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/admin/members`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async getMembersRaw(requestParameters: GetMembersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AdminMemberPageResponse>> {
        const requestOptions = await this.getMembersRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AdminMemberPageResponseFromJSON(jsonValue));
    }

    /**
     */
    async getMembers(requestParameters: GetMembersRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AdminMemberPageResponse> {
        const response = await this.getMembersRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
