/* tslint:disable */
/* eslint-disable */
/**
 * Horse Reservation API
 * 마장 예약 서비스 API
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type AdminReservationChangeRequest,
    AdminReservationChangeRequestFromJSON,
    AdminReservationChangeRequestToJSON,
} from '../models/AdminReservationChangeRequest';
import {
    type ReservationChangeResponse,
    ReservationChangeResponseFromJSON,
    ReservationChangeResponseToJSON,
} from '../models/ReservationChangeResponse';

export interface Change1Request {
    reservationId: number;
    adminReservationChangeRequest: AdminReservationChangeRequest;
}

/**
 *
 */
export class AdminReservationChangeControllerApi extends runtime.BaseAPI {

    /**
     * Creates request options for change1 without sending the request
     */
    async change1RequestOpts(requestParameters: Change1Request): Promise<runtime.RequestOpts> {
        if (requestParameters['reservationId'] == null) {
            throw new runtime.RequiredError(
                'reservationId',
                'Required parameter "reservationId" was null or undefined when calling change1().'
            );
        }

        if (requestParameters['adminReservationChangeRequest'] == null) {
            throw new runtime.RequiredError(
                'adminReservationChangeRequest',
                'Required parameter "adminReservationChangeRequest" was null or undefined when calling change1().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/admin/reservations/{reservationId}/change`;
        urlPath = urlPath.replace('{reservationId}', encodeURIComponent(String(requestParameters['reservationId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AdminReservationChangeRequestToJSON(requestParameters['adminReservationChangeRequest']),
        };
    }

    /**
     */
    async change1Raw(requestParameters: Change1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ReservationChangeResponse>> {
        const requestOptions = await this.change1RequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ReservationChangeResponseFromJSON(jsonValue));
    }

    /**
     */
    async change1(requestParameters: Change1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ReservationChangeResponse> {
        const response = await this.change1Raw(requestParameters, initOverrides);
        return await response.value();
    }

}
