/* tslint:disable */
/* eslint-disable */
/**
 * Horse Reservation API
 * 마장 예약 서비스 API
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type MemberReservationResponse,
    MemberReservationResponseFromJSON,
    MemberReservationResponseToJSON,
} from '../models/MemberReservationResponse';

/**
 *
 */
export class MemberReservationQueryControllerApi extends runtime.BaseAPI {

    /**
     * Creates request options for getMyReservations without sending the request
     */
    async getMyReservationsRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/me/reservations`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async getMyReservationsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<MemberReservationResponse>>> {
        const requestOptions = await this.getMyReservationsRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(MemberReservationResponseFromJSON));
    }

    /**
     */
    async getMyReservations(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<MemberReservationResponse>> {
        const response = await this.getMyReservationsRaw(initOverrides);
        return await response.value();
    }

}
