/* tslint:disable */
/* eslint-disable */
/**
 * Horse Reservation API
 * 마장 예약 서비스 API
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type ReservationApplicationRequest,
    ReservationApplicationRequestFromJSON,
    ReservationApplicationRequestToJSON,
} from '../models/ReservationApplicationRequest';
import {
    type ReservationApplicationResponse,
    ReservationApplicationResponseFromJSON,
    ReservationApplicationResponseToJSON,
} from '../models/ReservationApplicationResponse';

export interface ApplyRequest {
    idempotencyKey: string;
    reservationApplicationRequest: ReservationApplicationRequest;
}

/**
 *
 */
export class ReservationApplicationControllerApi extends runtime.BaseAPI {

    /**
     * Creates request options for apply without sending the request
     */
    async applyRequestOpts(requestParameters: ApplyRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['idempotencyKey'] == null) {
            throw new runtime.RequiredError(
                'idempotencyKey',
                'Required parameter "idempotencyKey" was null or undefined when calling apply().'
            );
        }

        if (requestParameters['reservationApplicationRequest'] == null) {
            throw new runtime.RequiredError(
                'reservationApplicationRequest',
                'Required parameter "reservationApplicationRequest" was null or undefined when calling apply().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['Idempotency-Key'] = String(requestParameters['idempotencyKey']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/reservations`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ReservationApplicationRequestToJSON(requestParameters['reservationApplicationRequest']),
        };
    }

    /**
     */
    async applyRaw(requestParameters: ApplyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ReservationApplicationResponse>> {
        const requestOptions = await this.applyRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ReservationApplicationResponseFromJSON(jsonValue));
    }

    /**
     */
    async apply(requestParameters: ApplyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ReservationApplicationResponse> {
        const response = await this.applyRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
