/* tslint:disable */
/* eslint-disable */
/**
 * Horse Reservation API
 * 마장 예약 서비스 API
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface AdminManualReservationRequest
 */
export interface AdminManualReservationRequest {
    /**
     *
     * @type {number}
     * @memberof AdminManualReservationRequest
     */
    memberId: number;
    /**
     *
     * @type {number}
     * @memberof AdminManualReservationRequest
     */
    timeSlotId: number;
    /**
     *
     * @type {string}
     * @memberof AdminManualReservationRequest
     */
    classType: string;
    /**
     *
     * @type {string}
     * @memberof AdminManualReservationRequest
     */
    reason: string;
}

/**
 * Check if a given object implements the AdminManualReservationRequest interface.
 */
export function instanceOfAdminManualReservationRequest(value: object): value is AdminManualReservationRequest {
    if (!('memberId' in value) || value['memberId'] === undefined) return false;
    if (!('timeSlotId' in value) || value['timeSlotId'] === undefined) return false;
    if (!('classType' in value) || value['classType'] === undefined) return false;
    if (!('reason' in value) || value['reason'] === undefined) return false;
    return true;
}

export function AdminManualReservationRequestFromJSON(json: any): AdminManualReservationRequest {
    return AdminManualReservationRequestFromJSONTyped(json, false);
}

export function AdminManualReservationRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdminManualReservationRequest {
    if (json == null) {
        return json;
    }
    return {

        'memberId': json['memberId'],
        'timeSlotId': json['timeSlotId'],
        'classType': json['classType'],
        'reason': json['reason'],
    };
}

export function AdminManualReservationRequestToJSON(json: any): AdminManualReservationRequest {
    return AdminManualReservationRequestToJSONTyped(json, false);
}

export function AdminManualReservationRequestToJSONTyped(value?: AdminManualReservationRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'memberId': value['memberId'],
        'timeSlotId': value['timeSlotId'],
        'classType': value['classType'],
        'reason': value['reason'],
    };
}
