/* tslint:disable */
/* eslint-disable */
/**
 * Horse Reservation API
 * 마장 예약 서비스 API
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AdminWeeklyOperationsTimeSlotResponse } from './AdminWeeklyOperationsTimeSlotResponse';
import {
    AdminWeeklyOperationsTimeSlotResponseFromJSON,
    AdminWeeklyOperationsTimeSlotResponseFromJSONTyped,
    AdminWeeklyOperationsTimeSlotResponseToJSON,
    AdminWeeklyOperationsTimeSlotResponseToJSONTyped,
} from './AdminWeeklyOperationsTimeSlotResponse';

/**
 *
 * @export
 * @interface AdminWeeklyOperationsCalendarResponse
 */
export interface AdminWeeklyOperationsCalendarResponse {
    /**
     *
     * @type {Date}
     * @memberof AdminWeeklyOperationsCalendarResponse
     */
    referenceDate: Date;
    /**
     *
     * @type {Date}
     * @memberof AdminWeeklyOperationsCalendarResponse
     */
    weekStartDate: Date;
    /**
     *
     * @type {Date}
     * @memberof AdminWeeklyOperationsCalendarResponse
     */
    weekEndDate: Date;
    /**
     *
     * @type {Array<AdminWeeklyOperationsTimeSlotResponse>}
     * @memberof AdminWeeklyOperationsCalendarResponse
     */
    timeSlots: Array<AdminWeeklyOperationsTimeSlotResponse>;
}

/**
 * Check if a given object implements the AdminWeeklyOperationsCalendarResponse interface.
 */
export function instanceOfAdminWeeklyOperationsCalendarResponse(value: object): value is AdminWeeklyOperationsCalendarResponse {
    if (!('referenceDate' in value) || value['referenceDate'] === undefined) return false;
    if (!('weekStartDate' in value) || value['weekStartDate'] === undefined) return false;
    if (!('weekEndDate' in value) || value['weekEndDate'] === undefined) return false;
    if (!('timeSlots' in value) || value['timeSlots'] === undefined) return false;
    return true;
}

export function AdminWeeklyOperationsCalendarResponseFromJSON(json: any): AdminWeeklyOperationsCalendarResponse {
    return AdminWeeklyOperationsCalendarResponseFromJSONTyped(json, false);
}

export function AdminWeeklyOperationsCalendarResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdminWeeklyOperationsCalendarResponse {
    if (json == null) {
        return json;
    }
    return {

        'referenceDate': (new Date(json['referenceDate'])),
        'weekStartDate': (new Date(json['weekStartDate'])),
        'weekEndDate': (new Date(json['weekEndDate'])),
        'timeSlots': ((json['timeSlots'] as Array<any>).map(AdminWeeklyOperationsTimeSlotResponseFromJSON)),
    };
}

export function AdminWeeklyOperationsCalendarResponseToJSON(json: any): AdminWeeklyOperationsCalendarResponse {
    return AdminWeeklyOperationsCalendarResponseToJSONTyped(json, false);
}

export function AdminWeeklyOperationsCalendarResponseToJSONTyped(value?: AdminWeeklyOperationsCalendarResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'referenceDate': value['referenceDate'].toISOString().substring(0,10),
        'weekStartDate': value['weekStartDate'].toISOString().substring(0,10),
        'weekEndDate': value['weekEndDate'].toISOString().substring(0,10),
        'timeSlots': ((value['timeSlots'] as Array<any>).map(AdminWeeklyOperationsTimeSlotResponseToJSON)),
    };
}
