/* tslint:disable */
/* eslint-disable */
/**
 * Horse Reservation API
 * 마장 예약 서비스 API
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AdminMonthlyRideLeaderResponse } from './AdminMonthlyRideLeaderResponse';
import {
    AdminMonthlyRideLeaderResponseFromJSON,
    AdminMonthlyRideLeaderResponseFromJSONTyped,
    AdminMonthlyRideLeaderResponseToJSON,
    AdminMonthlyRideLeaderResponseToJSONTyped,
} from './AdminMonthlyRideLeaderResponse';

/**
 *
 * @export
 * @interface AdminMonthlyRideStatisticsResponse
 */
export interface AdminMonthlyRideStatisticsResponse {
    /**
     *
     * @type {string}
     * @memberof AdminMonthlyRideStatisticsResponse
     */
    month: string;
    /**
     *
     * @type {AdminMonthlyRideStatisticsResponseRideTypeEnum}
     * @memberof AdminMonthlyRideStatisticsResponse
     */
    rideType: AdminMonthlyRideStatisticsResponseRideTypeEnum;
    /**
     *
     * @type {number}
     * @memberof AdminMonthlyRideStatisticsResponse
     */
    totalCompletedRideCount: number;
    /**
     *
     * @type {number}
     * @memberof AdminMonthlyRideStatisticsResponse
     */
    topCompletedRideCount: number;
    /**
     *
     * @type {Array<AdminMonthlyRideLeaderResponse>}
     * @memberof AdminMonthlyRideStatisticsResponse
     */
    leaders: Array<AdminMonthlyRideLeaderResponse>;
}


/**
 * @export
 */
export const AdminMonthlyRideStatisticsResponseRideTypeEnum = {
    All: 'ALL',
    General: 'GENERAL',
    Dressage: 'DRESSAGE',
    Jumping: 'JUMPING'
} as const;
export type AdminMonthlyRideStatisticsResponseRideTypeEnum = typeof AdminMonthlyRideStatisticsResponseRideTypeEnum[keyof typeof AdminMonthlyRideStatisticsResponseRideTypeEnum];


/**
 * Check if a given object implements the AdminMonthlyRideStatisticsResponse interface.
 */
export function instanceOfAdminMonthlyRideStatisticsResponse(value: object): value is AdminMonthlyRideStatisticsResponse {
    if (!('month' in value) || value['month'] === undefined) return false;
    if (!('rideType' in value) || value['rideType'] === undefined) return false;
    if (!('totalCompletedRideCount' in value) || value['totalCompletedRideCount'] === undefined) return false;
    if (!('topCompletedRideCount' in value) || value['topCompletedRideCount'] === undefined) return false;
    if (!('leaders' in value) || value['leaders'] === undefined) return false;
    return true;
}

export function AdminMonthlyRideStatisticsResponseFromJSON(json: any): AdminMonthlyRideStatisticsResponse {
    return AdminMonthlyRideStatisticsResponseFromJSONTyped(json, false);
}

export function AdminMonthlyRideStatisticsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdminMonthlyRideStatisticsResponse {
    if (json == null) {
        return json;
    }
    return {

        'month': json['month'],
        'rideType': json['rideType'],
        'totalCompletedRideCount': json['totalCompletedRideCount'],
        'topCompletedRideCount': json['topCompletedRideCount'],
        'leaders': ((json['leaders'] as Array<any>).map(AdminMonthlyRideLeaderResponseFromJSON)),
    };
}

export function AdminMonthlyRideStatisticsResponseToJSON(json: any): AdminMonthlyRideStatisticsResponse {
    return AdminMonthlyRideStatisticsResponseToJSONTyped(json, false);
}

export function AdminMonthlyRideStatisticsResponseToJSONTyped(value?: AdminMonthlyRideStatisticsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'month': value['month'],
        'rideType': value['rideType'],
        'totalCompletedRideCount': value['totalCompletedRideCount'],
        'topCompletedRideCount': value['topCompletedRideCount'],
        'leaders': ((value['leaders'] as Array<any>).map(AdminMonthlyRideLeaderResponseToJSON)),
    };
}
