/* tslint:disable */
/* eslint-disable */
/**
 * Horse Reservation API
 * 마장 예약 서비스 API
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AdminReservationResponse } from './AdminReservationResponse';
import {
    AdminReservationResponseFromJSON,
    AdminReservationResponseFromJSONTyped,
    AdminReservationResponseToJSON,
    AdminReservationResponseToJSONTyped,
} from './AdminReservationResponse';

/**
 *
 * @export
 * @interface AdminReservationPageResponse
 */
export interface AdminReservationPageResponse {
    /**
     *
     * @type {Array<AdminReservationResponse>}
     * @memberof AdminReservationPageResponse
     */
    content?: Array<AdminReservationResponse>;
    /**
     *
     * @type {number}
     * @memberof AdminReservationPageResponse
     */
    page?: number;
    /**
     *
     * @type {number}
     * @memberof AdminReservationPageResponse
     */
    size?: number;
    /**
     *
     * @type {number}
     * @memberof AdminReservationPageResponse
     */
    totalElements?: number;
    /**
     *
     * @type {number}
     * @memberof AdminReservationPageResponse
     */
    totalPages?: number;
    /**
     *
     * @type {boolean}
     * @memberof AdminReservationPageResponse
     */
    hasNext?: boolean;
}

/**
 * Check if a given object implements the AdminReservationPageResponse interface.
 */
export function instanceOfAdminReservationPageResponse(value: object): value is AdminReservationPageResponse {
    return true;
}

export function AdminReservationPageResponseFromJSON(json: any): AdminReservationPageResponse {
    return AdminReservationPageResponseFromJSONTyped(json, false);
}

export function AdminReservationPageResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdminReservationPageResponse {
    if (json == null) {
        return json;
    }
    return {

        'content': json['content'] == null ? undefined : ((json['content'] as Array<any>).map(AdminReservationResponseFromJSON)),
        'page': json['page'] == null ? undefined : json['page'],
        'size': json['size'] == null ? undefined : json['size'],
        'totalElements': json['totalElements'] == null ? undefined : json['totalElements'],
        'totalPages': json['totalPages'] == null ? undefined : json['totalPages'],
        'hasNext': json['hasNext'] == null ? undefined : json['hasNext'],
    };
}

export function AdminReservationPageResponseToJSON(json: any): AdminReservationPageResponse {
    return AdminReservationPageResponseToJSONTyped(json, false);
}

export function AdminReservationPageResponseToJSONTyped(value?: AdminReservationPageResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'content': value['content'] == null ? undefined : ((value['content'] as Array<any>).map(AdminReservationResponseToJSON)),
        'page': value['page'],
        'size': value['size'],
        'totalElements': value['totalElements'],
        'totalPages': value['totalPages'],
        'hasNext': value['hasNext'],
    };
}

