/* tslint:disable */
/* eslint-disable */
/**
 * Horse Reservation API
 * 마장 예약 서비스 API
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface AdminReservationChangeRequest
 */
export interface AdminReservationChangeRequest {
    /**
     *
     * @type {number}
     * @memberof AdminReservationChangeRequest
     */
    targetTimeSlotId?: number;
    /**
     *
     * @type {string}
     * @memberof AdminReservationChangeRequest
     */
    memo?: string;
}

/**
 * Check if a given object implements the AdminReservationChangeRequest interface.
 */
export function instanceOfAdminReservationChangeRequest(value: object): value is AdminReservationChangeRequest {
    return true;
}

export function AdminReservationChangeRequestFromJSON(json: any): AdminReservationChangeRequest {
    return AdminReservationChangeRequestFromJSONTyped(json, false);
}

export function AdminReservationChangeRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdminReservationChangeRequest {
    if (json == null) {
        return json;
    }
    return {

        'targetTimeSlotId': json['targetTimeSlotId'] == null ? undefined : json['targetTimeSlotId'],
        'memo': json['memo'] == null ? undefined : json['memo'],
    };
}

export function AdminReservationChangeRequestToJSON(json: any): AdminReservationChangeRequest {
    return AdminReservationChangeRequestToJSONTyped(json, false);
}

export function AdminReservationChangeRequestToJSONTyped(value?: AdminReservationChangeRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'targetTimeSlotId': value['targetTimeSlotId'],
        'memo': value['memo'],
    };
}

