/* tslint:disable */
/* eslint-disable */
/**
 * Horse Reservation API
 * 마장 예약 서비스 API
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ReservationStatusCountResponse } from './ReservationStatusCountResponse';
import {
    ReservationStatusCountResponseFromJSON,
    ReservationStatusCountResponseFromJSONTyped,
    ReservationStatusCountResponseToJSON,
    ReservationStatusCountResponseToJSONTyped,
} from './ReservationStatusCountResponse';
import type { AdminReservationDailySummaryResponse } from './AdminReservationDailySummaryResponse';
import {
    AdminReservationDailySummaryResponseFromJSON,
    AdminReservationDailySummaryResponseFromJSONTyped,
    AdminReservationDailySummaryResponseToJSON,
    AdminReservationDailySummaryResponseToJSONTyped,
} from './AdminReservationDailySummaryResponse';

/**
 *
 * @export
 * @interface AdminReservationSummaryResponse
 */
export interface AdminReservationSummaryResponse {
    /**
     *
     * @type {Date}
     * @memberof AdminReservationSummaryResponse
     */
    lessonDateFrom: Date;
    /**
     *
     * @type {Date}
     * @memberof AdminReservationSummaryResponse
     */
    lessonDateTo: Date;
    /**
     *
     * @type {number}
     * @memberof AdminReservationSummaryResponse
     */
    totalCount: number;
    /**
     *
     * @type {Array<ReservationStatusCountResponse>}
     * @memberof AdminReservationSummaryResponse
     */
    statusCounts: Array<ReservationStatusCountResponse>;
    /**
     *
     * @type {Array<AdminReservationDailySummaryResponse>}
     * @memberof AdminReservationSummaryResponse
     */
    dailyCounts: Array<AdminReservationDailySummaryResponse>;
}

/**
 * Check if a given object implements the AdminReservationSummaryResponse interface.
 */
export function instanceOfAdminReservationSummaryResponse(value: object): value is AdminReservationSummaryResponse {
    if (!('lessonDateFrom' in value) || value['lessonDateFrom'] === undefined) return false;
    if (!('lessonDateTo' in value) || value['lessonDateTo'] === undefined) return false;
    if (!('totalCount' in value) || value['totalCount'] === undefined) return false;
    if (!('statusCounts' in value) || value['statusCounts'] === undefined) return false;
    if (!('dailyCounts' in value) || value['dailyCounts'] === undefined) return false;
    return true;
}

export function AdminReservationSummaryResponseFromJSON(json: any): AdminReservationSummaryResponse {
    return AdminReservationSummaryResponseFromJSONTyped(json, false);
}

export function AdminReservationSummaryResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdminReservationSummaryResponse {
    if (json == null) {
        return json;
    }
    return {

        'lessonDateFrom': (new Date(json['lessonDateFrom'])),
        'lessonDateTo': (new Date(json['lessonDateTo'])),
        'totalCount': json['totalCount'],
        'statusCounts': ((json['statusCounts'] as Array<any>).map(ReservationStatusCountResponseFromJSON)),
        'dailyCounts': ((json['dailyCounts'] as Array<any>).map(AdminReservationDailySummaryResponseFromJSON)),
    };
}

export function AdminReservationSummaryResponseToJSON(json: any): AdminReservationSummaryResponse {
    return AdminReservationSummaryResponseToJSONTyped(json, false);
}

export function AdminReservationSummaryResponseToJSONTyped(value?: AdminReservationSummaryResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'lessonDateFrom': value['lessonDateFrom'].toISOString().substring(0,10),
        'lessonDateTo': value['lessonDateTo'].toISOString().substring(0,10),
        'totalCount': value['totalCount'],
        'statusCounts': ((value['statusCounts'] as Array<any>).map(ReservationStatusCountResponseToJSON)),
        'dailyCounts': ((value['dailyCounts'] as Array<any>).map(AdminReservationDailySummaryResponseToJSON)),
    };
}

