/* tslint:disable */
/* eslint-disable */
/**
 * Horse Reservation API
 * 마장 예약 서비스 API
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AdminReservationCouponResponse } from './AdminReservationCouponResponse';
import {
    AdminReservationCouponResponseFromJSON,
    AdminReservationCouponResponseFromJSONTyped,
    AdminReservationCouponResponseToJSON,
    AdminReservationCouponResponseToJSONTyped,
} from './AdminReservationCouponResponse';
import type { ReservationActionsResponse } from './ReservationActionsResponse';
import {
    ReservationActionsResponseFromJSON,
    ReservationActionsResponseFromJSONTyped,
    ReservationActionsResponseToJSON,
    ReservationActionsResponseToJSONTyped,
} from './ReservationActionsResponse';

/**
 *
 * @export
 * @interface AdminReservationResponse
 */
export interface AdminReservationResponse {
    /**
     *
     * @type {number}
     * @memberof AdminReservationResponse
     */
    reservationId?: number;
    /**
     *
     * @type {number}
     * @memberof AdminReservationResponse
     */
    memberId?: number;
    /**
     *
     * @type {string}
     * @memberof AdminReservationResponse
     */
    memberName?: string;
    /**
     *
     * @type {string}
     * @memberof AdminReservationResponse
     */
    memberPhone?: string;
    /**
     *
     * @type {string}
     * @memberof AdminReservationResponse
     */
    classType?: string;
    /**
     *
     * @type {Date}
     * @memberof AdminReservationResponse
     */
    lessonDate?: Date;
    /**
     *
     * @type {string}
     * @memberof AdminReservationResponse
     */
    startTime?: string;
    /**
     *
     * @type {string}
     * @memberof AdminReservationResponse
     */
    status?: string;
    /**
     *
     * @type {string}
     * @memberof AdminReservationResponse
     */
    paymentSource?: string;
    /**
     *
     * @type {AdminReservationCouponResponse}
     * @memberof AdminReservationResponse
     */
    coupon?: AdminReservationCouponResponse;
    /**
     *
     * @type {Date}
     * @memberof AdminReservationResponse
     */
    paymentDueAt?: Date;
    /**
     *
     * @type {Date}
     * @memberof AdminReservationResponse
     */
    approvalRequestedAt?: Date;
    /**
     *
     * @type {Date}
     * @memberof AdminReservationResponse
     */
    adminConfirmedAt?: Date;
    /**
     *
     * @type {Date}
     * @memberof AdminReservationResponse
     */
    rejectedAt?: Date;
    /**
     *
     * @type {string}
     * @memberof AdminReservationResponse
     */
    rejectedBy?: string;
    /**
     *
     * @type {string}
     * @memberof AdminReservationResponse
     */
    rejectionReason?: string;
    /**
     *
     * @type {Date}
     * @memberof AdminReservationResponse
     */
    cancelledAt?: Date;
    /**
     *
     * @type {string}
     * @memberof AdminReservationResponse
     */
    cancellationResponsibility?: string;
    /**
     *
     * @type {string}
     * @memberof AdminReservationResponse
     */
    couponAction?: string;
    /**
     *
     * @type {string}
     * @memberof AdminReservationResponse
     */
    adminMemo?: string;
    /**
     *
     * @type {string}
     * @memberof AdminReservationResponse
     */
    approvalWarning?: string;
    /**
     *
     * @type {Date}
     * @memberof AdminReservationResponse
     */
    createdAt?: Date;
    /**
     *
     * @type {Date}
     * @memberof AdminReservationResponse
     */
    updatedAt?: Date;
    /**
     *
     * @type {string}
     * @memberof AdminReservationResponse
     */
    displayGroup?: string;
    /**
     *
     * @type {ReservationActionsResponse}
     * @memberof AdminReservationResponse
     */
    actions?: ReservationActionsResponse;
}

/**
 * Check if a given object implements the AdminReservationResponse interface.
 */
export function instanceOfAdminReservationResponse(value: object): value is AdminReservationResponse {
    return true;
}

export function AdminReservationResponseFromJSON(json: any): AdminReservationResponse {
    return AdminReservationResponseFromJSONTyped(json, false);
}

export function AdminReservationResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdminReservationResponse {
    if (json == null) {
        return json;
    }
    return {

        'reservationId': json['reservationId'] == null ? undefined : json['reservationId'],
        'memberId': json['memberId'] == null ? undefined : json['memberId'],
        'memberName': json['memberName'] == null ? undefined : json['memberName'],
        'memberPhone': json['memberPhone'] == null ? undefined : json['memberPhone'],
        'classType': json['classType'] == null ? undefined : json['classType'],
        'lessonDate': json['lessonDate'] == null ? undefined : (new Date(json['lessonDate'])),
        'startTime': json['startTime'] == null ? undefined : json['startTime'],
        'status': json['status'] == null ? undefined : json['status'],
        'paymentSource': json['paymentSource'] == null ? undefined : json['paymentSource'],
        'coupon': json['coupon'] == null ? undefined : AdminReservationCouponResponseFromJSON(json['coupon']),
        'paymentDueAt': json['paymentDueAt'] == null ? undefined : (new Date(json['paymentDueAt'])),
        'approvalRequestedAt': json['approvalRequestedAt'] == null ? undefined : (new Date(json['approvalRequestedAt'])),
        'adminConfirmedAt': json['adminConfirmedAt'] == null ? undefined : (new Date(json['adminConfirmedAt'])),
        'rejectedAt': json['rejectedAt'] == null ? undefined : (new Date(json['rejectedAt'])),
        'rejectedBy': json['rejectedBy'] == null ? undefined : json['rejectedBy'],
        'rejectionReason': json['rejectionReason'] == null ? undefined : json['rejectionReason'],
        'cancelledAt': json['cancelledAt'] == null ? undefined : (new Date(json['cancelledAt'])),
        'cancellationResponsibility': json['cancellationResponsibility'] == null ? undefined : json['cancellationResponsibility'],
        'couponAction': json['couponAction'] == null ? undefined : json['couponAction'],
        'adminMemo': json['adminMemo'] == null ? undefined : json['adminMemo'],
        'approvalWarning': json['approvalWarning'] == null ? undefined : json['approvalWarning'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'updatedAt': json['updatedAt'] == null ? undefined : (new Date(json['updatedAt'])),
        'displayGroup': json['displayGroup'] == null ? undefined : json['displayGroup'],
        'actions': json['actions'] == null ? undefined : ReservationActionsResponseFromJSON(json['actions']),
    };
}

export function AdminReservationResponseToJSON(json: any): AdminReservationResponse {
    return AdminReservationResponseToJSONTyped(json, false);
}

export function AdminReservationResponseToJSONTyped(value?: AdminReservationResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'reservationId': value['reservationId'],
        'memberId': value['memberId'],
        'memberName': value['memberName'],
        'memberPhone': value['memberPhone'],
        'classType': value['classType'],
        'lessonDate': value['lessonDate'] == null ? value['lessonDate'] : value['lessonDate'].toISOString().substring(0,10),
        'startTime': value['startTime'],
        'status': value['status'],
        'paymentSource': value['paymentSource'],
        'coupon': AdminReservationCouponResponseToJSON(value['coupon']),
        'paymentDueAt': value['paymentDueAt'] == null ? value['paymentDueAt'] : value['paymentDueAt'].toISOString(),
        'approvalRequestedAt': value['approvalRequestedAt'] == null ? value['approvalRequestedAt'] : value['approvalRequestedAt'].toISOString(),
        'adminConfirmedAt': value['adminConfirmedAt'] == null ? value['adminConfirmedAt'] : value['adminConfirmedAt'].toISOString(),
        'rejectedAt': value['rejectedAt'] == null ? value['rejectedAt'] : value['rejectedAt'].toISOString(),
        'rejectedBy': value['rejectedBy'],
        'rejectionReason': value['rejectionReason'],
        'cancelledAt': value['cancelledAt'] == null ? value['cancelledAt'] : value['cancelledAt'].toISOString(),
        'cancellationResponsibility': value['cancellationResponsibility'],
        'couponAction': value['couponAction'],
        'adminMemo': value['adminMemo'],
        'approvalWarning': value['approvalWarning'],
        'createdAt': value['createdAt'] == null ? value['createdAt'] : value['createdAt'].toISOString(),
        'updatedAt': value['updatedAt'] == null ? value['updatedAt'] : value['updatedAt'].toISOString(),
        'displayGroup': value['displayGroup'],
        'actions': ReservationActionsResponseToJSON(value['actions']),
    };
}

