/* tslint:disable */
/* eslint-disable */
/**
 * Horse Reservation API
 * 마장 예약 서비스 API
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AdminReservationCouponResponse } from './AdminReservationCouponResponse';
import {
    AdminReservationCouponResponseFromJSON,
    AdminReservationCouponResponseFromJSONTyped,
    AdminReservationCouponResponseToJSON,
    AdminReservationCouponResponseToJSONTyped,
} from './AdminReservationCouponResponse';
import type { ReservationActionsResponse } from './ReservationActionsResponse';
import {
    ReservationActionsResponseFromJSON,
    ReservationActionsResponseFromJSONTyped,
    ReservationActionsResponseToJSON,
    ReservationActionsResponseToJSONTyped,
} from './ReservationActionsResponse';

/**
 *
 * @export
 * @interface AdminReservationResponse
 */
export interface AdminReservationResponse {
    /**
     *
     * @type {number}
     * @memberof AdminReservationResponse
     */
    reservationId: number;
    /**
     *
     * @type {number}
     * @memberof AdminReservationResponse
     */
    memberId: number;
    /**
     *
     * @type {string}
     * @memberof AdminReservationResponse
     */
    memberName: string;
    /**
     *
     * @type {string}
     * @memberof AdminReservationResponse
     */
    memberPhone: string;
    /**
     *
     * @type {string}
     * @memberof AdminReservationResponse
     */
    classType: string;
    /**
     *
     * @type {Date}
     * @memberof AdminReservationResponse
     */
    lessonDate: Date;
    /**
     *
     * @type {string}
     * @memberof AdminReservationResponse
     */
    startTime: string;
    /**
     *
     * @type {string}
     * @memberof AdminReservationResponse
     */
    status: string;
    /**
     *
     * @type {string}
     * @memberof AdminReservationResponse
     */
    paymentSource: string;
    /**
     *
     * @type {AdminReservationCouponResponse}
     * @memberof AdminReservationResponse
     */
    coupon: AdminReservationCouponResponse | null;
    /**
     *
     * @type {Date}
     * @memberof AdminReservationResponse
     */
    paymentDueAt: Date | null;
    /**
     *
     * @type {Date}
     * @memberof AdminReservationResponse
     */
    approvalRequestedAt: Date;
    /**
     *
     * @type {Date}
     * @memberof AdminReservationResponse
     */
    adminConfirmedAt: Date | null;
    /**
     *
     * @type {Date}
     * @memberof AdminReservationResponse
     */
    rejectedAt: Date | null;
    /**
     *
     * @type {string}
     * @memberof AdminReservationResponse
     */
    rejectedBy: string | null;
    /**
     *
     * @type {string}
     * @memberof AdminReservationResponse
     */
    rejectionReason: string | null;
    /**
     *
     * @type {Date}
     * @memberof AdminReservationResponse
     */
    cancelledAt: Date | null;
    /**
     *
     * @type {string}
     * @memberof AdminReservationResponse
     */
    cancellationResponsibility: string | null;
    /**
     *
     * @type {string}
     * @memberof AdminReservationResponse
     */
    couponAction: string | null;
    /**
     *
     * @type {string}
     * @memberof AdminReservationResponse
     */
    adminMemo: string | null;
    /**
     *
     * @type {string}
     * @memberof AdminReservationResponse
     */
    approvalWarning: string | null;
    /**
     *
     * @type {Date}
     * @memberof AdminReservationResponse
     */
    createdAt: Date;
    /**
     *
     * @type {Date}
     * @memberof AdminReservationResponse
     */
    updatedAt: Date;
    /**
     *
     * @type {string}
     * @memberof AdminReservationResponse
     */
    displayGroup: string;
    /**
     *
     * @type {ReservationActionsResponse}
     * @memberof AdminReservationResponse
     */
    actions: ReservationActionsResponse;
}

/**
 * Check if a given object implements the AdminReservationResponse interface.
 */
export function instanceOfAdminReservationResponse(value: object): value is AdminReservationResponse {
    if (!('reservationId' in value) || value['reservationId'] === undefined) return false;
    if (!('memberId' in value) || value['memberId'] === undefined) return false;
    if (!('memberName' in value) || value['memberName'] === undefined) return false;
    if (!('memberPhone' in value) || value['memberPhone'] === undefined) return false;
    if (!('classType' in value) || value['classType'] === undefined) return false;
    if (!('lessonDate' in value) || value['lessonDate'] === undefined) return false;
    if (!('startTime' in value) || value['startTime'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('paymentSource' in value) || value['paymentSource'] === undefined) return false;
    if (!('coupon' in value) || value['coupon'] === undefined) return false;
    if (!('paymentDueAt' in value) || value['paymentDueAt'] === undefined) return false;
    if (!('approvalRequestedAt' in value) || value['approvalRequestedAt'] === undefined) return false;
    if (!('adminConfirmedAt' in value) || value['adminConfirmedAt'] === undefined) return false;
    if (!('rejectedAt' in value) || value['rejectedAt'] === undefined) return false;
    if (!('rejectedBy' in value) || value['rejectedBy'] === undefined) return false;
    if (!('rejectionReason' in value) || value['rejectionReason'] === undefined) return false;
    if (!('cancelledAt' in value) || value['cancelledAt'] === undefined) return false;
    if (!('cancellationResponsibility' in value) || value['cancellationResponsibility'] === undefined) return false;
    if (!('couponAction' in value) || value['couponAction'] === undefined) return false;
    if (!('adminMemo' in value) || value['adminMemo'] === undefined) return false;
    if (!('approvalWarning' in value) || value['approvalWarning'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    if (!('displayGroup' in value) || value['displayGroup'] === undefined) return false;
    if (!('actions' in value) || value['actions'] === undefined) return false;
    return true;
}

export function AdminReservationResponseFromJSON(json: any): AdminReservationResponse {
    return AdminReservationResponseFromJSONTyped(json, false);
}

export function AdminReservationResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdminReservationResponse {
    if (json == null) {
        return json;
    }
    return {

        'reservationId': json['reservationId'],
        'memberId': json['memberId'],
        'memberName': json['memberName'],
        'memberPhone': json['memberPhone'],
        'classType': json['classType'],
        'lessonDate': (new Date(json['lessonDate'])),
        'startTime': json['startTime'],
        'status': json['status'],
        'paymentSource': json['paymentSource'],
        'coupon': AdminReservationCouponResponseFromJSON(json['coupon']),
        'paymentDueAt': (json['paymentDueAt'] == null ? null : new Date(json['paymentDueAt'])),
        'approvalRequestedAt': (new Date(json['approvalRequestedAt'])),
        'adminConfirmedAt': (json['adminConfirmedAt'] == null ? null : new Date(json['adminConfirmedAt'])),
        'rejectedAt': (json['rejectedAt'] == null ? null : new Date(json['rejectedAt'])),
        'rejectedBy': json['rejectedBy'],
        'rejectionReason': json['rejectionReason'],
        'cancelledAt': (json['cancelledAt'] == null ? null : new Date(json['cancelledAt'])),
        'cancellationResponsibility': json['cancellationResponsibility'],
        'couponAction': json['couponAction'],
        'adminMemo': json['adminMemo'],
        'approvalWarning': json['approvalWarning'],
        'createdAt': (new Date(json['createdAt'])),
        'updatedAt': (new Date(json['updatedAt'])),
        'displayGroup': json['displayGroup'],
        'actions': ReservationActionsResponseFromJSON(json['actions']),
    };
}

export function AdminReservationResponseToJSON(json: any): AdminReservationResponse {
    return AdminReservationResponseToJSONTyped(json, false);
}

export function AdminReservationResponseToJSONTyped(value?: AdminReservationResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'reservationId': value['reservationId'],
        'memberId': value['memberId'],
        'memberName': value['memberName'],
        'memberPhone': value['memberPhone'],
        'classType': value['classType'],
        'lessonDate': value['lessonDate'].toISOString().substring(0,10),
        'startTime': value['startTime'],
        'status': value['status'],
        'paymentSource': value['paymentSource'],
        'coupon': AdminReservationCouponResponseToJSON(value['coupon']),
        'paymentDueAt': value['paymentDueAt'] == null ? value['paymentDueAt'] : value['paymentDueAt'].toISOString(),
        'approvalRequestedAt': value['approvalRequestedAt'].toISOString(),
        'adminConfirmedAt': value['adminConfirmedAt'] == null ? value['adminConfirmedAt'] : value['adminConfirmedAt'].toISOString(),
        'rejectedAt': value['rejectedAt'] == null ? value['rejectedAt'] : value['rejectedAt'].toISOString(),
        'rejectedBy': value['rejectedBy'],
        'rejectionReason': value['rejectionReason'],
        'cancelledAt': value['cancelledAt'] == null ? value['cancelledAt'] : value['cancelledAt'].toISOString(),
        'cancellationResponsibility': value['cancellationResponsibility'],
        'couponAction': value['couponAction'],
        'adminMemo': value['adminMemo'],
        'approvalWarning': value['approvalWarning'],
        'createdAt': value['createdAt'].toISOString(),
        'updatedAt': value['updatedAt'].toISOString(),
        'displayGroup': value['displayGroup'],
        'actions': ReservationActionsResponseToJSON(value['actions']),
    };
}

