/* tslint:disable */
/* eslint-disable */
/**
 * Horse Reservation API
 * 마장 예약 서비스 API
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AdminWeeklyOperationsReservationResponse } from './AdminWeeklyOperationsReservationResponse';
import {
    AdminWeeklyOperationsReservationResponseFromJSON,
    AdminWeeklyOperationsReservationResponseFromJSONTyped,
    AdminWeeklyOperationsReservationResponseToJSON,
    AdminWeeklyOperationsReservationResponseToJSONTyped,
} from './AdminWeeklyOperationsReservationResponse';

/**
 *
 * @export
 * @interface AdminWeeklyOperationsTimeSlotResponse
 */
export interface AdminWeeklyOperationsTimeSlotResponse {
    /**
     *
     * @type {number}
     * @memberof AdminWeeklyOperationsTimeSlotResponse
     */
    timeSlotId: number;
    /**
     *
     * @type {Date}
     * @memberof AdminWeeklyOperationsTimeSlotResponse
     */
    lessonDate: Date;
    /**
     *
     * @type {string}
     * @memberof AdminWeeklyOperationsTimeSlotResponse
     */
    startTime: string;
    /**
     *
     * @type {string}
     * @memberof AdminWeeklyOperationsTimeSlotResponse
     */
    endTime: string;
    /**
     *
     * @type {number}
     * @memberof AdminWeeklyOperationsTimeSlotResponse
     */
    totalCapacity: number;
    /**
     *
     * @type {number}
     * @memberof AdminWeeklyOperationsTimeSlotResponse
     */
    roundArenaCapacity: number;
    /**
     *
     * @type {{ [key: string]: number; }}
     * @memberof AdminWeeklyOperationsTimeSlotResponse
     */
    classCapacities: { [key: string]: number; };
    /**
     *
     * @type {boolean}
     * @memberof AdminWeeklyOperationsTimeSlotResponse
     */
    closed: boolean;
    /**
     *
     * @type {Array<AdminWeeklyOperationsReservationResponse>}
     * @memberof AdminWeeklyOperationsTimeSlotResponse
     */
    reservations: Array<AdminWeeklyOperationsReservationResponse>;
}

/**
 * Check if a given object implements the AdminWeeklyOperationsTimeSlotResponse interface.
 */
export function instanceOfAdminWeeklyOperationsTimeSlotResponse(value: object): value is AdminWeeklyOperationsTimeSlotResponse {
    if (!('timeSlotId' in value) || value['timeSlotId'] === undefined) return false;
    if (!('lessonDate' in value) || value['lessonDate'] === undefined) return false;
    if (!('startTime' in value) || value['startTime'] === undefined) return false;
    if (!('endTime' in value) || value['endTime'] === undefined) return false;
    if (!('totalCapacity' in value) || value['totalCapacity'] === undefined) return false;
    if (!('roundArenaCapacity' in value) || value['roundArenaCapacity'] === undefined) return false;
    if (!('classCapacities' in value) || value['classCapacities'] === undefined) return false;
    if (!('closed' in value) || value['closed'] === undefined) return false;
    if (!('reservations' in value) || value['reservations'] === undefined) return false;
    return true;
}

export function AdminWeeklyOperationsTimeSlotResponseFromJSON(json: any): AdminWeeklyOperationsTimeSlotResponse {
    return AdminWeeklyOperationsTimeSlotResponseFromJSONTyped(json, false);
}

export function AdminWeeklyOperationsTimeSlotResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdminWeeklyOperationsTimeSlotResponse {
    if (json == null) {
        return json;
    }
    return {

        'timeSlotId': json['timeSlotId'],
        'lessonDate': (new Date(json['lessonDate'])),
        'startTime': json['startTime'],
        'endTime': json['endTime'],
        'totalCapacity': json['totalCapacity'],
        'roundArenaCapacity': json['roundArenaCapacity'],
        'classCapacities': json['classCapacities'],
        'closed': json['closed'],
        'reservations': ((json['reservations'] as Array<any>).map(AdminWeeklyOperationsReservationResponseFromJSON)),
    };
}

export function AdminWeeklyOperationsTimeSlotResponseToJSON(json: any): AdminWeeklyOperationsTimeSlotResponse {
    return AdminWeeklyOperationsTimeSlotResponseToJSONTyped(json, false);
}

export function AdminWeeklyOperationsTimeSlotResponseToJSONTyped(value?: AdminWeeklyOperationsTimeSlotResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'timeSlotId': value['timeSlotId'],
        'lessonDate': value['lessonDate'].toISOString().substring(0,10),
        'startTime': value['startTime'],
        'endTime': value['endTime'],
        'totalCapacity': value['totalCapacity'],
        'roundArenaCapacity': value['roundArenaCapacity'],
        'classCapacities': value['classCapacities'],
        'closed': value['closed'],
        'reservations': ((value['reservations'] as Array<any>).map(AdminWeeklyOperationsReservationResponseToJSON)),
    };
}
