/* tslint:disable */
/* eslint-disable */
/**
 * Horse Reservation API
 * 마장 예약 서비스 API
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AdminReservationResponse } from './AdminReservationResponse';
import {
    AdminReservationResponseFromJSON,
    AdminReservationResponseFromJSONTyped,
    AdminReservationResponseToJSON,
    AdminReservationResponseToJSONTyped,
} from './AdminReservationResponse';

/**
 *
 * @export
 * @interface AdminReservationPageResponse
 */
export interface AdminReservationPageResponse {
    /**
     *
     * @type {Array<AdminReservationResponse>}
     * @memberof AdminReservationPageResponse
     */
    content: Array<AdminReservationResponse>;
    /**
     *
     * @type {number}
     * @memberof AdminReservationPageResponse
     */
    page: number;
    /**
     *
     * @type {number}
     * @memberof AdminReservationPageResponse
     */
    size: number;
    /**
     *
     * @type {number}
     * @memberof AdminReservationPageResponse
     */
    totalElements: number;
    /**
     *
     * @type {number}
     * @memberof AdminReservationPageResponse
     */
    totalPages: number;
    /**
     *
     * @type {boolean}
     * @memberof AdminReservationPageResponse
     */
    hasNext: boolean;
}

/**
 * Check if a given object implements the AdminReservationPageResponse interface.
 */
export function instanceOfAdminReservationPageResponse(value: object): value is AdminReservationPageResponse {
    if (!('content' in value) || value['content'] === undefined) return false;
    if (!('page' in value) || value['page'] === undefined) return false;
    if (!('size' in value) || value['size'] === undefined) return false;
    if (!('totalElements' in value) || value['totalElements'] === undefined) return false;
    if (!('totalPages' in value) || value['totalPages'] === undefined) return false;
    if (!('hasNext' in value) || value['hasNext'] === undefined) return false;
    return true;
}

export function AdminReservationPageResponseFromJSON(json: any): AdminReservationPageResponse {
    return AdminReservationPageResponseFromJSONTyped(json, false);
}

export function AdminReservationPageResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdminReservationPageResponse {
    if (json == null) {
        return json;
    }
    return {

        'content': ((json['content'] as Array<any>).map(AdminReservationResponseFromJSON)),
        'page': json['page'],
        'size': json['size'],
        'totalElements': json['totalElements'],
        'totalPages': json['totalPages'],
        'hasNext': json['hasNext'],
    };
}

export function AdminReservationPageResponseToJSON(json: any): AdminReservationPageResponse {
    return AdminReservationPageResponseToJSONTyped(json, false);
}

export function AdminReservationPageResponseToJSONTyped(value?: AdminReservationPageResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'content': ((value['content'] as Array<any>).map(AdminReservationResponseToJSON)),
        'page': value['page'],
        'size': value['size'],
        'totalElements': value['totalElements'],
        'totalPages': value['totalPages'],
        'hasNext': value['hasNext'],
    };
}

