/* tslint:disable */
/* eslint-disable */
/**
 * Horse Reservation API
 * 마장 예약 서비스 API
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AdminMemberResponse } from './AdminMemberResponse';
import {
    AdminMemberResponseFromJSON,
    AdminMemberResponseFromJSONTyped,
    AdminMemberResponseToJSON,
    AdminMemberResponseToJSONTyped,
} from './AdminMemberResponse';

/**
 *
 * @export
 * @interface AdminMemberPageResponse
 */
export interface AdminMemberPageResponse {
    /**
     *
     * @type {Array<AdminMemberResponse>}
     * @memberof AdminMemberPageResponse
     */
    content: Array<AdminMemberResponse>;
    /**
     *
     * @type {number}
     * @memberof AdminMemberPageResponse
     */
    page: number;
    /**
     *
     * @type {number}
     * @memberof AdminMemberPageResponse
     */
    size: number;
    /**
     *
     * @type {number}
     * @memberof AdminMemberPageResponse
     */
    totalElements: number;
    /**
     *
     * @type {number}
     * @memberof AdminMemberPageResponse
     */
    totalPages: number;
    /**
     *
     * @type {boolean}
     * @memberof AdminMemberPageResponse
     */
    hasNext: boolean;
}

/**
 * Check if a given object implements the AdminMemberPageResponse interface.
 */
export function instanceOfAdminMemberPageResponse(value: object): value is AdminMemberPageResponse {
    if (!('content' in value) || value['content'] === undefined) return false;
    if (!('page' in value) || value['page'] === undefined) return false;
    if (!('size' in value) || value['size'] === undefined) return false;
    if (!('totalElements' in value) || value['totalElements'] === undefined) return false;
    if (!('totalPages' in value) || value['totalPages'] === undefined) return false;
    if (!('hasNext' in value) || value['hasNext'] === undefined) return false;
    return true;
}

export function AdminMemberPageResponseFromJSON(json: any): AdminMemberPageResponse {
    return AdminMemberPageResponseFromJSONTyped(json, false);
}

export function AdminMemberPageResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdminMemberPageResponse {
    if (json == null) {
        return json;
    }
    return {

        'content': ((json['content'] as Array<any>).map(AdminMemberResponseFromJSON)),
        'page': json['page'],
        'size': json['size'],
        'totalElements': json['totalElements'],
        'totalPages': json['totalPages'],
        'hasNext': json['hasNext'],
    };
}

export function AdminMemberPageResponseToJSON(json: any): AdminMemberPageResponse {
    return AdminMemberPageResponseToJSONTyped(json, false);
}

export function AdminMemberPageResponseToJSONTyped(value?: AdminMemberPageResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'content': ((value['content'] as Array<any>).map(AdminMemberResponseToJSON)),
        'page': value['page'],
        'size': value['size'],
        'totalElements': value['totalElements'],
        'totalPages': value['totalPages'],
        'hasNext': value['hasNext'],
    };
}
