/* tslint:disable */
/* eslint-disable */
/**
 * Horse Reservation API
 * 마장 예약 서비스 API
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface AuthLogoutResponse
 */
export interface AuthLogoutResponse {
    /**
     *
     * @type {boolean}
     * @memberof AuthLogoutResponse
     */
    loggedOut: boolean;
}

/**
 * Check if a given object implements the AuthLogoutResponse interface.
 */
export function instanceOfAuthLogoutResponse(value: object): value is AuthLogoutResponse {
    if (!('loggedOut' in value) || value['loggedOut'] === undefined) return false;
    return true;
}

export function AuthLogoutResponseFromJSON(json: any): AuthLogoutResponse {
    return AuthLogoutResponseFromJSONTyped(json, false);
}

export function AuthLogoutResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthLogoutResponse {
    if (json == null) {
        return json;
    }
    return {

        'loggedOut': json['loggedOut'],
    };
}

export function AuthLogoutResponseToJSON(json: any): AuthLogoutResponse {
    return AuthLogoutResponseToJSONTyped(json, false);
}

export function AuthLogoutResponseToJSONTyped(value?: AuthLogoutResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'loggedOut': value['loggedOut'],
    };
}
