/* tslint:disable */
/* eslint-disable */
/**
 * Horse Reservation API
 * 마장 예약 서비스 API
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface AuthLogoutRequest
 */
export interface AuthLogoutRequest {
    /**
     *
     * @type {string}
     * @memberof AuthLogoutRequest
     */
    refreshToken: string;
}

/**
 * Check if a given object implements the AuthLogoutRequest interface.
 */
export function instanceOfAuthLogoutRequest(value: object): value is AuthLogoutRequest {
    if (!('refreshToken' in value) || value['refreshToken'] === undefined) return false;
    return true;
}

export function AuthLogoutRequestFromJSON(json: any): AuthLogoutRequest {
    return AuthLogoutRequestFromJSONTyped(json, false);
}

export function AuthLogoutRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthLogoutRequest {
    if (json == null) {
        return json;
    }
    return {

        'refreshToken': json['refreshToken'],
    };
}

export function AuthLogoutRequestToJSON(json: any): AuthLogoutRequest {
    return AuthLogoutRequestToJSONTyped(json, false);
}

export function AuthLogoutRequestToJSONTyped(value?: AuthLogoutRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'refreshToken': value['refreshToken'],
    };
}
