/* tslint:disable */
/* eslint-disable */
/**
 * Horse Reservation API
 * 마장 예약 서비스 API
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BulkReservationAttendanceItemResponse } from './BulkReservationAttendanceItemResponse';
import {
    BulkReservationAttendanceItemResponseFromJSON,
    BulkReservationAttendanceItemResponseFromJSONTyped,
    BulkReservationAttendanceItemResponseToJSON,
    BulkReservationAttendanceItemResponseToJSONTyped,
} from './BulkReservationAttendanceItemResponse';

/**
 *
 * @export
 * @interface BulkReservationAttendanceResponse
 */
export interface BulkReservationAttendanceResponse {
    /**
     *
     * @type {number}
     * @memberof BulkReservationAttendanceResponse
     */
    requestedCount?: number;
    /**
     *
     * @type {number}
     * @memberof BulkReservationAttendanceResponse
     */
    succeededCount?: number;
    /**
     *
     * @type {number}
     * @memberof BulkReservationAttendanceResponse
     */
    failedCount?: number;
    /**
     *
     * @type {Array<BulkReservationAttendanceItemResponse>}
     * @memberof BulkReservationAttendanceResponse
     */
    items?: Array<BulkReservationAttendanceItemResponse>;
}

/**
 * Check if a given object implements the BulkReservationAttendanceResponse interface.
 */
export function instanceOfBulkReservationAttendanceResponse(value: object): value is BulkReservationAttendanceResponse {
    return true;
}

export function BulkReservationAttendanceResponseFromJSON(json: any): BulkReservationAttendanceResponse {
    return BulkReservationAttendanceResponseFromJSONTyped(json, false);
}

export function BulkReservationAttendanceResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): BulkReservationAttendanceResponse {
    if (json == null) {
        return json;
    }
    return {

        'requestedCount': json['requestedCount'] == null ? undefined : json['requestedCount'],
        'succeededCount': json['succeededCount'] == null ? undefined : json['succeededCount'],
        'failedCount': json['failedCount'] == null ? undefined : json['failedCount'],
        'items': json['items'] == null ? undefined : ((json['items'] as Array<any>).map(BulkReservationAttendanceItemResponseFromJSON)),
    };
}

export function BulkReservationAttendanceResponseToJSON(json: any): BulkReservationAttendanceResponse {
    return BulkReservationAttendanceResponseToJSONTyped(json, false);
}

export function BulkReservationAttendanceResponseToJSONTyped(value?: BulkReservationAttendanceResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'requestedCount': value['requestedCount'],
        'succeededCount': value['succeededCount'],
        'failedCount': value['failedCount'],
        'items': value['items'] == null ? undefined : ((value['items'] as Array<any>).map(BulkReservationAttendanceItemResponseToJSON)),
    };
}

