/* tslint:disable */
/* eslint-disable */
/**
 * Horse Reservation API
 * 마장 예약 서비스 API
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface CouponResponse
 */
export interface CouponResponse {
    /**
     *
     * @type {number}
     * @memberof CouponResponse
     */
    id: number;
    /**
     *
     * @type {number}
     * @memberof CouponResponse
     */
    memberId: number;
    /**
     *
     * @type {string}
     * @memberof CouponResponse
     */
    type: string;
    /**
     *
     * @type {number}
     * @memberof CouponResponse
     */
    totalCount: number;
    /**
     *
     * @type {number}
     * @memberof CouponResponse
     */
    remainingCount: number;
    /**
     *
     * @type {number}
     * @memberof CouponResponse
     */
    heldCount: number;
    /**
     *
     * @type {Date}
     * @memberof CouponResponse
     */
    firstUsedAt: Date | null;
    /**
     *
     * @type {Date}
     * @memberof CouponResponse
     */
    expiresAt: Date | null;
    /**
     *
     * @type {boolean}
     * @memberof CouponResponse
     */
    freeChangeUsed: boolean;
    /**
     *
     * @type {string}
     * @memberof CouponResponse
     */
    status: string;
    /**
     *
     * @type {string}
     * @memberof CouponResponse
     */
    createdBy: string;
    /**
     *
     * @type {Date}
     * @memberof CouponResponse
     */
    createdAt: Date;
}

/**
 * Check if a given object implements the CouponResponse interface.
 */
export function instanceOfCouponResponse(value: object): value is CouponResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('memberId' in value) || value['memberId'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('totalCount' in value) || value['totalCount'] === undefined) return false;
    if (!('remainingCount' in value) || value['remainingCount'] === undefined) return false;
    if (!('heldCount' in value) || value['heldCount'] === undefined) return false;
    if (!('firstUsedAt' in value) || value['firstUsedAt'] === undefined) return false;
    if (!('expiresAt' in value) || value['expiresAt'] === undefined) return false;
    if (!('freeChangeUsed' in value) || value['freeChangeUsed'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('createdBy' in value) || value['createdBy'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    return true;
}

export function CouponResponseFromJSON(json: any): CouponResponse {
    return CouponResponseFromJSONTyped(json, false);
}

export function CouponResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CouponResponse {
    if (json == null) {
        return json;
    }
    return {

        'id': json['id'],
        'memberId': json['memberId'],
        'type': json['type'],
        'totalCount': json['totalCount'],
        'remainingCount': json['remainingCount'],
        'heldCount': json['heldCount'],
        'firstUsedAt': (json['firstUsedAt'] == null ? null : new Date(json['firstUsedAt'])),
        'expiresAt': (json['expiresAt'] == null ? null : new Date(json['expiresAt'])),
        'freeChangeUsed': json['freeChangeUsed'],
        'status': json['status'],
        'createdBy': json['createdBy'],
        'createdAt': (new Date(json['createdAt'])),
    };
}

export function CouponResponseToJSON(json: any): CouponResponse {
    return CouponResponseToJSONTyped(json, false);
}

export function CouponResponseToJSONTyped(value?: CouponResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'id': value['id'],
        'memberId': value['memberId'],
        'type': value['type'],
        'totalCount': value['totalCount'],
        'remainingCount': value['remainingCount'],
        'heldCount': value['heldCount'],
        'firstUsedAt': value['firstUsedAt'] == null ? value['firstUsedAt'] : value['firstUsedAt'].toISOString(),
        'expiresAt': value['expiresAt'] == null ? value['expiresAt'] : value['expiresAt'].toISOString(),
        'freeChangeUsed': value['freeChangeUsed'],
        'status': value['status'],
        'createdBy': value['createdBy'],
        'createdAt': value['createdAt'].toISOString(),
    };
}

