/* tslint:disable */
/* eslint-disable */
/**
 * Horse Reservation API
 * 마장 예약 서비스 API
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface FamilyMembershipResponse
 */
export interface FamilyMembershipResponse {
    /**
     *
     * @type {number}
     * @memberof FamilyMembershipResponse
     */
    membershipId: number;
    /**
     *
     * @type {number}
     * @memberof FamilyMembershipResponse
     */
    groupId: number;
    /**
     *
     * @type {number}
     * @memberof FamilyMembershipResponse
     */
    memberId: number;
    /**
     *
     * @type {Date}
     * @memberof FamilyMembershipResponse
     */
    joinedAt: Date;
    /**
     *
     * @type {Date}
     * @memberof FamilyMembershipResponse
     */
    endedAt: Date | null;
}

/**
 * Check if a given object implements the FamilyMembershipResponse interface.
 */
export function instanceOfFamilyMembershipResponse(value: object): value is FamilyMembershipResponse {
    if (!('membershipId' in value) || value['membershipId'] === undefined) return false;
    if (!('groupId' in value) || value['groupId'] === undefined) return false;
    if (!('memberId' in value) || value['memberId'] === undefined) return false;
    if (!('joinedAt' in value) || value['joinedAt'] === undefined) return false;
    if (!('endedAt' in value) || value['endedAt'] === undefined) return false;
    return true;
}

export function FamilyMembershipResponseFromJSON(json: any): FamilyMembershipResponse {
    return FamilyMembershipResponseFromJSONTyped(json, false);
}

export function FamilyMembershipResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): FamilyMembershipResponse {
    if (json == null) {
        return json;
    }
    return {

        'membershipId': json['membershipId'],
        'groupId': json['groupId'],
        'memberId': json['memberId'],
        'joinedAt': (new Date(json['joinedAt'])),
        'endedAt': (json['endedAt'] == null ? null : new Date(json['endedAt'])),
    };
}

export function FamilyMembershipResponseToJSON(json: any): FamilyMembershipResponse {
    return FamilyMembershipResponseToJSONTyped(json, false);
}

export function FamilyMembershipResponseToJSONTyped(value?: FamilyMembershipResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'membershipId': value['membershipId'],
        'groupId': value['groupId'],
        'memberId': value['memberId'],
        'joinedAt': value['joinedAt'].toISOString(),
        'endedAt': value['endedAt'] == null ? value['endedAt'] : value['endedAt'].toISOString(),
    };
}
