/* tslint:disable */
/* eslint-disable */
/**
 * Horse Reservation API
 * 마장 예약 서비스 API
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FamilyMemberCandidateResponse } from './FamilyMemberCandidateResponse';
import {
    FamilyMemberCandidateResponseFromJSON,
    FamilyMemberCandidateResponseFromJSONTyped,
    FamilyMemberCandidateResponseToJSON,
    FamilyMemberCandidateResponseToJSONTyped,
} from './FamilyMemberCandidateResponse';

/**
 *
 * @export
 * @interface FamilyMemberCandidatePageResponse
 */
export interface FamilyMemberCandidatePageResponse {
    /**
     *
     * @type {Array<FamilyMemberCandidateResponse>}
     * @memberof FamilyMemberCandidatePageResponse
     */
    content: Array<FamilyMemberCandidateResponse>;
    /**
     *
     * @type {number}
     * @memberof FamilyMemberCandidatePageResponse
     */
    page: number;
    /**
     *
     * @type {number}
     * @memberof FamilyMemberCandidatePageResponse
     */
    size: number;
    /**
     *
     * @type {number}
     * @memberof FamilyMemberCandidatePageResponse
     */
    totalElements: number;
    /**
     *
     * @type {number}
     * @memberof FamilyMemberCandidatePageResponse
     */
    totalPages: number;
    /**
     *
     * @type {boolean}
     * @memberof FamilyMemberCandidatePageResponse
     */
    hasNext: boolean;
}

/**
 * Check if a given object implements the FamilyMemberCandidatePageResponse interface.
 */
export function instanceOfFamilyMemberCandidatePageResponse(value: object): value is FamilyMemberCandidatePageResponse {
    if (!('content' in value) || value['content'] === undefined) return false;
    if (!('page' in value) || value['page'] === undefined) return false;
    if (!('size' in value) || value['size'] === undefined) return false;
    if (!('totalElements' in value) || value['totalElements'] === undefined) return false;
    if (!('totalPages' in value) || value['totalPages'] === undefined) return false;
    if (!('hasNext' in value) || value['hasNext'] === undefined) return false;
    return true;
}

export function FamilyMemberCandidatePageResponseFromJSON(json: any): FamilyMemberCandidatePageResponse {
    return FamilyMemberCandidatePageResponseFromJSONTyped(json, false);
}

export function FamilyMemberCandidatePageResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): FamilyMemberCandidatePageResponse {
    if (json == null) {
        return json;
    }
    return {

        'content': ((json['content'] as Array<any>).map(FamilyMemberCandidateResponseFromJSON)),
        'page': json['page'],
        'size': json['size'],
        'totalElements': json['totalElements'],
        'totalPages': json['totalPages'],
        'hasNext': json['hasNext'],
    };
}

export function FamilyMemberCandidatePageResponseToJSON(json: any): FamilyMemberCandidatePageResponse {
    return FamilyMemberCandidatePageResponseToJSONTyped(json, false);
}

export function FamilyMemberCandidatePageResponseToJSONTyped(value?: FamilyMemberCandidatePageResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'content': ((value['content'] as Array<any>).map(FamilyMemberCandidateResponseToJSON)),
        'page': value['page'],
        'size': value['size'],
        'totalElements': value['totalElements'],
        'totalPages': value['totalPages'],
        'hasNext': value['hasNext'],
    };
}
