/* tslint:disable */
/* eslint-disable */
/**
 * Horse Reservation API
 * 마장 예약 서비스 API
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface FamilyGroupMemberResponse
 */
export interface FamilyGroupMemberResponse {
    /**
     *
     * @type {number}
     * @memberof FamilyGroupMemberResponse
     */
    membershipId: number;
    /**
     *
     * @type {number}
     * @memberof FamilyGroupMemberResponse
     */
    memberId: number;
    /**
     *
     * @type {string}
     * @memberof FamilyGroupMemberResponse
     */
    name: string;
    /**
     *
     * @type {string}
     * @memberof FamilyGroupMemberResponse
     */
    phone: string;
    /**
     *
     * @type {Date}
     * @memberof FamilyGroupMemberResponse
     */
    joinedAt: Date;
}

/**
 * Check if a given object implements the FamilyGroupMemberResponse interface.
 */
export function instanceOfFamilyGroupMemberResponse(value: object): value is FamilyGroupMemberResponse {
    if (!('membershipId' in value) || value['membershipId'] === undefined) return false;
    if (!('memberId' in value) || value['memberId'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('phone' in value) || value['phone'] === undefined) return false;
    if (!('joinedAt' in value) || value['joinedAt'] === undefined) return false;
    return true;
}

export function FamilyGroupMemberResponseFromJSON(json: any): FamilyGroupMemberResponse {
    return FamilyGroupMemberResponseFromJSONTyped(json, false);
}

export function FamilyGroupMemberResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): FamilyGroupMemberResponse {
    if (json == null) {
        return json;
    }
    return {

        'membershipId': json['membershipId'],
        'memberId': json['memberId'],
        'name': json['name'],
        'phone': json['phone'],
        'joinedAt': (new Date(json['joinedAt'])),
    };
}

export function FamilyGroupMemberResponseToJSON(json: any): FamilyGroupMemberResponse {
    return FamilyGroupMemberResponseToJSONTyped(json, false);
}

export function FamilyGroupMemberResponseToJSONTyped(value?: FamilyGroupMemberResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'membershipId': value['membershipId'],
        'memberId': value['memberId'],
        'name': value['name'],
        'phone': value['phone'],
        'joinedAt': value['joinedAt'].toISOString(),
    };
}
