/* tslint:disable */
/* eslint-disable */
/**
 * Horse Reservation API
 * 마장 예약 서비스 API
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FamilyGroupMemberResponse } from './FamilyGroupMemberResponse';
import {
    FamilyGroupMemberResponseFromJSON,
    FamilyGroupMemberResponseFromJSONTyped,
    FamilyGroupMemberResponseToJSON,
    FamilyGroupMemberResponseToJSONTyped,
} from './FamilyGroupMemberResponse';

/**
 *
 * @export
 * @interface FamilyGroupMemberPageResponse
 */
export interface FamilyGroupMemberPageResponse {
    /**
     *
     * @type {Array<FamilyGroupMemberResponse>}
     * @memberof FamilyGroupMemberPageResponse
     */
    content: Array<FamilyGroupMemberResponse>;
    /**
     *
     * @type {number}
     * @memberof FamilyGroupMemberPageResponse
     */
    page: number;
    /**
     *
     * @type {number}
     * @memberof FamilyGroupMemberPageResponse
     */
    size: number;
    /**
     *
     * @type {number}
     * @memberof FamilyGroupMemberPageResponse
     */
    totalElements: number;
    /**
     *
     * @type {number}
     * @memberof FamilyGroupMemberPageResponse
     */
    totalPages: number;
    /**
     *
     * @type {boolean}
     * @memberof FamilyGroupMemberPageResponse
     */
    hasNext: boolean;
}

/**
 * Check if a given object implements the FamilyGroupMemberPageResponse interface.
 */
export function instanceOfFamilyGroupMemberPageResponse(value: object): value is FamilyGroupMemberPageResponse {
    if (!('content' in value) || value['content'] === undefined) return false;
    if (!('page' in value) || value['page'] === undefined) return false;
    if (!('size' in value) || value['size'] === undefined) return false;
    if (!('totalElements' in value) || value['totalElements'] === undefined) return false;
    if (!('totalPages' in value) || value['totalPages'] === undefined) return false;
    if (!('hasNext' in value) || value['hasNext'] === undefined) return false;
    return true;
}

export function FamilyGroupMemberPageResponseFromJSON(json: any): FamilyGroupMemberPageResponse {
    return FamilyGroupMemberPageResponseFromJSONTyped(json, false);
}

export function FamilyGroupMemberPageResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): FamilyGroupMemberPageResponse {
    if (json == null) {
        return json;
    }
    return {

        'content': ((json['content'] as Array<any>).map(FamilyGroupMemberResponseFromJSON)),
        'page': json['page'],
        'size': json['size'],
        'totalElements': json['totalElements'],
        'totalPages': json['totalPages'],
        'hasNext': json['hasNext'],
    };
}

export function FamilyGroupMemberPageResponseToJSON(json: any): FamilyGroupMemberPageResponse {
    return FamilyGroupMemberPageResponseToJSONTyped(json, false);
}

export function FamilyGroupMemberPageResponseToJSONTyped(value?: FamilyGroupMemberPageResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'content': ((value['content'] as Array<any>).map(FamilyGroupMemberResponseToJSON)),
        'page': value['page'],
        'size': value['size'],
        'totalElements': value['totalElements'],
        'totalPages': value['totalPages'],
        'hasNext': value['hasNext'],
    };
}
