/* tslint:disable */
/* eslint-disable */
/**
 * Horse Reservation API
 * 마장 예약 서비스 API
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface FamilyGroupSummaryResponse
 */
export interface FamilyGroupSummaryResponse {
    /**
     *
     * @type {number}
     * @memberof FamilyGroupSummaryResponse
     */
    groupId: number;
    /**
     *
     * @type {string}
     * @memberof FamilyGroupSummaryResponse
     */
    name: string;
    /**
     *
     * @type {FamilyGroupSummaryResponseStatusEnum}
     * @memberof FamilyGroupSummaryResponse
     */
    status: FamilyGroupSummaryResponseStatusEnum;
    /**
     *
     * @type {number}
     * @memberof FamilyGroupSummaryResponse
     */
    activeMemberCount: number;
    /**
     *
     * @type {Date}
     * @memberof FamilyGroupSummaryResponse
     */
    createdAt: Date;
    /**
     *
     * @type {Date}
     * @memberof FamilyGroupSummaryResponse
     */
    dissolvedAt: Date | null;
}


/**
 * @export
 */
export const FamilyGroupSummaryResponseStatusEnum = {
    Active: 'ACTIVE',
    Dissolved: 'DISSOLVED'
} as const;
export type FamilyGroupSummaryResponseStatusEnum = typeof FamilyGroupSummaryResponseStatusEnum[keyof typeof FamilyGroupSummaryResponseStatusEnum];


/**
 * Check if a given object implements the FamilyGroupSummaryResponse interface.
 */
export function instanceOfFamilyGroupSummaryResponse(value: object): value is FamilyGroupSummaryResponse {
    if (!('groupId' in value) || value['groupId'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('activeMemberCount' in value) || value['activeMemberCount'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('dissolvedAt' in value) || value['dissolvedAt'] === undefined) return false;
    return true;
}

export function FamilyGroupSummaryResponseFromJSON(json: any): FamilyGroupSummaryResponse {
    return FamilyGroupSummaryResponseFromJSONTyped(json, false);
}

export function FamilyGroupSummaryResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): FamilyGroupSummaryResponse {
    if (json == null) {
        return json;
    }
    return {

        'groupId': json['groupId'],
        'name': json['name'],
        'status': json['status'],
        'activeMemberCount': json['activeMemberCount'],
        'createdAt': (new Date(json['createdAt'])),
        'dissolvedAt': (json['dissolvedAt'] == null ? null : new Date(json['dissolvedAt'])),
    };
}

export function FamilyGroupSummaryResponseToJSON(json: any): FamilyGroupSummaryResponse {
    return FamilyGroupSummaryResponseToJSONTyped(json, false);
}

export function FamilyGroupSummaryResponseToJSONTyped(value?: FamilyGroupSummaryResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'groupId': value['groupId'],
        'name': value['name'],
        'status': value['status'],
        'activeMemberCount': value['activeMemberCount'],
        'createdAt': value['createdAt'].toISOString(),
        'dissolvedAt': value['dissolvedAt'] == null ? value['dissolvedAt'] : value['dissolvedAt'].toISOString(),
    };
}
