/* tslint:disable */
/* eslint-disable */
/**
 * Horse Reservation API
 * 마장 예약 서비스 API
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FamilyGroupSummaryResponse } from './FamilyGroupSummaryResponse';
import {
    FamilyGroupSummaryResponseFromJSON,
    FamilyGroupSummaryResponseFromJSONTyped,
    FamilyGroupSummaryResponseToJSON,
    FamilyGroupSummaryResponseToJSONTyped,
} from './FamilyGroupSummaryResponse';

/**
 *
 * @export
 * @interface FamilyGroupPageResponse
 */
export interface FamilyGroupPageResponse {
    /**
     *
     * @type {Array<FamilyGroupSummaryResponse>}
     * @memberof FamilyGroupPageResponse
     */
    content: Array<FamilyGroupSummaryResponse>;
    /**
     *
     * @type {number}
     * @memberof FamilyGroupPageResponse
     */
    page: number;
    /**
     *
     * @type {number}
     * @memberof FamilyGroupPageResponse
     */
    size: number;
    /**
     *
     * @type {number}
     * @memberof FamilyGroupPageResponse
     */
    totalElements: number;
    /**
     *
     * @type {number}
     * @memberof FamilyGroupPageResponse
     */
    totalPages: number;
    /**
     *
     * @type {boolean}
     * @memberof FamilyGroupPageResponse
     */
    hasNext: boolean;
}

/**
 * Check if a given object implements the FamilyGroupPageResponse interface.
 */
export function instanceOfFamilyGroupPageResponse(value: object): value is FamilyGroupPageResponse {
    if (!('content' in value) || value['content'] === undefined) return false;
    if (!('page' in value) || value['page'] === undefined) return false;
    if (!('size' in value) || value['size'] === undefined) return false;
    if (!('totalElements' in value) || value['totalElements'] === undefined) return false;
    if (!('totalPages' in value) || value['totalPages'] === undefined) return false;
    if (!('hasNext' in value) || value['hasNext'] === undefined) return false;
    return true;
}

export function FamilyGroupPageResponseFromJSON(json: any): FamilyGroupPageResponse {
    return FamilyGroupPageResponseFromJSONTyped(json, false);
}

export function FamilyGroupPageResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): FamilyGroupPageResponse {
    if (json == null) {
        return json;
    }
    return {

        'content': ((json['content'] as Array<any>).map(FamilyGroupSummaryResponseFromJSON)),
        'page': json['page'],
        'size': json['size'],
        'totalElements': json['totalElements'],
        'totalPages': json['totalPages'],
        'hasNext': json['hasNext'],
    };
}

export function FamilyGroupPageResponseToJSON(json: any): FamilyGroupPageResponse {
    return FamilyGroupPageResponseToJSONTyped(json, false);
}

export function FamilyGroupPageResponseToJSONTyped(value?: FamilyGroupPageResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'content': ((value['content'] as Array<any>).map(FamilyGroupSummaryResponseToJSON)),
        'page': value['page'],
        'size': value['size'],
        'totalElements': value['totalElements'],
        'totalPages': value['totalPages'],
        'hasNext': value['hasNext'],
    };
}
