/* tslint:disable */
/* eslint-disable */
/**
 * Horse Reservation API
 * 마장 예약 서비스 API
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface FamilyGroupAuditStateResponse
 */
export interface FamilyGroupAuditStateResponse {
    /**
     *
     * @type {number}
     * @memberof FamilyGroupAuditStateResponse
     */
    groupId: number | null;
    /**
     *
     * @type {string}
     * @memberof FamilyGroupAuditStateResponse
     */
    name: string | null;
    /**
     *
     * @type {string}
     * @memberof FamilyGroupAuditStateResponse
     */
    status: string | null;
    /**
     *
     * @type {Array<number>}
     * @memberof FamilyGroupAuditStateResponse
     */
    activeMemberIds: Array<number> | null;
    /**
     *
     * @type {string}
     * @memberof FamilyGroupAuditStateResponse
     */
    dissolvedAt: string | null;
    /**
     *
     * @type {number}
     * @memberof FamilyGroupAuditStateResponse
     */
    membershipId: number | null;
    /**
     *
     * @type {number}
     * @memberof FamilyGroupAuditStateResponse
     */
    memberId: number | null;
    /**
     *
     * @type {string}
     * @memberof FamilyGroupAuditStateResponse
     */
    joinedAt: string | null;
    /**
     *
     * @type {string}
     * @memberof FamilyGroupAuditStateResponse
     */
    endedAt: string | null;
}

/**
 * Check if a given object implements the FamilyGroupAuditStateResponse interface.
 */
export function instanceOfFamilyGroupAuditStateResponse(value: object): value is FamilyGroupAuditStateResponse {
    if (!('groupId' in value) || value['groupId'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('activeMemberIds' in value) || value['activeMemberIds'] === undefined) return false;
    if (!('dissolvedAt' in value) || value['dissolvedAt'] === undefined) return false;
    if (!('membershipId' in value) || value['membershipId'] === undefined) return false;
    if (!('memberId' in value) || value['memberId'] === undefined) return false;
    if (!('joinedAt' in value) || value['joinedAt'] === undefined) return false;
    if (!('endedAt' in value) || value['endedAt'] === undefined) return false;
    return true;
}

export function FamilyGroupAuditStateResponseFromJSON(json: any): FamilyGroupAuditStateResponse {
    return FamilyGroupAuditStateResponseFromJSONTyped(json, false);
}

export function FamilyGroupAuditStateResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): FamilyGroupAuditStateResponse {
    if (json == null) {
        return json;
    }
    return {

        'groupId': json['groupId'],
        'name': json['name'],
        'status': json['status'],
        'activeMemberIds': json['activeMemberIds'] == null ? null : json['activeMemberIds'],
        'dissolvedAt': json['dissolvedAt'],
        'membershipId': json['membershipId'],
        'memberId': json['memberId'],
        'joinedAt': json['joinedAt'],
        'endedAt': json['endedAt'],
    };
}

export function FamilyGroupAuditStateResponseToJSON(json: any): FamilyGroupAuditStateResponse {
    return FamilyGroupAuditStateResponseToJSONTyped(json, false);
}

export function FamilyGroupAuditStateResponseToJSONTyped(value?: FamilyGroupAuditStateResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'groupId': value['groupId'],
        'name': value['name'],
        'status': value['status'],
        'activeMemberIds': value['activeMemberIds'],
        'dissolvedAt': value['dissolvedAt'],
        'membershipId': value['membershipId'],
        'memberId': value['memberId'],
        'joinedAt': value['joinedAt'],
        'endedAt': value['endedAt'],
    };
}
