/* tslint:disable */
/* eslint-disable */
/**
 * Horse Reservation API
 * 마장 예약 서비스 API
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface FamilyMemberAddRequest
 */
export interface FamilyMemberAddRequest {
    /**
     *
     * @type {number}
     * @memberof FamilyMemberAddRequest
     */
    memberId: number;
    /**
     *
     * @type {string}
     * @memberof FamilyMemberAddRequest
     */
    reason: string;
}

/**
 * Check if a given object implements the FamilyMemberAddRequest interface.
 */
export function instanceOfFamilyMemberAddRequest(value: object): value is FamilyMemberAddRequest {
    if (!('memberId' in value) || value['memberId'] === undefined) return false;
    if (!('reason' in value) || value['reason'] === undefined) return false;
    return true;
}

export function FamilyMemberAddRequestFromJSON(json: any): FamilyMemberAddRequest {
    return FamilyMemberAddRequestFromJSONTyped(json, false);
}

export function FamilyMemberAddRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): FamilyMemberAddRequest {
    if (json == null) {
        return json;
    }
    return {

        'memberId': json['memberId'],
        'reason': json['reason'],
    };
}

export function FamilyMemberAddRequestToJSON(json: any): FamilyMemberAddRequest {
    return FamilyMemberAddRequestToJSONTyped(json, false);
}

export function FamilyMemberAddRequestToJSONTyped(value?: FamilyMemberAddRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'memberId': value['memberId'],
        'reason': value['reason'],
    };
}
