/* tslint:disable */
/* eslint-disable */
/**
 * Horse Reservation API
 * 마장 예약 서비스 API
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface MemberProgressionCreditCorrectionRequest
 */
export interface MemberProgressionCreditCorrectionRequest {
    /**
     *
     * @type {number}
     * @memberof MemberProgressionCreditCorrectionRequest
     */
    specialApprovalProgressionCredit: number;
    /**
     *
     * @type {string}
     * @memberof MemberProgressionCreditCorrectionRequest
     */
    reason: string;
}

/**
 * Check if a given object implements the MemberProgressionCreditCorrectionRequest interface.
 */
export function instanceOfMemberProgressionCreditCorrectionRequest(value: object): value is MemberProgressionCreditCorrectionRequest {
    if (!('specialApprovalProgressionCredit' in value) || value['specialApprovalProgressionCredit'] === undefined) return false;
    if (!('reason' in value) || value['reason'] === undefined) return false;
    return true;
}

export function MemberProgressionCreditCorrectionRequestFromJSON(json: any): MemberProgressionCreditCorrectionRequest {
    return MemberProgressionCreditCorrectionRequestFromJSONTyped(json, false);
}

export function MemberProgressionCreditCorrectionRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): MemberProgressionCreditCorrectionRequest {
    if (json == null) {
        return json;
    }
    return {

        'specialApprovalProgressionCredit': json['specialApprovalProgressionCredit'],
        'reason': json['reason'],
    };
}

export function MemberProgressionCreditCorrectionRequestToJSON(json: any): MemberProgressionCreditCorrectionRequest {
    return MemberProgressionCreditCorrectionRequestToJSONTyped(json, false);
}

export function MemberProgressionCreditCorrectionRequestToJSONTyped(value?: MemberProgressionCreditCorrectionRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'specialApprovalProgressionCredit': value['specialApprovalProgressionCredit'],
        'reason': value['reason'],
    };
}
