/* tslint:disable */
/* eslint-disable */
/**
 * Horse Reservation API
 * 마장 예약 서비스 API
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface MemberAvailableRidingClassesResponse
 */
export interface MemberAvailableRidingClassesResponse {
    /**
     *
     * @type {MemberAvailableRidingClassesResponseCurrentGeneralGradeEnum}
     * @memberof MemberAvailableRidingClassesResponse
     */
    currentGeneralGrade?: MemberAvailableRidingClassesResponseCurrentGeneralGradeEnum;
    /**
     *
     * @type {boolean}
     * @memberof MemberAvailableRidingClassesResponse
     */
    dressageApproved?: boolean;
    /**
     *
     * @type {boolean}
     * @memberof MemberAvailableRidingClassesResponse
     */
    jumpingApproved?: boolean;
    /**
     *
     * @type {boolean}
     * @memberof MemberAvailableRidingClassesResponse
     */
    canUseLargeArena?: boolean;
    /**
     *
     * @type {Array<MemberAvailableRidingClassesResponseAvailableRidingClassesEnum>}
     * @memberof MemberAvailableRidingClassesResponse
     */
    availableRidingClasses?: Array<MemberAvailableRidingClassesResponseAvailableRidingClassesEnum>;
}


/**
 * @export
 */
export const MemberAvailableRidingClassesResponseCurrentGeneralGradeEnum = {
    FirstRide: 'FIRST_RIDE',
    RoundBeginner: 'ROUND_BEGINNER',
    RoundTrot: 'ROUND_TROT',
    LargeArenaBeginner: 'LARGE_ARENA_BEGINNER',
    LargeArenaTrot: 'LARGE_ARENA_TROT'
} as const;
export type MemberAvailableRidingClassesResponseCurrentGeneralGradeEnum = typeof MemberAvailableRidingClassesResponseCurrentGeneralGradeEnum[keyof typeof MemberAvailableRidingClassesResponseCurrentGeneralGradeEnum];

/**
 * @export
 */
export const MemberAvailableRidingClassesResponseAvailableRidingClassesEnum = {
    FirstRide: 'FIRST_RIDE',
    RoundBeginner: 'ROUND_BEGINNER',
    RoundTrot: 'ROUND_TROT',
    LargeArenaBeginner: 'LARGE_ARENA_BEGINNER',
    LargeArenaTrot: 'LARGE_ARENA_TROT',
    Dressage: 'DRESSAGE',
    Jumping: 'JUMPING'
} as const;
export type MemberAvailableRidingClassesResponseAvailableRidingClassesEnum = typeof MemberAvailableRidingClassesResponseAvailableRidingClassesEnum[keyof typeof MemberAvailableRidingClassesResponseAvailableRidingClassesEnum];


/**
 * Check if a given object implements the MemberAvailableRidingClassesResponse interface.
 */
export function instanceOfMemberAvailableRidingClassesResponse(value: object): value is MemberAvailableRidingClassesResponse {
    return true;
}

export function MemberAvailableRidingClassesResponseFromJSON(json: any): MemberAvailableRidingClassesResponse {
    return MemberAvailableRidingClassesResponseFromJSONTyped(json, false);
}

export function MemberAvailableRidingClassesResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): MemberAvailableRidingClassesResponse {
    if (json == null) {
        return json;
    }
    return {

        'currentGeneralGrade': json['currentGeneralGrade'] == null ? undefined : json['currentGeneralGrade'],
        'dressageApproved': json['dressageApproved'] == null ? undefined : json['dressageApproved'],
        'jumpingApproved': json['jumpingApproved'] == null ? undefined : json['jumpingApproved'],
        'canUseLargeArena': json['canUseLargeArena'] == null ? undefined : json['canUseLargeArena'],
        'availableRidingClasses': json['availableRidingClasses'] == null ? undefined : json['availableRidingClasses'],
    };
}

export function MemberAvailableRidingClassesResponseToJSON(json: any): MemberAvailableRidingClassesResponse {
    return MemberAvailableRidingClassesResponseToJSONTyped(json, false);
}

export function MemberAvailableRidingClassesResponseToJSONTyped(value?: MemberAvailableRidingClassesResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'currentGeneralGrade': value['currentGeneralGrade'],
        'dressageApproved': value['dressageApproved'],
        'jumpingApproved': value['jumpingApproved'],
        'canUseLargeArena': value['canUseLargeArena'],
        'availableRidingClasses': value['availableRidingClasses'],
    };
}

