/* tslint:disable */
/* eslint-disable */
/**
 * Horse Reservation API
 * 마장 예약 서비스 API
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface MemberCouponUsageResponse
 */
export interface MemberCouponUsageResponse {
    /**
     *
     * @type {number}
     * @memberof MemberCouponUsageResponse
     */
    usageLogId: number;
    /**
     *
     * @type {number}
     * @memberof MemberCouponUsageResponse
     */
    couponId: number;
    /**
     *
     * @type {number}
     * @memberof MemberCouponUsageResponse
     */
    reservationId: number | null;
    /**
     *
     * @type {string}
     * @memberof MemberCouponUsageResponse
     */
    action: string;
    /**
     *
     * @type {number}
     * @memberof MemberCouponUsageResponse
     */
    countDelta: number;
    /**
     *
     * @type {Date}
     * @memberof MemberCouponUsageResponse
     */
    occurredAt: Date;
    /**
     *
     * @type {string}
     * @memberof MemberCouponUsageResponse
     */
    actorType: string;
}

/**
 * Check if a given object implements the MemberCouponUsageResponse interface.
 */
export function instanceOfMemberCouponUsageResponse(value: object): value is MemberCouponUsageResponse {
    if (!('usageLogId' in value) || value['usageLogId'] === undefined) return false;
    if (!('couponId' in value) || value['couponId'] === undefined) return false;
    if (!('reservationId' in value) || value['reservationId'] === undefined) return false;
    if (!('action' in value) || value['action'] === undefined) return false;
    if (!('countDelta' in value) || value['countDelta'] === undefined) return false;
    if (!('occurredAt' in value) || value['occurredAt'] === undefined) return false;
    if (!('actorType' in value) || value['actorType'] === undefined) return false;
    return true;
}

export function MemberCouponUsageResponseFromJSON(json: any): MemberCouponUsageResponse {
    return MemberCouponUsageResponseFromJSONTyped(json, false);
}

export function MemberCouponUsageResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): MemberCouponUsageResponse {
    if (json == null) {
        return json;
    }
    return {

        'usageLogId': json['usageLogId'],
        'couponId': json['couponId'],
        'reservationId': json['reservationId'],
        'action': json['action'],
        'countDelta': json['countDelta'],
        'occurredAt': (new Date(json['occurredAt'])),
        'actorType': json['actorType'],
    };
}

export function MemberCouponUsageResponseToJSON(json: any): MemberCouponUsageResponse {
    return MemberCouponUsageResponseToJSONTyped(json, false);
}

export function MemberCouponUsageResponseToJSONTyped(value?: MemberCouponUsageResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'usageLogId': value['usageLogId'],
        'couponId': value['couponId'],
        'reservationId': value['reservationId'],
        'action': value['action'],
        'countDelta': value['countDelta'],
        'occurredAt': value['occurredAt'].toISOString(),
        'actorType': value['actorType'],
    };
}

