/* tslint:disable */
/* eslint-disable */
/**
 * Horse Reservation API
 * 마장 예약 서비스 API
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MemberCouponUsageResponse } from './MemberCouponUsageResponse';
import {
    MemberCouponUsageResponseFromJSON,
    MemberCouponUsageResponseFromJSONTyped,
    MemberCouponUsageResponseToJSON,
    MemberCouponUsageResponseToJSONTyped,
} from './MemberCouponUsageResponse';

/**
 *
 * @export
 * @interface MemberCouponUsagePageResponse
 */
export interface MemberCouponUsagePageResponse {
    /**
     *
     * @type {Array<MemberCouponUsageResponse>}
     * @memberof MemberCouponUsagePageResponse
     */
    content?: Array<MemberCouponUsageResponse>;
    /**
     *
     * @type {number}
     * @memberof MemberCouponUsagePageResponse
     */
    page?: number;
    /**
     *
     * @type {number}
     * @memberof MemberCouponUsagePageResponse
     */
    size?: number;
    /**
     *
     * @type {number}
     * @memberof MemberCouponUsagePageResponse
     */
    totalElements?: number;
    /**
     *
     * @type {number}
     * @memberof MemberCouponUsagePageResponse
     */
    totalPages?: number;
    /**
     *
     * @type {boolean}
     * @memberof MemberCouponUsagePageResponse
     */
    hasNext?: boolean;
}

/**
 * Check if a given object implements the MemberCouponUsagePageResponse interface.
 */
export function instanceOfMemberCouponUsagePageResponse(value: object): value is MemberCouponUsagePageResponse {
    return true;
}

export function MemberCouponUsagePageResponseFromJSON(json: any): MemberCouponUsagePageResponse {
    return MemberCouponUsagePageResponseFromJSONTyped(json, false);
}

export function MemberCouponUsagePageResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): MemberCouponUsagePageResponse {
    if (json == null) {
        return json;
    }
    return {

        'content': json['content'] == null ? undefined : ((json['content'] as Array<any>).map(MemberCouponUsageResponseFromJSON)),
        'page': json['page'] == null ? undefined : json['page'],
        'size': json['size'] == null ? undefined : json['size'],
        'totalElements': json['totalElements'] == null ? undefined : json['totalElements'],
        'totalPages': json['totalPages'] == null ? undefined : json['totalPages'],
        'hasNext': json['hasNext'] == null ? undefined : json['hasNext'],
    };
}

export function MemberCouponUsagePageResponseToJSON(json: any): MemberCouponUsagePageResponse {
    return MemberCouponUsagePageResponseToJSONTyped(json, false);
}

export function MemberCouponUsagePageResponseToJSONTyped(value?: MemberCouponUsagePageResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'content': value['content'] == null ? undefined : ((value['content'] as Array<any>).map(MemberCouponUsageResponseToJSON)),
        'page': value['page'],
        'size': value['size'],
        'totalElements': value['totalElements'],
        'totalPages': value['totalPages'],
        'hasNext': value['hasNext'],
    };
}
