/* tslint:disable */
/* eslint-disable */
/**
 * Horse Reservation API
 * 마장 예약 서비스 API
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface MemberClassProgressionProjectionResponse
 */
export interface MemberClassProgressionProjectionResponse {
    /**
     *
     * @type {number}
     * @memberof MemberClassProgressionProjectionResponse
     */
    actualCompletedRideCount: number;
    /**
     *
     * @type {number}
     * @memberof MemberClassProgressionProjectionResponse
     */
    progressionValue: number;
    /**
     *
     * @type {MemberClassProgressionProjectionResponseProgressionClassEnum}
     * @memberof MemberClassProgressionProjectionResponse
     */
    progressionClass: MemberClassProgressionProjectionResponseProgressionClassEnum;
    /**
     *
     * @type {MemberClassProgressionProjectionResponseEffectiveClassEnum}
     * @memberof MemberClassProgressionProjectionResponse
     */
    effectiveClass: MemberClassProgressionProjectionResponseEffectiveClassEnum;
    /**
     *
     * @type {MemberClassProgressionProjectionResponseBaselineClassEnum}
     * @memberof MemberClassProgressionProjectionResponse
     */
    baselineClass: MemberClassProgressionProjectionResponseBaselineClassEnum | null;
    /**
     *
     * @type {number}
     * @memberof MemberClassProgressionProjectionResponse
     */
    baselineThreshold: number | null;
    /**
     *
     * @type {number}
     * @memberof MemberClassProgressionProjectionResponse
     */
    baselineActualRideCount: number | null;
    /**
     *
     * @type {number}
     * @memberof MemberClassProgressionProjectionResponse
     */
    specialApprovalProgressionCredit: number;
    /**
     *
     * @type {MemberClassProgressionProjectionResponsePromotionHoldClassEnum}
     * @memberof MemberClassProgressionProjectionResponse
     */
    promotionHoldClass: MemberClassProgressionProjectionResponsePromotionHoldClassEnum | null;
}


/**
 * @export
 */
export const MemberClassProgressionProjectionResponseProgressionClassEnum = {
    FirstRide: 'FIRST_RIDE',
    RoundBeginner: 'ROUND_BEGINNER',
    RoundTrot: 'ROUND_TROT',
    LargeArenaBeginner: 'LARGE_ARENA_BEGINNER',
    LargeArenaTrot: 'LARGE_ARENA_TROT',
    CanterBeginner: 'CANTER_BEGINNER',
    Canter: 'CANTER'
} as const;
export type MemberClassProgressionProjectionResponseProgressionClassEnum = typeof MemberClassProgressionProjectionResponseProgressionClassEnum[keyof typeof MemberClassProgressionProjectionResponseProgressionClassEnum];

/**
 * @export
 */
export const MemberClassProgressionProjectionResponseEffectiveClassEnum = {
    FirstRide: 'FIRST_RIDE',
    RoundBeginner: 'ROUND_BEGINNER',
    RoundTrot: 'ROUND_TROT',
    LargeArenaBeginner: 'LARGE_ARENA_BEGINNER',
    LargeArenaTrot: 'LARGE_ARENA_TROT',
    CanterBeginner: 'CANTER_BEGINNER',
    Canter: 'CANTER'
} as const;
export type MemberClassProgressionProjectionResponseEffectiveClassEnum = typeof MemberClassProgressionProjectionResponseEffectiveClassEnum[keyof typeof MemberClassProgressionProjectionResponseEffectiveClassEnum];

/**
 * @export
 */
export const MemberClassProgressionProjectionResponseBaselineClassEnum = {
    FirstRide: 'FIRST_RIDE',
    RoundBeginner: 'ROUND_BEGINNER',
    RoundTrot: 'ROUND_TROT',
    LargeArenaBeginner: 'LARGE_ARENA_BEGINNER',
    LargeArenaTrot: 'LARGE_ARENA_TROT',
    CanterBeginner: 'CANTER_BEGINNER',
    Canter: 'CANTER'
} as const;
export type MemberClassProgressionProjectionResponseBaselineClassEnum = typeof MemberClassProgressionProjectionResponseBaselineClassEnum[keyof typeof MemberClassProgressionProjectionResponseBaselineClassEnum];

/**
 * @export
 */
export const MemberClassProgressionProjectionResponsePromotionHoldClassEnum = {
    FirstRide: 'FIRST_RIDE',
    RoundBeginner: 'ROUND_BEGINNER',
    RoundTrot: 'ROUND_TROT',
    LargeArenaBeginner: 'LARGE_ARENA_BEGINNER',
    LargeArenaTrot: 'LARGE_ARENA_TROT',
    CanterBeginner: 'CANTER_BEGINNER',
    Canter: 'CANTER'
} as const;
export type MemberClassProgressionProjectionResponsePromotionHoldClassEnum = typeof MemberClassProgressionProjectionResponsePromotionHoldClassEnum[keyof typeof MemberClassProgressionProjectionResponsePromotionHoldClassEnum];


/**
 * Check if a given object implements the MemberClassProgressionProjectionResponse interface.
 */
export function instanceOfMemberClassProgressionProjectionResponse(value: object): value is MemberClassProgressionProjectionResponse {
    if (!('actualCompletedRideCount' in value) || value['actualCompletedRideCount'] === undefined) return false;
    if (!('progressionValue' in value) || value['progressionValue'] === undefined) return false;
    if (!('progressionClass' in value) || value['progressionClass'] === undefined) return false;
    if (!('effectiveClass' in value) || value['effectiveClass'] === undefined) return false;
    if (!('baselineClass' in value) || value['baselineClass'] === undefined) return false;
    if (!('baselineThreshold' in value) || value['baselineThreshold'] === undefined) return false;
    if (!('baselineActualRideCount' in value) || value['baselineActualRideCount'] === undefined) return false;
    if (!('specialApprovalProgressionCredit' in value) || value['specialApprovalProgressionCredit'] === undefined) return false;
    if (!('promotionHoldClass' in value) || value['promotionHoldClass'] === undefined) return false;
    return true;
}

export function MemberClassProgressionProjectionResponseFromJSON(json: any): MemberClassProgressionProjectionResponse {
    return MemberClassProgressionProjectionResponseFromJSONTyped(json, false);
}

export function MemberClassProgressionProjectionResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): MemberClassProgressionProjectionResponse {
    if (json == null) {
        return json;
    }
    return {

        'actualCompletedRideCount': json['actualCompletedRideCount'],
        'progressionValue': json['progressionValue'],
        'progressionClass': json['progressionClass'],
        'effectiveClass': json['effectiveClass'],
        'baselineClass': json['baselineClass'],
        'baselineThreshold': json['baselineThreshold'],
        'baselineActualRideCount': json['baselineActualRideCount'],
        'specialApprovalProgressionCredit': json['specialApprovalProgressionCredit'],
        'promotionHoldClass': json['promotionHoldClass'],
    };
}

export function MemberClassProgressionProjectionResponseToJSON(json: any): MemberClassProgressionProjectionResponse {
    return MemberClassProgressionProjectionResponseToJSONTyped(json, false);
}

export function MemberClassProgressionProjectionResponseToJSONTyped(value?: MemberClassProgressionProjectionResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'actualCompletedRideCount': value['actualCompletedRideCount'],
        'progressionValue': value['progressionValue'],
        'progressionClass': value['progressionClass'],
        'effectiveClass': value['effectiveClass'],
        'baselineClass': value['baselineClass'],
        'baselineThreshold': value['baselineThreshold'],
        'baselineActualRideCount': value['baselineActualRideCount'],
        'specialApprovalProgressionCredit': value['specialApprovalProgressionCredit'],
        'promotionHoldClass': value['promotionHoldClass'],
    };
}
