/* tslint:disable */
/* eslint-disable */
/**
 * Horse Reservation API
 * 마장 예약 서비스 API
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface MemberCouponResponse
 */
export interface MemberCouponResponse {
    /**
     *
     * @type {number}
     * @memberof MemberCouponResponse
     */
    couponId: number;
    /**
     *
     * @type {string}
     * @memberof MemberCouponResponse
     */
    type: string;
    /**
     *
     * @type {number}
     * @memberof MemberCouponResponse
     */
    totalCount: number;
    /**
     *
     * @type {number}
     * @memberof MemberCouponResponse
     */
    remainingCount: number;
    /**
     *
     * @type {number}
     * @memberof MemberCouponResponse
     */
    heldCount: number;
    /**
     *
     * @type {number}
     * @memberof MemberCouponResponse
     */
    availableCount: number;
    /**
     *
     * @type {Date}
     * @memberof MemberCouponResponse
     */
    firstUsedAt: Date | null;
    /**
     *
     * @type {Date}
     * @memberof MemberCouponResponse
     */
    expiresAt: Date | null;
    /**
     *
     * @type {boolean}
     * @memberof MemberCouponResponse
     */
    freeChangeUsed: boolean;
    /**
     *
     * @type {string}
     * @memberof MemberCouponResponse
     */
    status: string;
}

/**
 * Check if a given object implements the MemberCouponResponse interface.
 */
export function instanceOfMemberCouponResponse(value: object): value is MemberCouponResponse {
    if (!('couponId' in value) || value['couponId'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('totalCount' in value) || value['totalCount'] === undefined) return false;
    if (!('remainingCount' in value) || value['remainingCount'] === undefined) return false;
    if (!('heldCount' in value) || value['heldCount'] === undefined) return false;
    if (!('availableCount' in value) || value['availableCount'] === undefined) return false;
    if (!('firstUsedAt' in value) || value['firstUsedAt'] === undefined) return false;
    if (!('expiresAt' in value) || value['expiresAt'] === undefined) return false;
    if (!('freeChangeUsed' in value) || value['freeChangeUsed'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function MemberCouponResponseFromJSON(json: any): MemberCouponResponse {
    return MemberCouponResponseFromJSONTyped(json, false);
}

export function MemberCouponResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): MemberCouponResponse {
    if (json == null) {
        return json;
    }
    return {

        'couponId': json['couponId'],
        'type': json['type'],
        'totalCount': json['totalCount'],
        'remainingCount': json['remainingCount'],
        'heldCount': json['heldCount'],
        'availableCount': json['availableCount'],
        'firstUsedAt': (json['firstUsedAt'] == null ? null : new Date(json['firstUsedAt'])),
        'expiresAt': (json['expiresAt'] == null ? null : new Date(json['expiresAt'])),
        'freeChangeUsed': json['freeChangeUsed'],
        'status': json['status'],
    };
}

export function MemberCouponResponseToJSON(json: any): MemberCouponResponse {
    return MemberCouponResponseToJSONTyped(json, false);
}

export function MemberCouponResponseToJSONTyped(value?: MemberCouponResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'couponId': value['couponId'],
        'type': value['type'],
        'totalCount': value['totalCount'],
        'remainingCount': value['remainingCount'],
        'heldCount': value['heldCount'],
        'availableCount': value['availableCount'],
        'firstUsedAt': value['firstUsedAt'] == null ? value['firstUsedAt'] : value['firstUsedAt'].toISOString(),
        'expiresAt': value['expiresAt'] == null ? value['expiresAt'] : value['expiresAt'].toISOString(),
        'freeChangeUsed': value['freeChangeUsed'],
        'status': value['status'],
    };
}

