/* tslint:disable */
/* eslint-disable */
/**
 * Horse Reservation API
 * 마장 예약 서비스 API
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface MemberReservationCouponResponse
 */
export interface MemberReservationCouponResponse {
    /**
     *
     * @type {number}
     * @memberof MemberReservationCouponResponse
     */
    couponId?: number;
    /**
     *
     * @type {string}
     * @memberof MemberReservationCouponResponse
     */
    couponType?: string;
    /**
     *
     * @type {string}
     * @memberof MemberReservationCouponResponse
     */
    status?: string;
    /**
     *
     * @type {number}
     * @memberof MemberReservationCouponResponse
     */
    remainingCount?: number;
    /**
     *
     * @type {number}
     * @memberof MemberReservationCouponResponse
     */
    heldCount?: number;
    /**
     *
     * @type {number}
     * @memberof MemberReservationCouponResponse
     */
    availableCount?: number;
    /**
     *
     * @type {Date}
     * @memberof MemberReservationCouponResponse
     */
    expiresAt?: Date;
}

/**
 * Check if a given object implements the MemberReservationCouponResponse interface.
 */
export function instanceOfMemberReservationCouponResponse(value: object): value is MemberReservationCouponResponse {
    return true;
}

export function MemberReservationCouponResponseFromJSON(json: any): MemberReservationCouponResponse {
    return MemberReservationCouponResponseFromJSONTyped(json, false);
}

export function MemberReservationCouponResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): MemberReservationCouponResponse {
    if (json == null) {
        return json;
    }
    return {

        'couponId': json['couponId'] == null ? undefined : json['couponId'],
        'couponType': json['couponType'] == null ? undefined : json['couponType'],
        'status': json['status'] == null ? undefined : json['status'],
        'remainingCount': json['remainingCount'] == null ? undefined : json['remainingCount'],
        'heldCount': json['heldCount'] == null ? undefined : json['heldCount'],
        'availableCount': json['availableCount'] == null ? undefined : json['availableCount'],
        'expiresAt': json['expiresAt'] == null ? undefined : (new Date(json['expiresAt'])),
    };
}

export function MemberReservationCouponResponseToJSON(json: any): MemberReservationCouponResponse {
    return MemberReservationCouponResponseToJSONTyped(json, false);
}

export function MemberReservationCouponResponseToJSONTyped(value?: MemberReservationCouponResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'couponId': value['couponId'],
        'couponType': value['couponType'],
        'status': value['status'],
        'remainingCount': value['remainingCount'],
        'heldCount': value['heldCount'],
        'availableCount': value['availableCount'],
        'expiresAt': value['expiresAt'] == null ? value['expiresAt'] : value['expiresAt'].toISOString(),
    };
}

