/* tslint:disable */
/* eslint-disable */
/**
 * Horse Reservation API
 * 마장 예약 서비스 API
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MemberReservationCouponResponse } from './MemberReservationCouponResponse';
import {
    MemberReservationCouponResponseFromJSON,
    MemberReservationCouponResponseFromJSONTyped,
    MemberReservationCouponResponseToJSON,
    MemberReservationCouponResponseToJSONTyped,
} from './MemberReservationCouponResponse';

/**
 *
 * @export
 * @interface MemberReservationResponse
 */
export interface MemberReservationResponse {
    /**
     *
     * @type {number}
     * @memberof MemberReservationResponse
     */
    reservationId?: number;
    /**
     *
     * @type {string}
     * @memberof MemberReservationResponse
     */
    classType?: string;
    /**
     *
     * @type {Date}
     * @memberof MemberReservationResponse
     */
    lessonDate?: Date;
    /**
     *
     * @type {string}
     * @memberof MemberReservationResponse
     */
    startTime?: string;
    /**
     *
     * @type {string}
     * @memberof MemberReservationResponse
     */
    status?: string;
    /**
     *
     * @type {string}
     * @memberof MemberReservationResponse
     */
    paymentSource?: string;
    /**
     *
     * @type {MemberReservationCouponResponse}
     * @memberof MemberReservationResponse
     */
    coupon?: MemberReservationCouponResponse;
    /**
     *
     * @type {Date}
     * @memberof MemberReservationResponse
     */
    paymentDueAt?: Date;
    /**
     *
     * @type {string}
     * @memberof MemberReservationResponse
     */
    rejectionReason?: string;
    /**
     *
     * @type {string}
     * @memberof MemberReservationResponse
     */
    couponAction?: string;
    /**
     *
     * @type {Date}
     * @memberof MemberReservationResponse
     */
    approvalRequestedAt?: Date;
    /**
     *
     * @type {Date}
     * @memberof MemberReservationResponse
     */
    adminConfirmedAt?: Date;
    /**
     *
     * @type {Date}
     * @memberof MemberReservationResponse
     */
    rejectedAt?: Date;
    /**
     *
     * @type {Date}
     * @memberof MemberReservationResponse
     */
    cancelledAt?: Date;
}

/**
 * Check if a given object implements the MemberReservationResponse interface.
 */
export function instanceOfMemberReservationResponse(value: object): value is MemberReservationResponse {
    return true;
}

export function MemberReservationResponseFromJSON(json: any): MemberReservationResponse {
    return MemberReservationResponseFromJSONTyped(json, false);
}

export function MemberReservationResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): MemberReservationResponse {
    if (json == null) {
        return json;
    }
    return {

        'reservationId': json['reservationId'] == null ? undefined : json['reservationId'],
        'classType': json['classType'] == null ? undefined : json['classType'],
        'lessonDate': json['lessonDate'] == null ? undefined : (new Date(json['lessonDate'])),
        'startTime': json['startTime'] == null ? undefined : json['startTime'],
        'status': json['status'] == null ? undefined : json['status'],
        'paymentSource': json['paymentSource'] == null ? undefined : json['paymentSource'],
        'coupon': json['coupon'] == null ? undefined : MemberReservationCouponResponseFromJSON(json['coupon']),
        'paymentDueAt': json['paymentDueAt'] == null ? undefined : (new Date(json['paymentDueAt'])),
        'rejectionReason': json['rejectionReason'] == null ? undefined : json['rejectionReason'],
        'couponAction': json['couponAction'] == null ? undefined : json['couponAction'],
        'approvalRequestedAt': json['approvalRequestedAt'] == null ? undefined : (new Date(json['approvalRequestedAt'])),
        'adminConfirmedAt': json['adminConfirmedAt'] == null ? undefined : (new Date(json['adminConfirmedAt'])),
        'rejectedAt': json['rejectedAt'] == null ? undefined : (new Date(json['rejectedAt'])),
        'cancelledAt': json['cancelledAt'] == null ? undefined : (new Date(json['cancelledAt'])),
    };
}

export function MemberReservationResponseToJSON(json: any): MemberReservationResponse {
    return MemberReservationResponseToJSONTyped(json, false);
}

export function MemberReservationResponseToJSONTyped(value?: MemberReservationResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'reservationId': value['reservationId'],
        'classType': value['classType'],
        'lessonDate': value['lessonDate'] == null ? value['lessonDate'] : value['lessonDate'].toISOString().substring(0,10),
        'startTime': value['startTime'],
        'status': value['status'],
        'paymentSource': value['paymentSource'],
        'coupon': MemberReservationCouponResponseToJSON(value['coupon']),
        'paymentDueAt': value['paymentDueAt'] == null ? value['paymentDueAt'] : value['paymentDueAt'].toISOString(),
        'rejectionReason': value['rejectionReason'],
        'couponAction': value['couponAction'],
        'approvalRequestedAt': value['approvalRequestedAt'] == null ? value['approvalRequestedAt'] : value['approvalRequestedAt'].toISOString(),
        'adminConfirmedAt': value['adminConfirmedAt'] == null ? value['adminConfirmedAt'] : value['adminConfirmedAt'].toISOString(),
        'rejectedAt': value['rejectedAt'] == null ? value['rejectedAt'] : value['rejectedAt'].toISOString(),
        'cancelledAt': value['cancelledAt'] == null ? value['cancelledAt'] : value['cancelledAt'].toISOString(),
    };
}

