/* tslint:disable */
/* eslint-disable */
/**
 * Horse Reservation API
 * 마장 예약 서비스 API
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface MemberRidingPermissionUpdateRequest
 */
export interface MemberRidingPermissionUpdateRequest {
    /**
     *
     * @type {boolean}
     * @memberof MemberRidingPermissionUpdateRequest
     */
    dressageApproved?: boolean;
    /**
     *
     * @type {boolean}
     * @memberof MemberRidingPermissionUpdateRequest
     */
    jumpingApproved?: boolean;
}

/**
 * Check if a given object implements the MemberRidingPermissionUpdateRequest interface.
 */
export function instanceOfMemberRidingPermissionUpdateRequest(value: object): value is MemberRidingPermissionUpdateRequest {
    return true;
}

export function MemberRidingPermissionUpdateRequestFromJSON(json: any): MemberRidingPermissionUpdateRequest {
    return MemberRidingPermissionUpdateRequestFromJSONTyped(json, false);
}

export function MemberRidingPermissionUpdateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): MemberRidingPermissionUpdateRequest {
    if (json == null) {
        return json;
    }
    return {

        'dressageApproved': json['dressageApproved'] == null ? undefined : json['dressageApproved'],
        'jumpingApproved': json['jumpingApproved'] == null ? undefined : json['jumpingApproved'],
    };
}

export function MemberRidingPermissionUpdateRequestToJSON(json: any): MemberRidingPermissionUpdateRequest {
    return MemberRidingPermissionUpdateRequestToJSONTyped(json, false);
}

export function MemberRidingPermissionUpdateRequestToJSONTyped(value?: MemberRidingPermissionUpdateRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'dressageApproved': value['dressageApproved'],
        'jumpingApproved': value['jumpingApproved'],
    };
}

