/* tslint:disable */
/* eslint-disable */
/**
 * Horse Reservation API
 * 마장 예약 서비스 API
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface MemberClassProgressionPreviewRequest
 */
export interface MemberClassProgressionPreviewRequest {
    /**
     *
     * @type {MemberClassProgressionPreviewRequestActionEnum}
     * @memberof MemberClassProgressionPreviewRequest
     */
    action: MemberClassProgressionPreviewRequestActionEnum;
    /**
     *
     * @type {MemberClassProgressionPreviewRequestBaselineClassEnum}
     * @memberof MemberClassProgressionPreviewRequest
     */
    baselineClass?: MemberClassProgressionPreviewRequestBaselineClassEnum;
    /**
     *
     * @type {MemberClassProgressionPreviewRequestPromotionHoldClassEnum}
     * @memberof MemberClassProgressionPreviewRequest
     */
    promotionHoldClass?: MemberClassProgressionPreviewRequestPromotionHoldClassEnum;
    /**
     *
     * @type {number}
     * @memberof MemberClassProgressionPreviewRequest
     */
    specialApprovalProgressionCredit?: number;
    /**
     *
     * @type {number}
     * @memberof MemberClassProgressionPreviewRequest
     */
    rideCountDelta?: number;
}


/**
 * @export
 */
export const MemberClassProgressionPreviewRequestActionEnum = {
    SetBaseline: 'SET_BASELINE',
    RemoveBaseline: 'REMOVE_BASELINE',
    SetPromotionHold: 'SET_PROMOTION_HOLD',
    RemovePromotionHold: 'REMOVE_PROMOTION_HOLD',
    CorrectSpecialApprovalCredit: 'CORRECT_SPECIAL_APPROVAL_CREDIT',
    AdjustRideCount: 'ADJUST_RIDE_COUNT'
} as const;
export type MemberClassProgressionPreviewRequestActionEnum = typeof MemberClassProgressionPreviewRequestActionEnum[keyof typeof MemberClassProgressionPreviewRequestActionEnum];

/**
 * @export
 */
export const MemberClassProgressionPreviewRequestBaselineClassEnum = {
    FirstRide: 'FIRST_RIDE',
    RoundBeginner: 'ROUND_BEGINNER',
    RoundTrot: 'ROUND_TROT',
    LargeArenaBeginner: 'LARGE_ARENA_BEGINNER',
    LargeArenaTrot: 'LARGE_ARENA_TROT',
    CanterBeginner: 'CANTER_BEGINNER',
    Canter: 'CANTER'
} as const;
export type MemberClassProgressionPreviewRequestBaselineClassEnum = typeof MemberClassProgressionPreviewRequestBaselineClassEnum[keyof typeof MemberClassProgressionPreviewRequestBaselineClassEnum];

/**
 * @export
 */
export const MemberClassProgressionPreviewRequestPromotionHoldClassEnum = {
    FirstRide: 'FIRST_RIDE',
    RoundBeginner: 'ROUND_BEGINNER',
    RoundTrot: 'ROUND_TROT',
    LargeArenaBeginner: 'LARGE_ARENA_BEGINNER',
    LargeArenaTrot: 'LARGE_ARENA_TROT',
    CanterBeginner: 'CANTER_BEGINNER',
    Canter: 'CANTER'
} as const;
export type MemberClassProgressionPreviewRequestPromotionHoldClassEnum = typeof MemberClassProgressionPreviewRequestPromotionHoldClassEnum[keyof typeof MemberClassProgressionPreviewRequestPromotionHoldClassEnum];


/**
 * Check if a given object implements the MemberClassProgressionPreviewRequest interface.
 */
export function instanceOfMemberClassProgressionPreviewRequest(value: object): value is MemberClassProgressionPreviewRequest {
    if (!('action' in value) || value['action'] === undefined) return false;
    return true;
}

export function MemberClassProgressionPreviewRequestFromJSON(json: any): MemberClassProgressionPreviewRequest {
    return MemberClassProgressionPreviewRequestFromJSONTyped(json, false);
}

export function MemberClassProgressionPreviewRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): MemberClassProgressionPreviewRequest {
    if (json == null) {
        return json;
    }
    return {

        'action': json['action'],
        'baselineClass': json['baselineClass'] == null ? undefined : json['baselineClass'],
        'promotionHoldClass': json['promotionHoldClass'] == null ? undefined : json['promotionHoldClass'],
        'specialApprovalProgressionCredit': json['specialApprovalProgressionCredit'] == null ? undefined : json['specialApprovalProgressionCredit'],
        'rideCountDelta': json['rideCountDelta'] == null ? undefined : json['rideCountDelta'],
    };
}

export function MemberClassProgressionPreviewRequestToJSON(json: any): MemberClassProgressionPreviewRequest {
    return MemberClassProgressionPreviewRequestToJSONTyped(json, false);
}

export function MemberClassProgressionPreviewRequestToJSONTyped(value?: MemberClassProgressionPreviewRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'action': value['action'],
        'baselineClass': value['baselineClass'],
        'promotionHoldClass': value['promotionHoldClass'],
        'specialApprovalProgressionCredit': value['specialApprovalProgressionCredit'],
        'rideCountDelta': value['rideCountDelta'],
    };
}
