/* tslint:disable */
/* eslint-disable */
/**
 * Horse Reservation API
 * 마장 예약 서비스 API
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface MemberClassProgressionAuditStateResponse
 */
export interface MemberClassProgressionAuditStateResponse {
    /**
     *
     * @type {number}
     * @memberof MemberClassProgressionAuditStateResponse
     */
    actualCompletedRideCount: number | null;
    /**
     *
     * @type {number}
     * @memberof MemberClassProgressionAuditStateResponse
     */
    progressionValue: number | null;
    /**
     *
     * @type {MemberClassProgressionAuditStateResponseProgressionClassEnum}
     * @memberof MemberClassProgressionAuditStateResponse
     */
    progressionClass: MemberClassProgressionAuditStateResponseProgressionClassEnum | null;
    /**
     *
     * @type {MemberClassProgressionAuditStateResponseEffectiveClassEnum}
     * @memberof MemberClassProgressionAuditStateResponse
     */
    effectiveClass: MemberClassProgressionAuditStateResponseEffectiveClassEnum | null;
    /**
     *
     * @type {string}
     * @memberof MemberClassProgressionAuditStateResponse
     */
    managementStartedAt: string | null;
    /**
     *
     * @type {MemberClassProgressionAuditStateResponseBaselineClassEnum}
     * @memberof MemberClassProgressionAuditStateResponse
     */
    baselineClass: MemberClassProgressionAuditStateResponseBaselineClassEnum | null;
    /**
     *
     * @type {number}
     * @memberof MemberClassProgressionAuditStateResponse
     */
    baselineThreshold: number | null;
    /**
     *
     * @type {number}
     * @memberof MemberClassProgressionAuditStateResponse
     */
    baselineActualRideCount: number | null;
    /**
     *
     * @type {number}
     * @memberof MemberClassProgressionAuditStateResponse
     */
    specialApprovalProgressionCredit: number | null;
    /**
     *
     * @type {MemberClassProgressionAuditStateResponsePromotionHoldClassEnum}
     * @memberof MemberClassProgressionAuditStateResponse
     */
    promotionHoldClass: MemberClassProgressionAuditStateResponsePromotionHoldClassEnum | null;
    /**
     *
     * @type {boolean}
     * @memberof MemberClassProgressionAuditStateResponse
     */
    dressageApproved: boolean | null;
    /**
     *
     * @type {boolean}
     * @memberof MemberClassProgressionAuditStateResponse
     */
    jumpingApproved: boolean | null;
    /**
     *
     * @type {number}
     * @memberof MemberClassProgressionAuditStateResponse
     */
    rideCountDelta: number | null;
}


/**
 * @export
 */
export const MemberClassProgressionAuditStateResponseProgressionClassEnum = {
    FirstRide: 'FIRST_RIDE',
    RoundBeginner: 'ROUND_BEGINNER',
    RoundTrot: 'ROUND_TROT',
    LargeArenaBeginner: 'LARGE_ARENA_BEGINNER',
    LargeArenaTrot: 'LARGE_ARENA_TROT',
    CanterBeginner: 'CANTER_BEGINNER',
    Canter: 'CANTER'
} as const;
export type MemberClassProgressionAuditStateResponseProgressionClassEnum = typeof MemberClassProgressionAuditStateResponseProgressionClassEnum[keyof typeof MemberClassProgressionAuditStateResponseProgressionClassEnum];

/**
 * @export
 */
export const MemberClassProgressionAuditStateResponseEffectiveClassEnum = {
    FirstRide: 'FIRST_RIDE',
    RoundBeginner: 'ROUND_BEGINNER',
    RoundTrot: 'ROUND_TROT',
    LargeArenaBeginner: 'LARGE_ARENA_BEGINNER',
    LargeArenaTrot: 'LARGE_ARENA_TROT',
    CanterBeginner: 'CANTER_BEGINNER',
    Canter: 'CANTER'
} as const;
export type MemberClassProgressionAuditStateResponseEffectiveClassEnum = typeof MemberClassProgressionAuditStateResponseEffectiveClassEnum[keyof typeof MemberClassProgressionAuditStateResponseEffectiveClassEnum];

/**
 * @export
 */
export const MemberClassProgressionAuditStateResponseBaselineClassEnum = {
    FirstRide: 'FIRST_RIDE',
    RoundBeginner: 'ROUND_BEGINNER',
    RoundTrot: 'ROUND_TROT',
    LargeArenaBeginner: 'LARGE_ARENA_BEGINNER',
    LargeArenaTrot: 'LARGE_ARENA_TROT',
    CanterBeginner: 'CANTER_BEGINNER',
    Canter: 'CANTER'
} as const;
export type MemberClassProgressionAuditStateResponseBaselineClassEnum = typeof MemberClassProgressionAuditStateResponseBaselineClassEnum[keyof typeof MemberClassProgressionAuditStateResponseBaselineClassEnum];

/**
 * @export
 */
export const MemberClassProgressionAuditStateResponsePromotionHoldClassEnum = {
    FirstRide: 'FIRST_RIDE',
    RoundBeginner: 'ROUND_BEGINNER',
    RoundTrot: 'ROUND_TROT',
    LargeArenaBeginner: 'LARGE_ARENA_BEGINNER',
    LargeArenaTrot: 'LARGE_ARENA_TROT',
    CanterBeginner: 'CANTER_BEGINNER',
    Canter: 'CANTER'
} as const;
export type MemberClassProgressionAuditStateResponsePromotionHoldClassEnum = typeof MemberClassProgressionAuditStateResponsePromotionHoldClassEnum[keyof typeof MemberClassProgressionAuditStateResponsePromotionHoldClassEnum];


/**
 * Check if a given object implements the MemberClassProgressionAuditStateResponse interface.
 */
export function instanceOfMemberClassProgressionAuditStateResponse(value: object): value is MemberClassProgressionAuditStateResponse {
    if (!('actualCompletedRideCount' in value) || value['actualCompletedRideCount'] === undefined) return false;
    if (!('progressionValue' in value) || value['progressionValue'] === undefined) return false;
    if (!('progressionClass' in value) || value['progressionClass'] === undefined) return false;
    if (!('effectiveClass' in value) || value['effectiveClass'] === undefined) return false;
    if (!('managementStartedAt' in value) || value['managementStartedAt'] === undefined) return false;
    if (!('baselineClass' in value) || value['baselineClass'] === undefined) return false;
    if (!('baselineThreshold' in value) || value['baselineThreshold'] === undefined) return false;
    if (!('baselineActualRideCount' in value) || value['baselineActualRideCount'] === undefined) return false;
    if (!('specialApprovalProgressionCredit' in value) || value['specialApprovalProgressionCredit'] === undefined) return false;
    if (!('promotionHoldClass' in value) || value['promotionHoldClass'] === undefined) return false;
    if (!('dressageApproved' in value) || value['dressageApproved'] === undefined) return false;
    if (!('jumpingApproved' in value) || value['jumpingApproved'] === undefined) return false;
    if (!('rideCountDelta' in value) || value['rideCountDelta'] === undefined) return false;
    return true;
}

export function MemberClassProgressionAuditStateResponseFromJSON(json: any): MemberClassProgressionAuditStateResponse {
    return MemberClassProgressionAuditStateResponseFromJSONTyped(json, false);
}

export function MemberClassProgressionAuditStateResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): MemberClassProgressionAuditStateResponse {
    if (json == null) {
        return json;
    }
    return {

        'actualCompletedRideCount': json['actualCompletedRideCount'],
        'progressionValue': json['progressionValue'],
        'progressionClass': json['progressionClass'],
        'effectiveClass': json['effectiveClass'],
        'managementStartedAt': json['managementStartedAt'],
        'baselineClass': json['baselineClass'],
        'baselineThreshold': json['baselineThreshold'],
        'baselineActualRideCount': json['baselineActualRideCount'],
        'specialApprovalProgressionCredit': json['specialApprovalProgressionCredit'],
        'promotionHoldClass': json['promotionHoldClass'],
        'dressageApproved': json['dressageApproved'],
        'jumpingApproved': json['jumpingApproved'],
        'rideCountDelta': json['rideCountDelta'],
    };
}

export function MemberClassProgressionAuditStateResponseToJSON(json: any): MemberClassProgressionAuditStateResponse {
    return MemberClassProgressionAuditStateResponseToJSONTyped(json, false);
}

export function MemberClassProgressionAuditStateResponseToJSONTyped(value?: MemberClassProgressionAuditStateResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'actualCompletedRideCount': value['actualCompletedRideCount'],
        'progressionValue': value['progressionValue'],
        'progressionClass': value['progressionClass'],
        'effectiveClass': value['effectiveClass'],
        'managementStartedAt': value['managementStartedAt'],
        'baselineClass': value['baselineClass'],
        'baselineThreshold': value['baselineThreshold'],
        'baselineActualRideCount': value['baselineActualRideCount'],
        'specialApprovalProgressionCredit': value['specialApprovalProgressionCredit'],
        'promotionHoldClass': value['promotionHoldClass'],
        'dressageApproved': value['dressageApproved'],
        'jumpingApproved': value['jumpingApproved'],
        'rideCountDelta': value['rideCountDelta'],
    };
}
