/* tslint:disable */
/* eslint-disable */
/**
 * Horse Reservation API
 * 마장 예약 서비스 API
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MemberAvailableTimeSlotResponse } from './MemberAvailableTimeSlotResponse';
import {
    MemberAvailableTimeSlotResponseFromJSON,
    MemberAvailableTimeSlotResponseFromJSONTyped,
    MemberAvailableTimeSlotResponseToJSON,
    MemberAvailableTimeSlotResponseToJSONTyped,
} from './MemberAvailableTimeSlotResponse';

/**
 *
 * @export
 * @interface MemberAvailableTimeSlotsResponse
 */
export interface MemberAvailableTimeSlotsResponse {
    /**
     *
     * @type {Date}
     * @memberof MemberAvailableTimeSlotsResponse
     */
    date: Date;
    /**
     *
     * @type {MemberAvailableTimeSlotsResponseClassTypeEnum}
     * @memberof MemberAvailableTimeSlotsResponse
     */
    classType: MemberAvailableTimeSlotsResponseClassTypeEnum;
    /**
     *
     * @type {Array<MemberAvailableTimeSlotResponse>}
     * @memberof MemberAvailableTimeSlotsResponse
     */
    timeSlots: Array<MemberAvailableTimeSlotResponse>;
}


/**
 * @export
 */
export const MemberAvailableTimeSlotsResponseClassTypeEnum = {
    FirstRide: 'FIRST_RIDE',
    RoundBeginner: 'ROUND_BEGINNER',
    RoundTrot: 'ROUND_TROT',
    LargeArenaBeginner: 'LARGE_ARENA_BEGINNER',
    LargeArenaTrot: 'LARGE_ARENA_TROT',
    Dressage: 'DRESSAGE',
    Jumping: 'JUMPING'
} as const;
export type MemberAvailableTimeSlotsResponseClassTypeEnum = typeof MemberAvailableTimeSlotsResponseClassTypeEnum[keyof typeof MemberAvailableTimeSlotsResponseClassTypeEnum];


/**
 * Check if a given object implements the MemberAvailableTimeSlotsResponse interface.
 */
export function instanceOfMemberAvailableTimeSlotsResponse(value: object): value is MemberAvailableTimeSlotsResponse {
    if (!('date' in value) || value['date'] === undefined) return false;
    if (!('classType' in value) || value['classType'] === undefined) return false;
    if (!('timeSlots' in value) || value['timeSlots'] === undefined) return false;
    return true;
}

export function MemberAvailableTimeSlotsResponseFromJSON(json: any): MemberAvailableTimeSlotsResponse {
    return MemberAvailableTimeSlotsResponseFromJSONTyped(json, false);
}

export function MemberAvailableTimeSlotsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): MemberAvailableTimeSlotsResponse {
    if (json == null) {
        return json;
    }
    return {

        'date': (new Date(json['date'])),
        'classType': json['classType'],
        'timeSlots': ((json['timeSlots'] as Array<any>).map(MemberAvailableTimeSlotResponseFromJSON)),
    };
}

export function MemberAvailableTimeSlotsResponseToJSON(json: any): MemberAvailableTimeSlotsResponse {
    return MemberAvailableTimeSlotsResponseToJSONTyped(json, false);
}

export function MemberAvailableTimeSlotsResponseToJSONTyped(value?: MemberAvailableTimeSlotsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'date': value['date'].toISOString().substring(0,10),
        'classType': value['classType'],
        'timeSlots': ((value['timeSlots'] as Array<any>).map(MemberAvailableTimeSlotResponseToJSON)),
    };
}

