/* tslint:disable */
/* eslint-disable */
/**
 * Horse Reservation API
 * 마장 예약 서비스 API
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface MemberAvailableTimeSlotResponse
 */
export interface MemberAvailableTimeSlotResponse {
    /**
     *
     * @type {number}
     * @memberof MemberAvailableTimeSlotResponse
     */
    timeSlotId?: number;
    /**
     *
     * @type {Date}
     * @memberof MemberAvailableTimeSlotResponse
     */
    lessonDate?: Date;
    /**
     *
     * @type {string}
     * @memberof MemberAvailableTimeSlotResponse
     */
    startTime?: string;
    /**
     *
     * @type {boolean}
     * @memberof MemberAvailableTimeSlotResponse
     */
    closed?: boolean;
    /**
     *
     * @type {boolean}
     * @memberof MemberAvailableTimeSlotResponse
     */
    reservable?: boolean;
    /**
     *
     * @type {number}
     * @memberof MemberAvailableTimeSlotResponse
     */
    remainingCapacity?: number;
    /**
     *
     * @type {MemberAvailableTimeSlotResponseUnavailableReasonEnum}
     * @memberof MemberAvailableTimeSlotResponse
     */
    unavailableReason?: MemberAvailableTimeSlotResponseUnavailableReasonEnum;
}


/**
 * @export
 */
export const MemberAvailableTimeSlotResponseUnavailableReasonEnum = {
    NotEligible: 'NOT_ELIGIBLE',
    Closed: 'CLOSED',
    Full: 'FULL'
} as const;
export type MemberAvailableTimeSlotResponseUnavailableReasonEnum = typeof MemberAvailableTimeSlotResponseUnavailableReasonEnum[keyof typeof MemberAvailableTimeSlotResponseUnavailableReasonEnum];


/**
 * Check if a given object implements the MemberAvailableTimeSlotResponse interface.
 */
export function instanceOfMemberAvailableTimeSlotResponse(value: object): value is MemberAvailableTimeSlotResponse {
    return true;
}

export function MemberAvailableTimeSlotResponseFromJSON(json: any): MemberAvailableTimeSlotResponse {
    return MemberAvailableTimeSlotResponseFromJSONTyped(json, false);
}

export function MemberAvailableTimeSlotResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): MemberAvailableTimeSlotResponse {
    if (json == null) {
        return json;
    }
    return {

        'timeSlotId': json['timeSlotId'] == null ? undefined : json['timeSlotId'],
        'lessonDate': json['lessonDate'] == null ? undefined : (new Date(json['lessonDate'])),
        'startTime': json['startTime'] == null ? undefined : json['startTime'],
        'closed': json['closed'] == null ? undefined : json['closed'],
        'reservable': json['reservable'] == null ? undefined : json['reservable'],
        'remainingCapacity': json['remainingCapacity'] == null ? undefined : json['remainingCapacity'],
        'unavailableReason': json['unavailableReason'] == null ? undefined : json['unavailableReason'],
    };
}

export function MemberAvailableTimeSlotResponseToJSON(json: any): MemberAvailableTimeSlotResponse {
    return MemberAvailableTimeSlotResponseToJSONTyped(json, false);
}

export function MemberAvailableTimeSlotResponseToJSONTyped(value?: MemberAvailableTimeSlotResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'timeSlotId': value['timeSlotId'],
        'lessonDate': value['lessonDate'] == null ? value['lessonDate'] : value['lessonDate'].toISOString().substring(0,10),
        'startTime': value['startTime'],
        'closed': value['closed'],
        'reservable': value['reservable'],
        'remainingCapacity': value['remainingCapacity'],
        'unavailableReason': value['unavailableReason'],
    };
}

