/* tslint:disable */
/* eslint-disable */
/**
 * Horse Reservation API
 * 마장 예약 서비스 API
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface MemberCouponUsageResponse
 */
export interface MemberCouponUsageResponse {
    /**
     *
     * @type {number}
     * @memberof MemberCouponUsageResponse
     */
    usageLogId?: number;
    /**
     *
     * @type {number}
     * @memberof MemberCouponUsageResponse
     */
    couponId?: number;
    /**
     *
     * @type {number}
     * @memberof MemberCouponUsageResponse
     */
    reservationId?: number;
    /**
     *
     * @type {string}
     * @memberof MemberCouponUsageResponse
     */
    action?: string;
    /**
     *
     * @type {number}
     * @memberof MemberCouponUsageResponse
     */
    countDelta?: number;
    /**
     *
     * @type {Date}
     * @memberof MemberCouponUsageResponse
     */
    occurredAt?: Date;
    /**
     *
     * @type {string}
     * @memberof MemberCouponUsageResponse
     */
    actorType?: string;
}

/**
 * Check if a given object implements the MemberCouponUsageResponse interface.
 */
export function instanceOfMemberCouponUsageResponse(value: object): value is MemberCouponUsageResponse {
    return true;
}

export function MemberCouponUsageResponseFromJSON(json: any): MemberCouponUsageResponse {
    return MemberCouponUsageResponseFromJSONTyped(json, false);
}

export function MemberCouponUsageResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): MemberCouponUsageResponse {
    if (json == null) {
        return json;
    }
    return {

        'usageLogId': json['usageLogId'] == null ? undefined : json['usageLogId'],
        'couponId': json['couponId'] == null ? undefined : json['couponId'],
        'reservationId': json['reservationId'] == null ? undefined : json['reservationId'],
        'action': json['action'] == null ? undefined : json['action'],
        'countDelta': json['countDelta'] == null ? undefined : json['countDelta'],
        'occurredAt': json['occurredAt'] == null ? undefined : (new Date(json['occurredAt'])),
        'actorType': json['actorType'] == null ? undefined : json['actorType'],
    };
}

export function MemberCouponUsageResponseToJSON(json: any): MemberCouponUsageResponse {
    return MemberCouponUsageResponseToJSONTyped(json, false);
}

export function MemberCouponUsageResponseToJSONTyped(value?: MemberCouponUsageResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'usageLogId': value['usageLogId'],
        'couponId': value['couponId'],
        'reservationId': value['reservationId'],
        'action': value['action'],
        'countDelta': value['countDelta'],
        'occurredAt': value['occurredAt'] == null ? value['occurredAt'] : value['occurredAt'].toISOString(),
        'actorType': value['actorType'],
    };
}

