/* tslint:disable */
/* eslint-disable */
/**
 * Horse Reservation API
 * 마장 예약 서비스 API
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface PendingPaymentExpiryResponse
 */
export interface PendingPaymentExpiryResponse {
    /**
     *
     * @type {number}
     * @memberof PendingPaymentExpiryResponse
     */
    expiredCount?: number;
    /**
     *
     * @type {Date}
     * @memberof PendingPaymentExpiryResponse
     */
    executedAt?: Date;
}

/**
 * Check if a given object implements the PendingPaymentExpiryResponse interface.
 */
export function instanceOfPendingPaymentExpiryResponse(value: object): value is PendingPaymentExpiryResponse {
    return true;
}

export function PendingPaymentExpiryResponseFromJSON(json: any): PendingPaymentExpiryResponse {
    return PendingPaymentExpiryResponseFromJSONTyped(json, false);
}

export function PendingPaymentExpiryResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PendingPaymentExpiryResponse {
    if (json == null) {
        return json;
    }
    return {

        'expiredCount': json['expiredCount'] == null ? undefined : json['expiredCount'],
        'executedAt': json['executedAt'] == null ? undefined : (new Date(json['executedAt'])),
    };
}

export function PendingPaymentExpiryResponseToJSON(json: any): PendingPaymentExpiryResponse {
    return PendingPaymentExpiryResponseToJSONTyped(json, false);
}

export function PendingPaymentExpiryResponseToJSONTyped(value?: PendingPaymentExpiryResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'expiredCount': value['expiredCount'],
        'executedAt': value['executedAt'] == null ? value['executedAt'] : value['executedAt'].toISOString(),
    };
}

