/* tslint:disable */
/* eslint-disable */
/**
 * Horse Reservation API
 * 마장 예약 서비스 API
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface RecurringHolidayPreviewRequest
 */
export interface RecurringHolidayPreviewRequest {
    /**
     *
     * @type {number}
     * @memberof RecurringHolidayPreviewRequest
     */
    holidayId?: number;
    /**
     *
     * @type {RecurringHolidayPreviewRequestDayOfWeekEnum}
     * @memberof RecurringHolidayPreviewRequest
     */
    dayOfWeek: RecurringHolidayPreviewRequestDayOfWeekEnum;
    /**
     *
     * @type {Date}
     * @memberof RecurringHolidayPreviewRequest
     */
    effectiveFrom: Date;
    /**
     *
     * @type {Date}
     * @memberof RecurringHolidayPreviewRequest
     */
    effectiveTo?: Date;
}


/**
 * @export
 */
export const RecurringHolidayPreviewRequestDayOfWeekEnum = {
    Monday: 'MONDAY',
    Tuesday: 'TUESDAY',
    Wednesday: 'WEDNESDAY',
    Thursday: 'THURSDAY',
    Friday: 'FRIDAY',
    Saturday: 'SATURDAY',
    Sunday: 'SUNDAY'
} as const;
export type RecurringHolidayPreviewRequestDayOfWeekEnum = typeof RecurringHolidayPreviewRequestDayOfWeekEnum[keyof typeof RecurringHolidayPreviewRequestDayOfWeekEnum];


/**
 * Check if a given object implements the RecurringHolidayPreviewRequest interface.
 */
export function instanceOfRecurringHolidayPreviewRequest(value: object): value is RecurringHolidayPreviewRequest {
    if (!('dayOfWeek' in value) || value['dayOfWeek'] === undefined) return false;
    if (!('effectiveFrom' in value) || value['effectiveFrom'] === undefined) return false;
    return true;
}

export function RecurringHolidayPreviewRequestFromJSON(json: any): RecurringHolidayPreviewRequest {
    return RecurringHolidayPreviewRequestFromJSONTyped(json, false);
}

export function RecurringHolidayPreviewRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): RecurringHolidayPreviewRequest {
    if (json == null) {
        return json;
    }
    return {

        'holidayId': json['holidayId'] == null ? undefined : json['holidayId'],
        'dayOfWeek': json['dayOfWeek'],
        'effectiveFrom': (new Date(json['effectiveFrom'])),
        'effectiveTo': json['effectiveTo'] == null ? undefined : (new Date(json['effectiveTo'])),
    };
}

export function RecurringHolidayPreviewRequestToJSON(json: any): RecurringHolidayPreviewRequest {
    return RecurringHolidayPreviewRequestToJSONTyped(json, false);
}

export function RecurringHolidayPreviewRequestToJSONTyped(value?: RecurringHolidayPreviewRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'holidayId': value['holidayId'],
        'dayOfWeek': value['dayOfWeek'],
        'effectiveFrom': value['effectiveFrom'].toISOString().substring(0,10),
        'effectiveTo': value['effectiveTo'] == null ? value['effectiveTo'] : value['effectiveTo'].toISOString().substring(0,10),
    };
}
