/* tslint:disable */
/* eslint-disable */
/**
 * Horse Reservation API
 * 마장 예약 서비스 API
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface RecurringHolidayRequest
 */
export interface RecurringHolidayRequest {
    /**
     *
     * @type {RecurringHolidayRequestDayOfWeekEnum}
     * @memberof RecurringHolidayRequest
     */
    dayOfWeek: RecurringHolidayRequestDayOfWeekEnum;
    /**
     *
     * @type {Date}
     * @memberof RecurringHolidayRequest
     */
    effectiveFrom: Date;
    /**
     *
     * @type {Date}
     * @memberof RecurringHolidayRequest
     */
    effectiveTo?: Date;
    /**
     *
     * @type {string}
     * @memberof RecurringHolidayRequest
     */
    holidayReason: string;
    /**
     *
     * @type {number}
     * @memberof RecurringHolidayRequest
     */
    expectedConfigVersion: number;
    /**
     *
     * @type {string}
     * @memberof RecurringHolidayRequest
     */
    changeReason: string;
}


/**
 * @export
 */
export const RecurringHolidayRequestDayOfWeekEnum = {
    Monday: 'MONDAY',
    Tuesday: 'TUESDAY',
    Wednesday: 'WEDNESDAY',
    Thursday: 'THURSDAY',
    Friday: 'FRIDAY',
    Saturday: 'SATURDAY',
    Sunday: 'SUNDAY'
} as const;
export type RecurringHolidayRequestDayOfWeekEnum = typeof RecurringHolidayRequestDayOfWeekEnum[keyof typeof RecurringHolidayRequestDayOfWeekEnum];


/**
 * Check if a given object implements the RecurringHolidayRequest interface.
 */
export function instanceOfRecurringHolidayRequest(value: object): value is RecurringHolidayRequest {
    if (!('dayOfWeek' in value) || value['dayOfWeek'] === undefined) return false;
    if (!('effectiveFrom' in value) || value['effectiveFrom'] === undefined) return false;
    if (!('holidayReason' in value) || value['holidayReason'] === undefined) return false;
    if (!('expectedConfigVersion' in value) || value['expectedConfigVersion'] === undefined) return false;
    if (!('changeReason' in value) || value['changeReason'] === undefined) return false;
    return true;
}

export function RecurringHolidayRequestFromJSON(json: any): RecurringHolidayRequest {
    return RecurringHolidayRequestFromJSONTyped(json, false);
}

export function RecurringHolidayRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): RecurringHolidayRequest {
    if (json == null) {
        return json;
    }
    return {

        'dayOfWeek': json['dayOfWeek'],
        'effectiveFrom': (new Date(json['effectiveFrom'])),
        'effectiveTo': json['effectiveTo'] == null ? undefined : (new Date(json['effectiveTo'])),
        'holidayReason': json['holidayReason'],
        'expectedConfigVersion': json['expectedConfigVersion'],
        'changeReason': json['changeReason'],
    };
}

export function RecurringHolidayRequestToJSON(json: any): RecurringHolidayRequest {
    return RecurringHolidayRequestToJSONTyped(json, false);
}

export function RecurringHolidayRequestToJSONTyped(value?: RecurringHolidayRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'dayOfWeek': value['dayOfWeek'],
        'effectiveFrom': value['effectiveFrom'].toISOString().substring(0,10),
        'effectiveTo': value['effectiveTo'] == null ? value['effectiveTo'] : value['effectiveTo'].toISOString().substring(0,10),
        'holidayReason': value['holidayReason'],
        'expectedConfigVersion': value['expectedConfigVersion'],
        'changeReason': value['changeReason'],
    };
}
