/* tslint:disable */
/* eslint-disable */
/**
 * Horse Reservation API
 * 마장 예약 서비스 API
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface RecurringHolidayResponse
 */
export interface RecurringHolidayResponse {
    /**
     *
     * @type {number}
     * @memberof RecurringHolidayResponse
     */
    holidayId: number;
    /**
     *
     * @type {RecurringHolidayResponseDayOfWeekEnum}
     * @memberof RecurringHolidayResponse
     */
    dayOfWeek: RecurringHolidayResponseDayOfWeekEnum;
    /**
     *
     * @type {Date}
     * @memberof RecurringHolidayResponse
     */
    effectiveFrom: Date;
    /**
     *
     * @type {Date}
     * @memberof RecurringHolidayResponse
     */
    effectiveTo?: Date;
    /**
     *
     * @type {string}
     * @memberof RecurringHolidayResponse
     */
    reason: string;
    /**
     *
     * @type {boolean}
     * @memberof RecurringHolidayResponse
     */
    active: boolean;
    /**
     *
     * @type {number}
     * @memberof RecurringHolidayResponse
     */
    version: number;
}


/**
 * @export
 */
export const RecurringHolidayResponseDayOfWeekEnum = {
    Monday: 'MONDAY',
    Tuesday: 'TUESDAY',
    Wednesday: 'WEDNESDAY',
    Thursday: 'THURSDAY',
    Friday: 'FRIDAY',
    Saturday: 'SATURDAY',
    Sunday: 'SUNDAY'
} as const;
export type RecurringHolidayResponseDayOfWeekEnum = typeof RecurringHolidayResponseDayOfWeekEnum[keyof typeof RecurringHolidayResponseDayOfWeekEnum];


/**
 * Check if a given object implements the RecurringHolidayResponse interface.
 */
export function instanceOfRecurringHolidayResponse(value: object): value is RecurringHolidayResponse {
    if (!('holidayId' in value) || value['holidayId'] === undefined) return false;
    if (!('dayOfWeek' in value) || value['dayOfWeek'] === undefined) return false;
    if (!('effectiveFrom' in value) || value['effectiveFrom'] === undefined) return false;
    if (!('reason' in value) || value['reason'] === undefined) return false;
    if (!('active' in value) || value['active'] === undefined) return false;
    if (!('version' in value) || value['version'] === undefined) return false;
    return true;
}

export function RecurringHolidayResponseFromJSON(json: any): RecurringHolidayResponse {
    return RecurringHolidayResponseFromJSONTyped(json, false);
}

export function RecurringHolidayResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RecurringHolidayResponse {
    if (json == null) {
        return json;
    }
    return {

        'holidayId': json['holidayId'],
        'dayOfWeek': json['dayOfWeek'],
        'effectiveFrom': (new Date(json['effectiveFrom'])),
        'effectiveTo': json['effectiveTo'] == null ? undefined : (new Date(json['effectiveTo'])),
        'reason': json['reason'],
        'active': json['active'],
        'version': json['version'],
    };
}

export function RecurringHolidayResponseToJSON(json: any): RecurringHolidayResponse {
    return RecurringHolidayResponseToJSONTyped(json, false);
}

export function RecurringHolidayResponseToJSONTyped(value?: RecurringHolidayResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'holidayId': value['holidayId'],
        'dayOfWeek': value['dayOfWeek'],
        'effectiveFrom': value['effectiveFrom'].toISOString().substring(0,10),
        'effectiveTo': value['effectiveTo'] == null ? value['effectiveTo'] : value['effectiveTo'].toISOString().substring(0,10),
        'reason': value['reason'],
        'active': value['active'],
        'version': value['version'],
    };
}
