/* tslint:disable */
/* eslint-disable */
/**
 * Horse Reservation API
 * 마장 예약 서비스 API
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RecurringHolidayResponse } from './RecurringHolidayResponse';
import {
    RecurringHolidayResponseFromJSON,
    RecurringHolidayResponseFromJSONTyped,
    RecurringHolidayResponseToJSON,
    RecurringHolidayResponseToJSONTyped,
} from './RecurringHolidayResponse';
import type { RecurringHolidayImpactResponse } from './RecurringHolidayImpactResponse';
import {
    RecurringHolidayImpactResponseFromJSON,
    RecurringHolidayImpactResponseFromJSONTyped,
    RecurringHolidayImpactResponseToJSON,
    RecurringHolidayImpactResponseToJSONTyped,
} from './RecurringHolidayImpactResponse';
import type { ScheduleSynchronizationResponse } from './ScheduleSynchronizationResponse';
import {
    ScheduleSynchronizationResponseFromJSON,
    ScheduleSynchronizationResponseFromJSONTyped,
    ScheduleSynchronizationResponseToJSON,
    ScheduleSynchronizationResponseToJSONTyped,
} from './ScheduleSynchronizationResponse';

/**
 *
 * @export
 * @interface RecurringHolidayMutationResponse
 */
export interface RecurringHolidayMutationResponse {
    /**
     *
     * @type {RecurringHolidayResponse}
     * @memberof RecurringHolidayMutationResponse
     */
    holiday: RecurringHolidayResponse;
    /**
     *
     * @type {number}
     * @memberof RecurringHolidayMutationResponse
     */
    pendingConfigVersion: number;
    /**
     *
     * @type {RecurringHolidayImpactResponse}
     * @memberof RecurringHolidayMutationResponse
     */
    impact: RecurringHolidayImpactResponse;
    /**
     *
     * @type {ScheduleSynchronizationResponse}
     * @memberof RecurringHolidayMutationResponse
     */
    synchronization: ScheduleSynchronizationResponse;
}

/**
 * Check if a given object implements the RecurringHolidayMutationResponse interface.
 */
export function instanceOfRecurringHolidayMutationResponse(value: object): value is RecurringHolidayMutationResponse {
    if (!('holiday' in value) || value['holiday'] === undefined) return false;
    if (!('pendingConfigVersion' in value) || value['pendingConfigVersion'] === undefined) return false;
    if (!('impact' in value) || value['impact'] === undefined) return false;
    if (!('synchronization' in value) || value['synchronization'] === undefined) return false;
    return true;
}

export function RecurringHolidayMutationResponseFromJSON(json: any): RecurringHolidayMutationResponse {
    return RecurringHolidayMutationResponseFromJSONTyped(json, false);
}

export function RecurringHolidayMutationResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RecurringHolidayMutationResponse {
    if (json == null) {
        return json;
    }
    return {

        'holiday': RecurringHolidayResponseFromJSON(json['holiday']),
        'pendingConfigVersion': json['pendingConfigVersion'],
        'impact': RecurringHolidayImpactResponseFromJSON(json['impact']),
        'synchronization': ScheduleSynchronizationResponseFromJSON(json['synchronization']),
    };
}

export function RecurringHolidayMutationResponseToJSON(json: any): RecurringHolidayMutationResponse {
    return RecurringHolidayMutationResponseToJSONTyped(json, false);
}

export function RecurringHolidayMutationResponseToJSONTyped(value?: RecurringHolidayMutationResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'holiday': RecurringHolidayResponseToJSON(value['holiday']),
        'pendingConfigVersion': value['pendingConfigVersion'],
        'impact': RecurringHolidayImpactResponseToJSON(value['impact']),
        'synchronization': ScheduleSynchronizationResponseToJSON(value['synchronization']),
    };
}
