/* tslint:disable */
/* eslint-disable */
/**
 * Horse Reservation API
 * 마장 예약 서비스 API
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RecurringHolidayImpactCountsResponse } from './RecurringHolidayImpactCountsResponse';
import {
    RecurringHolidayImpactCountsResponseFromJSON,
    RecurringHolidayImpactCountsResponseFromJSONTyped,
    RecurringHolidayImpactCountsResponseToJSON,
    RecurringHolidayImpactCountsResponseToJSONTyped,
} from './RecurringHolidayImpactCountsResponse';

/**
 *
 * @export
 * @interface RecurringHolidayImpactResponse
 */
export interface RecurringHolidayImpactResponse {
    /**
     *
     * @type {RecurringHolidayImpactCountsResponse}
     * @memberof RecurringHolidayImpactResponse
     */
    previous: RecurringHolidayImpactCountsResponse;
    /**
     *
     * @type {RecurringHolidayImpactCountsResponse}
     * @memberof RecurringHolidayImpactResponse
     */
    current: RecurringHolidayImpactCountsResponse;
    /**
     *
     * @type {RecurringHolidayImpactCountsResponse}
     * @memberof RecurringHolidayImpactResponse
     */
    combined: RecurringHolidayImpactCountsResponse;
}

/**
 * Check if a given object implements the RecurringHolidayImpactResponse interface.
 */
export function instanceOfRecurringHolidayImpactResponse(value: object): value is RecurringHolidayImpactResponse {
    if (!('previous' in value) || value['previous'] === undefined) return false;
    if (!('current' in value) || value['current'] === undefined) return false;
    if (!('combined' in value) || value['combined'] === undefined) return false;
    return true;
}

export function RecurringHolidayImpactResponseFromJSON(json: any): RecurringHolidayImpactResponse {
    return RecurringHolidayImpactResponseFromJSONTyped(json, false);
}

export function RecurringHolidayImpactResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RecurringHolidayImpactResponse {
    if (json == null) {
        return json;
    }
    return {

        'previous': RecurringHolidayImpactCountsResponseFromJSON(json['previous']),
        'current': RecurringHolidayImpactCountsResponseFromJSON(json['current']),
        'combined': RecurringHolidayImpactCountsResponseFromJSON(json['combined']),
    };
}

export function RecurringHolidayImpactResponseToJSON(json: any): RecurringHolidayImpactResponse {
    return RecurringHolidayImpactResponseToJSONTyped(json, false);
}

export function RecurringHolidayImpactResponseToJSONTyped(value?: RecurringHolidayImpactResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'previous': RecurringHolidayImpactCountsResponseToJSON(value['previous']),
        'current': RecurringHolidayImpactCountsResponseToJSON(value['current']),
        'combined': RecurringHolidayImpactCountsResponseToJSON(value['combined']),
    };
}
