/* tslint:disable */
/* eslint-disable */
/**
 * Horse Reservation API
 * 마장 예약 서비스 API
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface ReservationCompletionResponse
 */
export interface ReservationCompletionResponse {
    /**
     *
     * @type {number}
     * @memberof ReservationCompletionResponse
     */
    reservationId?: number;
    /**
     *
     * @type {string}
     * @memberof ReservationCompletionResponse
     */
    status?: string;
    /**
     *
     * @type {string}
     * @memberof ReservationCompletionResponse
     */
    paymentSource?: string;
    /**
     *
     * @type {number}
     * @memberof ReservationCompletionResponse
     */
    couponId?: number;
    /**
     *
     * @type {number}
     * @memberof ReservationCompletionResponse
     */
    generalRideCount?: number;
    /**
     *
     * @type {number}
     * @memberof ReservationCompletionResponse
     */
    dressageRideCount?: number;
    /**
     *
     * @type {number}
     * @memberof ReservationCompletionResponse
     */
    jumpingRideCount?: number;
}

/**
 * Check if a given object implements the ReservationCompletionResponse interface.
 */
export function instanceOfReservationCompletionResponse(value: object): value is ReservationCompletionResponse {
    return true;
}

export function ReservationCompletionResponseFromJSON(json: any): ReservationCompletionResponse {
    return ReservationCompletionResponseFromJSONTyped(json, false);
}

export function ReservationCompletionResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReservationCompletionResponse {
    if (json == null) {
        return json;
    }
    return {

        'reservationId': json['reservationId'] == null ? undefined : json['reservationId'],
        'status': json['status'] == null ? undefined : json['status'],
        'paymentSource': json['paymentSource'] == null ? undefined : json['paymentSource'],
        'couponId': json['couponId'] == null ? undefined : json['couponId'],
        'generalRideCount': json['generalRideCount'] == null ? undefined : json['generalRideCount'],
        'dressageRideCount': json['dressageRideCount'] == null ? undefined : json['dressageRideCount'],
        'jumpingRideCount': json['jumpingRideCount'] == null ? undefined : json['jumpingRideCount'],
    };
}

export function ReservationCompletionResponseToJSON(json: any): ReservationCompletionResponse {
    return ReservationCompletionResponseToJSONTyped(json, false);
}

export function ReservationCompletionResponseToJSONTyped(value?: ReservationCompletionResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'reservationId': value['reservationId'],
        'status': value['status'],
        'paymentSource': value['paymentSource'],
        'couponId': value['couponId'],
        'generalRideCount': value['generalRideCount'],
        'dressageRideCount': value['dressageRideCount'],
        'jumpingRideCount': value['jumpingRideCount'],
    };
}

