/* tslint:disable */
/* eslint-disable */
/**
 * Horse Reservation API
 * 마장 예약 서비스 API
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface ReservationConfirmResponse
 */
export interface ReservationConfirmResponse {
    /**
     *
     * @type {number}
     * @memberof ReservationConfirmResponse
     */
    reservationId?: number;
    /**
     *
     * @type {string}
     * @memberof ReservationConfirmResponse
     */
    status?: string;
    /**
     *
     * @type {string}
     * @memberof ReservationConfirmResponse
     */
    paymentSource?: string;
    /**
     *
     * @type {number}
     * @memberof ReservationConfirmResponse
     */
    couponId?: number;
    /**
     *
     * @type {Date}
     * @memberof ReservationConfirmResponse
     */
    adminConfirmedAt?: Date;
}

/**
 * Check if a given object implements the ReservationConfirmResponse interface.
 */
export function instanceOfReservationConfirmResponse(value: object): value is ReservationConfirmResponse {
    return true;
}

export function ReservationConfirmResponseFromJSON(json: any): ReservationConfirmResponse {
    return ReservationConfirmResponseFromJSONTyped(json, false);
}

export function ReservationConfirmResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReservationConfirmResponse {
    if (json == null) {
        return json;
    }
    return {

        'reservationId': json['reservationId'] == null ? undefined : json['reservationId'],
        'status': json['status'] == null ? undefined : json['status'],
        'paymentSource': json['paymentSource'] == null ? undefined : json['paymentSource'],
        'couponId': json['couponId'] == null ? undefined : json['couponId'],
        'adminConfirmedAt': json['adminConfirmedAt'] == null ? undefined : (new Date(json['adminConfirmedAt'])),
    };
}

export function ReservationConfirmResponseToJSON(json: any): ReservationConfirmResponse {
    return ReservationConfirmResponseToJSONTyped(json, false);
}

export function ReservationConfirmResponseToJSONTyped(value?: ReservationConfirmResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'reservationId': value['reservationId'],
        'status': value['status'],
        'paymentSource': value['paymentSource'],
        'couponId': value['couponId'],
        'adminConfirmedAt': value['adminConfirmedAt'] == null ? value['adminConfirmedAt'] : value['adminConfirmedAt'].toISOString(),
    };
}

