/* tslint:disable */
/* eslint-disable */
/**
 * Horse Reservation API
 * 마장 예약 서비스 API
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface ReservationChangePreviewResponse
 */
export interface ReservationChangePreviewResponse {
    /**
     *
     * @type {number}
     * @memberof ReservationChangePreviewResponse
     */
    reservationId: number;
    /**
     *
     * @type {number}
     * @memberof ReservationChangePreviewResponse
     */
    targetTimeSlotId: number;
    /**
     *
     * @type {Date}
     * @memberof ReservationChangePreviewResponse
     */
    targetLessonDate: Date;
    /**
     *
     * @type {string}
     * @memberof ReservationChangePreviewResponse
     */
    targetStartTime: string;
    /**
     *
     * @type {string}
     * @memberof ReservationChangePreviewResponse
     */
    timing: string;
    /**
     *
     * @type {string}
     * @memberof ReservationChangePreviewResponse
     */
    couponAction: string;
    /**
     *
     * @type {boolean}
     * @memberof ReservationChangePreviewResponse
     */
    freeChangeUsed: boolean;
}

/**
 * Check if a given object implements the ReservationChangePreviewResponse interface.
 */
export function instanceOfReservationChangePreviewResponse(value: object): value is ReservationChangePreviewResponse {
    if (!('reservationId' in value) || value['reservationId'] === undefined) return false;
    if (!('targetTimeSlotId' in value) || value['targetTimeSlotId'] === undefined) return false;
    if (!('targetLessonDate' in value) || value['targetLessonDate'] === undefined) return false;
    if (!('targetStartTime' in value) || value['targetStartTime'] === undefined) return false;
    if (!('timing' in value) || value['timing'] === undefined) return false;
    if (!('couponAction' in value) || value['couponAction'] === undefined) return false;
    if (!('freeChangeUsed' in value) || value['freeChangeUsed'] === undefined) return false;
    return true;
}

export function ReservationChangePreviewResponseFromJSON(json: any): ReservationChangePreviewResponse {
    return ReservationChangePreviewResponseFromJSONTyped(json, false);
}

export function ReservationChangePreviewResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReservationChangePreviewResponse {
    if (json == null) {
        return json;
    }
    return {

        'reservationId': json['reservationId'],
        'targetTimeSlotId': json['targetTimeSlotId'],
        'targetLessonDate': (new Date(json['targetLessonDate'])),
        'targetStartTime': json['targetStartTime'],
        'timing': json['timing'],
        'couponAction': json['couponAction'],
        'freeChangeUsed': json['freeChangeUsed'],
    };
}

export function ReservationChangePreviewResponseToJSON(json: any): ReservationChangePreviewResponse {
    return ReservationChangePreviewResponseToJSONTyped(json, false);
}

export function ReservationChangePreviewResponseToJSONTyped(value?: ReservationChangePreviewResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'reservationId': value['reservationId'],
        'targetTimeSlotId': value['targetTimeSlotId'],
        'targetLessonDate': value['targetLessonDate'].toISOString().substring(0,10),
        'targetStartTime': value['targetStartTime'],
        'timing': value['timing'],
        'couponAction': value['couponAction'],
        'freeChangeUsed': value['freeChangeUsed'],
    };
}

