/* tslint:disable */
/* eslint-disable */
/**
 * Horse Reservation API
 * 마장 예약 서비스 API
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface ReservationNoShowResponse
 */
export interface ReservationNoShowResponse {
    /**
     *
     * @type {number}
     * @memberof ReservationNoShowResponse
     */
    reservationId: number;
    /**
     *
     * @type {string}
     * @memberof ReservationNoShowResponse
     */
    status: string;
    /**
     *
     * @type {string}
     * @memberof ReservationNoShowResponse
     */
    paymentSource: string;
    /**
     *
     * @type {number}
     * @memberof ReservationNoShowResponse
     */
    couponId: number | null;
    /**
     *
     * @type {string}
     * @memberof ReservationNoShowResponse
     */
    couponAction: string;
    /**
     *
     * @type {string}
     * @memberof ReservationNoShowResponse
     */
    adminMemo: string | null;
}

/**
 * Check if a given object implements the ReservationNoShowResponse interface.
 */
export function instanceOfReservationNoShowResponse(value: object): value is ReservationNoShowResponse {
    if (!('reservationId' in value) || value['reservationId'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('paymentSource' in value) || value['paymentSource'] === undefined) return false;
    if (!('couponId' in value) || value['couponId'] === undefined) return false;
    if (!('couponAction' in value) || value['couponAction'] === undefined) return false;
    if (!('adminMemo' in value) || value['adminMemo'] === undefined) return false;
    return true;
}

export function ReservationNoShowResponseFromJSON(json: any): ReservationNoShowResponse {
    return ReservationNoShowResponseFromJSONTyped(json, false);
}

export function ReservationNoShowResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReservationNoShowResponse {
    if (json == null) {
        return json;
    }
    return {

        'reservationId': json['reservationId'],
        'status': json['status'],
        'paymentSource': json['paymentSource'],
        'couponId': json['couponId'],
        'couponAction': json['couponAction'],
        'adminMemo': json['adminMemo'],
    };
}

export function ReservationNoShowResponseToJSON(json: any): ReservationNoShowResponse {
    return ReservationNoShowResponseToJSONTyped(json, false);
}

export function ReservationNoShowResponseToJSONTyped(value?: ReservationNoShowResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'reservationId': value['reservationId'],
        'status': value['status'],
        'paymentSource': value['paymentSource'],
        'couponId': value['couponId'],
        'couponAction': value['couponAction'],
        'adminMemo': value['adminMemo'],
    };
}

