/* tslint:disable */
/* eslint-disable */
/**
 * Horse Reservation API
 * 마장 예약 서비스 API
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface ReservationCancellationPreviewResponse
 */
export interface ReservationCancellationPreviewResponse {
    /**
     *
     * @type {number}
     * @memberof ReservationCancellationPreviewResponse
     */
    reservationId?: number;
    /**
     *
     * @type {string}
     * @memberof ReservationCancellationPreviewResponse
     */
    timing?: string;
    /**
     *
     * @type {string}
     * @memberof ReservationCancellationPreviewResponse
     */
    responsibility?: string;
    /**
     *
     * @type {string}
     * @memberof ReservationCancellationPreviewResponse
     */
    couponAction?: string;
}

/**
 * Check if a given object implements the ReservationCancellationPreviewResponse interface.
 */
export function instanceOfReservationCancellationPreviewResponse(value: object): value is ReservationCancellationPreviewResponse {
    return true;
}

export function ReservationCancellationPreviewResponseFromJSON(json: any): ReservationCancellationPreviewResponse {
    return ReservationCancellationPreviewResponseFromJSONTyped(json, false);
}

export function ReservationCancellationPreviewResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReservationCancellationPreviewResponse {
    if (json == null) {
        return json;
    }
    return {

        'reservationId': json['reservationId'] == null ? undefined : json['reservationId'],
        'timing': json['timing'] == null ? undefined : json['timing'],
        'responsibility': json['responsibility'] == null ? undefined : json['responsibility'],
        'couponAction': json['couponAction'] == null ? undefined : json['couponAction'],
    };
}

export function ReservationCancellationPreviewResponseToJSON(json: any): ReservationCancellationPreviewResponse {
    return ReservationCancellationPreviewResponseToJSONTyped(json, false);
}

export function ReservationCancellationPreviewResponseToJSONTyped(value?: ReservationCancellationPreviewResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'reservationId': value['reservationId'],
        'timing': value['timing'],
        'responsibility': value['responsibility'],
        'couponAction': value['couponAction'],
    };
}

