/* tslint:disable */
/* eslint-disable */
/**
 * Horse Reservation API
 * 마장 예약 서비스 API
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ReservationActionAvailabilityResponse } from './ReservationActionAvailabilityResponse';
import {
    ReservationActionAvailabilityResponseFromJSON,
    ReservationActionAvailabilityResponseFromJSONTyped,
    ReservationActionAvailabilityResponseToJSON,
    ReservationActionAvailabilityResponseToJSONTyped,
} from './ReservationActionAvailabilityResponse';

/**
 *
 * @export
 * @interface ReservationActionsResponse
 */
export interface ReservationActionsResponse {
    /**
     *
     * @type {ReservationActionAvailabilityResponse}
     * @memberof ReservationActionsResponse
     */
    change?: ReservationActionAvailabilityResponse;
    /**
     *
     * @type {ReservationActionAvailabilityResponse}
     * @memberof ReservationActionsResponse
     */
    cancel?: ReservationActionAvailabilityResponse;
    /**
     *
     * @type {ReservationActionAvailabilityResponse}
     * @memberof ReservationActionsResponse
     */
    complete?: ReservationActionAvailabilityResponse;
    /**
     *
     * @type {ReservationActionAvailabilityResponse}
     * @memberof ReservationActionsResponse
     */
    noShow?: ReservationActionAvailabilityResponse;
    /**
     *
     * @type {ReservationActionAvailabilityResponse}
     * @memberof ReservationActionsResponse
     */
    approve?: ReservationActionAvailabilityResponse;
}

/**
 * Check if a given object implements the ReservationActionsResponse interface.
 */
export function instanceOfReservationActionsResponse(value: object): value is ReservationActionsResponse {
    return true;
}

export function ReservationActionsResponseFromJSON(json: any): ReservationActionsResponse {
    return ReservationActionsResponseFromJSONTyped(json, false);
}

export function ReservationActionsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReservationActionsResponse {
    if (json == null) {
        return json;
    }
    return {

        'change': json['change'] == null ? undefined : ReservationActionAvailabilityResponseFromJSON(json['change']),
        'cancel': json['cancel'] == null ? undefined : ReservationActionAvailabilityResponseFromJSON(json['cancel']),
        'complete': json['complete'] == null ? undefined : ReservationActionAvailabilityResponseFromJSON(json['complete']),
        'noShow': json['noShow'] == null ? undefined : ReservationActionAvailabilityResponseFromJSON(json['noShow']),
        'approve': json['approve'] == null ? undefined : ReservationActionAvailabilityResponseFromJSON(json['approve']),
    };
}

export function ReservationActionsResponseToJSON(json: any): ReservationActionsResponse {
    return ReservationActionsResponseToJSONTyped(json, false);
}

export function ReservationActionsResponseToJSONTyped(value?: ReservationActionsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'change': ReservationActionAvailabilityResponseToJSON(value['change']),
        'cancel': ReservationActionAvailabilityResponseToJSON(value['cancel']),
        'complete': ReservationActionAvailabilityResponseToJSON(value['complete']),
        'noShow': ReservationActionAvailabilityResponseToJSON(value['noShow']),
        'approve': ReservationActionAvailabilityResponseToJSON(value['approve']),
    };
}

