/* tslint:disable */
/* eslint-disable */
/**
 * Horse Reservation API
 * 마장 예약 서비스 API
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ReservationCouponResponse } from './ReservationCouponResponse';
import {
    ReservationCouponResponseFromJSON,
    ReservationCouponResponseFromJSONTyped,
    ReservationCouponResponseToJSON,
    ReservationCouponResponseToJSONTyped,
} from './ReservationCouponResponse';

/**
 *
 * @export
 * @interface ReservationApplicationResponse
 */
export interface ReservationApplicationResponse {
    /**
     *
     * @type {number}
     * @memberof ReservationApplicationResponse
     */
    reservationId: number;
    /**
     *
     * @type {string}
     * @memberof ReservationApplicationResponse
     */
    classType: string;
    /**
     *
     * @type {Date}
     * @memberof ReservationApplicationResponse
     */
    lessonDate: Date;
    /**
     *
     * @type {string}
     * @memberof ReservationApplicationResponse
     */
    startTime: string;
    /**
     *
     * @type {string}
     * @memberof ReservationApplicationResponse
     */
    status: string;
    /**
     *
     * @type {string}
     * @memberof ReservationApplicationResponse
     */
    paymentSource: string;
    /**
     *
     * @type {ReservationCouponResponse}
     * @memberof ReservationApplicationResponse
     */
    coupon: ReservationCouponResponse | null;
    /**
     *
     * @type {Date}
     * @memberof ReservationApplicationResponse
     */
    paymentDueAt: Date | null;
}

/**
 * Check if a given object implements the ReservationApplicationResponse interface.
 */
export function instanceOfReservationApplicationResponse(value: object): value is ReservationApplicationResponse {
    if (!('reservationId' in value) || value['reservationId'] === undefined) return false;
    if (!('classType' in value) || value['classType'] === undefined) return false;
    if (!('lessonDate' in value) || value['lessonDate'] === undefined) return false;
    if (!('startTime' in value) || value['startTime'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('paymentSource' in value) || value['paymentSource'] === undefined) return false;
    if (!('coupon' in value) || value['coupon'] === undefined) return false;
    if (!('paymentDueAt' in value) || value['paymentDueAt'] === undefined) return false;
    return true;
}

export function ReservationApplicationResponseFromJSON(json: any): ReservationApplicationResponse {
    return ReservationApplicationResponseFromJSONTyped(json, false);
}

export function ReservationApplicationResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReservationApplicationResponse {
    if (json == null) {
        return json;
    }
    return {

        'reservationId': json['reservationId'],
        'classType': json['classType'],
        'lessonDate': (new Date(json['lessonDate'])),
        'startTime': json['startTime'],
        'status': json['status'],
        'paymentSource': json['paymentSource'],
        'coupon': ReservationCouponResponseFromJSON(json['coupon']),
        'paymentDueAt': (json['paymentDueAt'] == null ? null : new Date(json['paymentDueAt'])),
    };
}

export function ReservationApplicationResponseToJSON(json: any): ReservationApplicationResponse {
    return ReservationApplicationResponseToJSONTyped(json, false);
}

export function ReservationApplicationResponseToJSONTyped(value?: ReservationApplicationResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'reservationId': value['reservationId'],
        'classType': value['classType'],
        'lessonDate': value['lessonDate'].toISOString().substring(0,10),
        'startTime': value['startTime'],
        'status': value['status'],
        'paymentSource': value['paymentSource'],
        'coupon': ReservationCouponResponseToJSON(value['coupon']),
        'paymentDueAt': value['paymentDueAt'] == null ? value['paymentDueAt'] : value['paymentDueAt'].toISOString(),
    };
}

