/* tslint:disable */
/* eslint-disable */
/**
 * Horse Reservation API
 * 마장 예약 서비스 API
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface ReservationRejectRequest
 */
export interface ReservationRejectRequest {
    /**
     *
     * @type {string}
     * @memberof ReservationRejectRequest
     */
    reason: string;
}

/**
 * Check if a given object implements the ReservationRejectRequest interface.
 */
export function instanceOfReservationRejectRequest(value: object): value is ReservationRejectRequest {
    if (!('reason' in value) || value['reason'] === undefined) return false;
    return true;
}

export function ReservationRejectRequestFromJSON(json: any): ReservationRejectRequest {
    return ReservationRejectRequestFromJSONTyped(json, false);
}

export function ReservationRejectRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReservationRejectRequest {
    if (json == null) {
        return json;
    }
    return {

        'reason': json['reason'],
    };
}

export function ReservationRejectRequestToJSON(json: any): ReservationRejectRequest {
    return ReservationRejectRequestToJSONTyped(json, false);
}

export function ReservationRejectRequestToJSONTyped(value?: ReservationRejectRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'reason': value['reason'],
    };
}

