/* tslint:disable */
/* eslint-disable */
/**
 * Horse Reservation API
 * 마장 예약 서비스 API
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface ReservationCompletionResponse
 */
export interface ReservationCompletionResponse {
    /**
     *
     * @type {number}
     * @memberof ReservationCompletionResponse
     */
    reservationId: number;
    /**
     *
     * @type {string}
     * @memberof ReservationCompletionResponse
     */
    status: string;
    /**
     *
     * @type {string}
     * @memberof ReservationCompletionResponse
     */
    paymentSource: string;
    /**
     *
     * @type {number}
     * @memberof ReservationCompletionResponse
     */
    couponId: number | null;
    /**
     *
     * @type {number}
     * @memberof ReservationCompletionResponse
     */
    generalRideCount: number;
    /**
     *
     * @type {number}
     * @memberof ReservationCompletionResponse
     */
    dressageRideCount: number;
    /**
     *
     * @type {number}
     * @memberof ReservationCompletionResponse
     */
    jumpingRideCount: number;
}

/**
 * Check if a given object implements the ReservationCompletionResponse interface.
 */
export function instanceOfReservationCompletionResponse(value: object): value is ReservationCompletionResponse {
    if (!('reservationId' in value) || value['reservationId'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('paymentSource' in value) || value['paymentSource'] === undefined) return false;
    if (!('couponId' in value) || value['couponId'] === undefined) return false;
    if (!('generalRideCount' in value) || value['generalRideCount'] === undefined) return false;
    if (!('dressageRideCount' in value) || value['dressageRideCount'] === undefined) return false;
    if (!('jumpingRideCount' in value) || value['jumpingRideCount'] === undefined) return false;
    return true;
}

export function ReservationCompletionResponseFromJSON(json: any): ReservationCompletionResponse {
    return ReservationCompletionResponseFromJSONTyped(json, false);
}

export function ReservationCompletionResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReservationCompletionResponse {
    if (json == null) {
        return json;
    }
    return {

        'reservationId': json['reservationId'],
        'status': json['status'],
        'paymentSource': json['paymentSource'],
        'couponId': json['couponId'],
        'generalRideCount': json['generalRideCount'],
        'dressageRideCount': json['dressageRideCount'],
        'jumpingRideCount': json['jumpingRideCount'],
    };
}

export function ReservationCompletionResponseToJSON(json: any): ReservationCompletionResponse {
    return ReservationCompletionResponseToJSONTyped(json, false);
}

export function ReservationCompletionResponseToJSONTyped(value?: ReservationCompletionResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'reservationId': value['reservationId'],
        'status': value['status'],
        'paymentSource': value['paymentSource'],
        'couponId': value['couponId'],
        'generalRideCount': value['generalRideCount'],
        'dressageRideCount': value['dressageRideCount'],
        'jumpingRideCount': value['jumpingRideCount'],
    };
}

