/* tslint:disable */
/* eslint-disable */
/**
 * Horse Reservation API
 * 마장 예약 서비스 API
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface ReservationChangeResponse
 */
export interface ReservationChangeResponse {
    /**
     *
     * @type {number}
     * @memberof ReservationChangeResponse
     */
    reservationId: number;
    /**
     *
     * @type {Date}
     * @memberof ReservationChangeResponse
     */
    lessonDate: Date;
    /**
     *
     * @type {string}
     * @memberof ReservationChangeResponse
     */
    startTime: string;
    /**
     *
     * @type {string}
     * @memberof ReservationChangeResponse
     */
    status: string;
    /**
     *
     * @type {string}
     * @memberof ReservationChangeResponse
     */
    couponAction: string;
    /**
     *
     * @type {boolean}
     * @memberof ReservationChangeResponse
     */
    freeChangeUsed: boolean;
    /**
     *
     * @type {boolean}
     * @memberof ReservationChangeResponse
     */
    changed: boolean;
}

/**
 * Check if a given object implements the ReservationChangeResponse interface.
 */
export function instanceOfReservationChangeResponse(value: object): value is ReservationChangeResponse {
    if (!('reservationId' in value) || value['reservationId'] === undefined) return false;
    if (!('lessonDate' in value) || value['lessonDate'] === undefined) return false;
    if (!('startTime' in value) || value['startTime'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('couponAction' in value) || value['couponAction'] === undefined) return false;
    if (!('freeChangeUsed' in value) || value['freeChangeUsed'] === undefined) return false;
    if (!('changed' in value) || value['changed'] === undefined) return false;
    return true;
}

export function ReservationChangeResponseFromJSON(json: any): ReservationChangeResponse {
    return ReservationChangeResponseFromJSONTyped(json, false);
}

export function ReservationChangeResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReservationChangeResponse {
    if (json == null) {
        return json;
    }
    return {

        'reservationId': json['reservationId'],
        'lessonDate': (new Date(json['lessonDate'])),
        'startTime': json['startTime'],
        'status': json['status'],
        'couponAction': json['couponAction'],
        'freeChangeUsed': json['freeChangeUsed'],
        'changed': json['changed'],
    };
}

export function ReservationChangeResponseToJSON(json: any): ReservationChangeResponse {
    return ReservationChangeResponseToJSONTyped(json, false);
}

export function ReservationChangeResponseToJSONTyped(value?: ReservationChangeResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'reservationId': value['reservationId'],
        'lessonDate': value['lessonDate'].toISOString().substring(0,10),
        'startTime': value['startTime'],
        'status': value['status'],
        'couponAction': value['couponAction'],
        'freeChangeUsed': value['freeChangeUsed'],
        'changed': value['changed'],
    };
}

