/* tslint:disable */
/* eslint-disable */
/**
 * Horse Reservation API
 * 마장 예약 서비스 API
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface ReservationCouponResponse
 */
export interface ReservationCouponResponse {
    /**
     *
     * @type {number}
     * @memberof ReservationCouponResponse
     */
    couponId?: number;
    /**
     *
     * @type {Date}
     * @memberof ReservationCouponResponse
     */
    expiresAt?: Date;
    /**
     *
     * @type {number}
     * @memberof ReservationCouponResponse
     */
    remainingCount?: number;
    /**
     *
     * @type {number}
     * @memberof ReservationCouponResponse
     */
    heldCount?: number;
    /**
     *
     * @type {number}
     * @memberof ReservationCouponResponse
     */
    availableCount?: number;
}

/**
 * Check if a given object implements the ReservationCouponResponse interface.
 */
export function instanceOfReservationCouponResponse(value: object): value is ReservationCouponResponse {
    return true;
}

export function ReservationCouponResponseFromJSON(json: any): ReservationCouponResponse {
    return ReservationCouponResponseFromJSONTyped(json, false);
}

export function ReservationCouponResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReservationCouponResponse {
    if (json == null) {
        return json;
    }
    return {

        'couponId': json['couponId'] == null ? undefined : json['couponId'],
        'expiresAt': json['expiresAt'] == null ? undefined : (new Date(json['expiresAt'])),
        'remainingCount': json['remainingCount'] == null ? undefined : json['remainingCount'],
        'heldCount': json['heldCount'] == null ? undefined : json['heldCount'],
        'availableCount': json['availableCount'] == null ? undefined : json['availableCount'],
    };
}

export function ReservationCouponResponseToJSON(json: any): ReservationCouponResponse {
    return ReservationCouponResponseToJSONTyped(json, false);
}

export function ReservationCouponResponseToJSONTyped(value?: ReservationCouponResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'couponId': value['couponId'],
        'expiresAt': value['expiresAt'] == null ? value['expiresAt'] : value['expiresAt'].toISOString(),
        'remainingCount': value['remainingCount'],
        'heldCount': value['heldCount'],
        'availableCount': value['availableCount'],
    };
}

