/* tslint:disable */
/* eslint-disable */
/**
 * Horse Reservation API
 * 마장 예약 서비스 API
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface ReservationChangePreviewResponse
 */
export interface ReservationChangePreviewResponse {
    /**
     *
     * @type {number}
     * @memberof ReservationChangePreviewResponse
     */
    reservationId?: number;
    /**
     *
     * @type {number}
     * @memberof ReservationChangePreviewResponse
     */
    targetTimeSlotId?: number;
    /**
     *
     * @type {Date}
     * @memberof ReservationChangePreviewResponse
     */
    targetLessonDate?: Date;
    /**
     *
     * @type {string}
     * @memberof ReservationChangePreviewResponse
     */
    targetStartTime?: string;
    /**
     *
     * @type {string}
     * @memberof ReservationChangePreviewResponse
     */
    timing?: string;
    /**
     *
     * @type {string}
     * @memberof ReservationChangePreviewResponse
     */
    couponAction?: string;
    /**
     *
     * @type {boolean}
     * @memberof ReservationChangePreviewResponse
     */
    freeChangeUsed?: boolean;
}

/**
 * Check if a given object implements the ReservationChangePreviewResponse interface.
 */
export function instanceOfReservationChangePreviewResponse(value: object): value is ReservationChangePreviewResponse {
    return true;
}

export function ReservationChangePreviewResponseFromJSON(json: any): ReservationChangePreviewResponse {
    return ReservationChangePreviewResponseFromJSONTyped(json, false);
}

export function ReservationChangePreviewResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReservationChangePreviewResponse {
    if (json == null) {
        return json;
    }
    return {

        'reservationId': json['reservationId'] == null ? undefined : json['reservationId'],
        'targetTimeSlotId': json['targetTimeSlotId'] == null ? undefined : json['targetTimeSlotId'],
        'targetLessonDate': json['targetLessonDate'] == null ? undefined : (new Date(json['targetLessonDate'])),
        'targetStartTime': json['targetStartTime'] == null ? undefined : json['targetStartTime'],
        'timing': json['timing'] == null ? undefined : json['timing'],
        'couponAction': json['couponAction'] == null ? undefined : json['couponAction'],
        'freeChangeUsed': json['freeChangeUsed'] == null ? undefined : json['freeChangeUsed'],
    };
}

export function ReservationChangePreviewResponseToJSON(json: any): ReservationChangePreviewResponse {
    return ReservationChangePreviewResponseToJSONTyped(json, false);
}

export function ReservationChangePreviewResponseToJSONTyped(value?: ReservationChangePreviewResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'reservationId': value['reservationId'],
        'targetTimeSlotId': value['targetTimeSlotId'],
        'targetLessonDate': value['targetLessonDate'] == null ? value['targetLessonDate'] : value['targetLessonDate'].toISOString().substring(0,10),
        'targetStartTime': value['targetStartTime'],
        'timing': value['timing'],
        'couponAction': value['couponAction'],
        'freeChangeUsed': value['freeChangeUsed'],
    };
}

