/* tslint:disable */
/* eslint-disable */
/**
 * Horse Reservation API
 * 마장 예약 서비스 API
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ReservationCouponResponse } from './ReservationCouponResponse';
import {
    ReservationCouponResponseFromJSON,
    ReservationCouponResponseFromJSONTyped,
    ReservationCouponResponseToJSON,
    ReservationCouponResponseToJSONTyped,
} from './ReservationCouponResponse';

/**
 *
 * @export
 * @interface ReservationApplicationResponse
 */
export interface ReservationApplicationResponse {
    /**
     *
     * @type {number}
     * @memberof ReservationApplicationResponse
     */
    reservationId?: number;
    /**
     *
     * @type {string}
     * @memberof ReservationApplicationResponse
     */
    classType?: string;
    /**
     *
     * @type {Date}
     * @memberof ReservationApplicationResponse
     */
    lessonDate?: Date;
    /**
     *
     * @type {string}
     * @memberof ReservationApplicationResponse
     */
    startTime?: string;
    /**
     *
     * @type {string}
     * @memberof ReservationApplicationResponse
     */
    status?: string;
    /**
     *
     * @type {string}
     * @memberof ReservationApplicationResponse
     */
    paymentSource?: string;
    /**
     *
     * @type {ReservationCouponResponse}
     * @memberof ReservationApplicationResponse
     */
    coupon?: ReservationCouponResponse;
    /**
     *
     * @type {Date}
     * @memberof ReservationApplicationResponse
     */
    paymentDueAt?: Date;
}

/**
 * Check if a given object implements the ReservationApplicationResponse interface.
 */
export function instanceOfReservationApplicationResponse(value: object): value is ReservationApplicationResponse {
    return true;
}

export function ReservationApplicationResponseFromJSON(json: any): ReservationApplicationResponse {
    return ReservationApplicationResponseFromJSONTyped(json, false);
}

export function ReservationApplicationResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReservationApplicationResponse {
    if (json == null) {
        return json;
    }
    return {

        'reservationId': json['reservationId'] == null ? undefined : json['reservationId'],
        'classType': json['classType'] == null ? undefined : json['classType'],
        'lessonDate': json['lessonDate'] == null ? undefined : (new Date(json['lessonDate'])),
        'startTime': json['startTime'] == null ? undefined : json['startTime'],
        'status': json['status'] == null ? undefined : json['status'],
        'paymentSource': json['paymentSource'] == null ? undefined : json['paymentSource'],
        'coupon': json['coupon'] == null ? undefined : ReservationCouponResponseFromJSON(json['coupon']),
        'paymentDueAt': json['paymentDueAt'] == null ? undefined : (new Date(json['paymentDueAt'])),
    };
}

export function ReservationApplicationResponseToJSON(json: any): ReservationApplicationResponse {
    return ReservationApplicationResponseToJSONTyped(json, false);
}

export function ReservationApplicationResponseToJSONTyped(value?: ReservationApplicationResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'reservationId': value['reservationId'],
        'classType': value['classType'],
        'lessonDate': value['lessonDate'] == null ? value['lessonDate'] : value['lessonDate'].toISOString().substring(0,10),
        'startTime': value['startTime'],
        'status': value['status'],
        'paymentSource': value['paymentSource'],
        'coupon': ReservationCouponResponseToJSON(value['coupon']),
        'paymentDueAt': value['paymentDueAt'] == null ? value['paymentDueAt'] : value['paymentDueAt'].toISOString(),
    };
}

