/* tslint:disable */
/* eslint-disable */
/**
 * Horse Reservation API
 * 마장 예약 서비스 API
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface ReservationCancelResponse
 */
export interface ReservationCancelResponse {
    /**
     *
     * @type {number}
     * @memberof ReservationCancelResponse
     */
    reservationId: number;
    /**
     *
     * @type {string}
     * @memberof ReservationCancelResponse
     */
    status: string;
    /**
     *
     * @type {string}
     * @memberof ReservationCancelResponse
     */
    responsibility: string;
    /**
     *
     * @type {string}
     * @memberof ReservationCancelResponse
     */
    couponAction: string;
    /**
     *
     * @type {Date}
     * @memberof ReservationCancelResponse
     */
    cancelledAt: Date;
    /**
     *
     * @type {boolean}
     * @memberof ReservationCancelResponse
     */
    changed: boolean;
}

/**
 * Check if a given object implements the ReservationCancelResponse interface.
 */
export function instanceOfReservationCancelResponse(value: object): value is ReservationCancelResponse {
    if (!('reservationId' in value) || value['reservationId'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('responsibility' in value) || value['responsibility'] === undefined) return false;
    if (!('couponAction' in value) || value['couponAction'] === undefined) return false;
    if (!('cancelledAt' in value) || value['cancelledAt'] === undefined) return false;
    if (!('changed' in value) || value['changed'] === undefined) return false;
    return true;
}

export function ReservationCancelResponseFromJSON(json: any): ReservationCancelResponse {
    return ReservationCancelResponseFromJSONTyped(json, false);
}

export function ReservationCancelResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReservationCancelResponse {
    if (json == null) {
        return json;
    }
    return {

        'reservationId': json['reservationId'],
        'status': json['status'],
        'responsibility': json['responsibility'],
        'couponAction': json['couponAction'],
        'cancelledAt': (new Date(json['cancelledAt'])),
        'changed': json['changed'],
    };
}

export function ReservationCancelResponseToJSON(json: any): ReservationCancelResponse {
    return ReservationCancelResponseToJSONTyped(json, false);
}

export function ReservationCancelResponseToJSONTyped(value?: ReservationCancelResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'reservationId': value['reservationId'],
        'status': value['status'],
        'responsibility': value['responsibility'],
        'couponAction': value['couponAction'],
        'cancelledAt': value['cancelledAt'].toISOString(),
        'changed': value['changed'],
    };
}

