/* tslint:disable */
/* eslint-disable */
/**
 * Horse Reservation API
 * 마장 예약 서비스 API
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ScheduleTemplateImpactResponse } from './ScheduleTemplateImpactResponse';
import {
    ScheduleTemplateImpactResponseFromJSON,
    ScheduleTemplateImpactResponseFromJSONTyped,
    ScheduleTemplateImpactResponseToJSON,
    ScheduleTemplateImpactResponseToJSONTyped,
} from './ScheduleTemplateImpactResponse';
import type { ScheduleTemplateResponse } from './ScheduleTemplateResponse';
import {
    ScheduleTemplateResponseFromJSON,
    ScheduleTemplateResponseFromJSONTyped,
    ScheduleTemplateResponseToJSON,
    ScheduleTemplateResponseToJSONTyped,
} from './ScheduleTemplateResponse';
import type { ScheduleSynchronizationResponse } from './ScheduleSynchronizationResponse';
import {
    ScheduleSynchronizationResponseFromJSON,
    ScheduleSynchronizationResponseFromJSONTyped,
    ScheduleSynchronizationResponseToJSON,
    ScheduleSynchronizationResponseToJSONTyped,
} from './ScheduleSynchronizationResponse';

/**
 *
 * @export
 * @interface ScheduleTemplateMutationResponse
 */
export interface ScheduleTemplateMutationResponse {
    /**
     *
     * @type {ScheduleTemplateResponse}
     * @memberof ScheduleTemplateMutationResponse
     */
    template: ScheduleTemplateResponse;
    /**
     *
     * @type {number}
     * @memberof ScheduleTemplateMutationResponse
     */
    pendingConfigVersion: number;
    /**
     *
     * @type {ScheduleTemplateImpactResponse}
     * @memberof ScheduleTemplateMutationResponse
     */
    impact: ScheduleTemplateImpactResponse;
    /**
     *
     * @type {ScheduleSynchronizationResponse}
     * @memberof ScheduleTemplateMutationResponse
     */
    synchronization: ScheduleSynchronizationResponse;
}

/**
 * Check if a given object implements the ScheduleTemplateMutationResponse interface.
 */
export function instanceOfScheduleTemplateMutationResponse(value: object): value is ScheduleTemplateMutationResponse {
    if (!('template' in value) || value['template'] === undefined) return false;
    if (!('pendingConfigVersion' in value) || value['pendingConfigVersion'] === undefined) return false;
    if (!('impact' in value) || value['impact'] === undefined) return false;
    if (!('synchronization' in value) || value['synchronization'] === undefined) return false;
    return true;
}

export function ScheduleTemplateMutationResponseFromJSON(json: any): ScheduleTemplateMutationResponse {
    return ScheduleTemplateMutationResponseFromJSONTyped(json, false);
}

export function ScheduleTemplateMutationResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ScheduleTemplateMutationResponse {
    if (json == null) {
        return json;
    }
    return {

        'template': ScheduleTemplateResponseFromJSON(json['template']),
        'pendingConfigVersion': json['pendingConfigVersion'],
        'impact': ScheduleTemplateImpactResponseFromJSON(json['impact']),
        'synchronization': ScheduleSynchronizationResponseFromJSON(json['synchronization']),
    };
}

export function ScheduleTemplateMutationResponseToJSON(json: any): ScheduleTemplateMutationResponse {
    return ScheduleTemplateMutationResponseToJSONTyped(json, false);
}

export function ScheduleTemplateMutationResponseToJSONTyped(value?: ScheduleTemplateMutationResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'template': ScheduleTemplateResponseToJSON(value['template']),
        'pendingConfigVersion': value['pendingConfigVersion'],
        'impact': ScheduleTemplateImpactResponseToJSON(value['impact']),
        'synchronization': ScheduleSynchronizationResponseToJSON(value['synchronization']),
    };
}
