/* tslint:disable */
/* eslint-disable */
/**
 * Horse Reservation API
 * 마장 예약 서비스 API
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface ScheduleTemplateFutureReservationResponse
 */
export interface ScheduleTemplateFutureReservationResponse {
    /**
     *
     * @type {number}
     * @memberof ScheduleTemplateFutureReservationResponse
     */
    reservationId: number;
    /**
     *
     * @type {Date}
     * @memberof ScheduleTemplateFutureReservationResponse
     */
    lessonDate: Date;
    /**
     *
     * @type {string}
     * @memberof ScheduleTemplateFutureReservationResponse
     */
    startTime: string;
    /**
     *
     * @type {string}
     * @memberof ScheduleTemplateFutureReservationResponse
     */
    endTime: string;
    /**
     *
     * @type {number}
     * @memberof ScheduleTemplateFutureReservationResponse
     */
    memberId: number;
    /**
     *
     * @type {string}
     * @memberof ScheduleTemplateFutureReservationResponse
     */
    memberName: string;
    /**
     *
     * @type {string}
     * @memberof ScheduleTemplateFutureReservationResponse
     */
    memberPhone: string;
    /**
     *
     * @type {ScheduleTemplateFutureReservationResponseRidingClassEnum}
     * @memberof ScheduleTemplateFutureReservationResponse
     */
    ridingClass: ScheduleTemplateFutureReservationResponseRidingClassEnum;
    /**
     *
     * @type {ScheduleTemplateFutureReservationResponseStatusEnum}
     * @memberof ScheduleTemplateFutureReservationResponse
     */
    status: ScheduleTemplateFutureReservationResponseStatusEnum;
}


/**
 * @export
 */
export const ScheduleTemplateFutureReservationResponseRidingClassEnum = {
    FirstRide: 'FIRST_RIDE',
    RoundBeginner: 'ROUND_BEGINNER',
    RoundTrot: 'ROUND_TROT',
    LargeArenaBeginner: 'LARGE_ARENA_BEGINNER',
    LargeArenaTrot: 'LARGE_ARENA_TROT',
    CanterBeginner: 'CANTER_BEGINNER',
    Canter: 'CANTER',
    Dressage: 'DRESSAGE',
    Jumping: 'JUMPING'
} as const;
export type ScheduleTemplateFutureReservationResponseRidingClassEnum = typeof ScheduleTemplateFutureReservationResponseRidingClassEnum[keyof typeof ScheduleTemplateFutureReservationResponseRidingClassEnum];

/**
 * @export
 */
export const ScheduleTemplateFutureReservationResponseStatusEnum = {
    PendingAdminApproval: 'pending_admin_approval',
    PendingPayment: 'pending_payment',
    Confirmed: 'confirmed'
} as const;
export type ScheduleTemplateFutureReservationResponseStatusEnum = typeof ScheduleTemplateFutureReservationResponseStatusEnum[keyof typeof ScheduleTemplateFutureReservationResponseStatusEnum];


/**
 * Check if a given object implements the ScheduleTemplateFutureReservationResponse interface.
 */
export function instanceOfScheduleTemplateFutureReservationResponse(value: object): value is ScheduleTemplateFutureReservationResponse {
    if (!('reservationId' in value) || value['reservationId'] === undefined) return false;
    if (!('lessonDate' in value) || value['lessonDate'] === undefined) return false;
    if (!('startTime' in value) || value['startTime'] === undefined) return false;
    if (!('endTime' in value) || value['endTime'] === undefined) return false;
    if (!('memberId' in value) || value['memberId'] === undefined) return false;
    if (!('memberName' in value) || value['memberName'] === undefined) return false;
    if (!('memberPhone' in value) || value['memberPhone'] === undefined) return false;
    if (!('ridingClass' in value) || value['ridingClass'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function ScheduleTemplateFutureReservationResponseFromJSON(json: any): ScheduleTemplateFutureReservationResponse {
    return ScheduleTemplateFutureReservationResponseFromJSONTyped(json, false);
}

export function ScheduleTemplateFutureReservationResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ScheduleTemplateFutureReservationResponse {
    if (json == null) {
        return json;
    }
    return {

        'reservationId': json['reservationId'],
        'lessonDate': (new Date(json['lessonDate'])),
        'startTime': json['startTime'],
        'endTime': json['endTime'],
        'memberId': json['memberId'],
        'memberName': json['memberName'],
        'memberPhone': json['memberPhone'],
        'ridingClass': json['ridingClass'],
        'status': json['status'],
    };
}

export function ScheduleTemplateFutureReservationResponseToJSON(json: any): ScheduleTemplateFutureReservationResponse {
    return ScheduleTemplateFutureReservationResponseToJSONTyped(json, false);
}

export function ScheduleTemplateFutureReservationResponseToJSONTyped(value?: ScheduleTemplateFutureReservationResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'reservationId': value['reservationId'],
        'lessonDate': value['lessonDate'].toISOString().substring(0,10),
        'startTime': value['startTime'],
        'endTime': value['endTime'],
        'memberId': value['memberId'],
        'memberName': value['memberName'],
        'memberPhone': value['memberPhone'],
        'ridingClass': value['ridingClass'],
        'status': value['status'],
    };
}
