/* tslint:disable */
/* eslint-disable */
/**
 * Horse Reservation API
 * 마장 예약 서비스 API
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface ScheduleDateResponse
 */
export interface ScheduleDateResponse {
    /**
     *
     * @type {Date}
     * @memberof ScheduleDateResponse
     */
    scheduleDate: Date;
    /**
     *
     * @type {ScheduleDateResponseStatusEnum}
     * @memberof ScheduleDateResponse
     */
    status: ScheduleDateResponseStatusEnum;
    /**
     *
     * @type {ScheduleDateResponseResumeStatusEnum}
     * @memberof ScheduleDateResponse
     */
    resumeStatus: ScheduleDateResponseResumeStatusEnum | null;
    /**
     *
     * @type {string}
     * @memberof ScheduleDateResponse
     */
    reason: string | null;
    /**
     *
     * @type {number}
     * @memberof ScheduleDateResponse
     */
    appliedConfigVersion: number;
    /**
     *
     * @type {number}
     * @memberof ScheduleDateResponse
     */
    version: number;
}


/**
 * @export
 */
export const ScheduleDateResponseStatusEnum = {
    Normal: 'NORMAL',
    Open: 'OPEN',
    Closing: 'CLOSING',
    Closed: 'CLOSED'
} as const;
export type ScheduleDateResponseStatusEnum = typeof ScheduleDateResponseStatusEnum[keyof typeof ScheduleDateResponseStatusEnum];

/**
 * @export
 */
export const ScheduleDateResponseResumeStatusEnum = {
    Normal: 'NORMAL',
    Open: 'OPEN',
    Closing: 'CLOSING',
    Closed: 'CLOSED'
} as const;
export type ScheduleDateResponseResumeStatusEnum = typeof ScheduleDateResponseResumeStatusEnum[keyof typeof ScheduleDateResponseResumeStatusEnum];


/**
 * Check if a given object implements the ScheduleDateResponse interface.
 */
export function instanceOfScheduleDateResponse(value: object): value is ScheduleDateResponse {
    if (!('scheduleDate' in value) || value['scheduleDate'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('resumeStatus' in value) || value['resumeStatus'] === undefined) return false;
    if (!('reason' in value) || value['reason'] === undefined) return false;
    if (!('appliedConfigVersion' in value) || value['appliedConfigVersion'] === undefined) return false;
    if (!('version' in value) || value['version'] === undefined) return false;
    return true;
}

export function ScheduleDateResponseFromJSON(json: any): ScheduleDateResponse {
    return ScheduleDateResponseFromJSONTyped(json, false);
}

export function ScheduleDateResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ScheduleDateResponse {
    if (json == null) {
        return json;
    }
    return {

        'scheduleDate': (new Date(json['scheduleDate'])),
        'status': json['status'],
        'resumeStatus': json['resumeStatus'],
        'reason': json['reason'],
        'appliedConfigVersion': json['appliedConfigVersion'],
        'version': json['version'],
    };
}

export function ScheduleDateResponseToJSON(json: any): ScheduleDateResponse {
    return ScheduleDateResponseToJSONTyped(json, false);
}

export function ScheduleDateResponseToJSONTyped(value?: ScheduleDateResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'scheduleDate': value['scheduleDate'].toISOString().substring(0,10),
        'status': value['status'],
        'resumeStatus': value['resumeStatus'],
        'reason': value['reason'],
        'appliedConfigVersion': value['appliedConfigVersion'],
        'version': value['version'],
    };
}
