/* tslint:disable */
/* eslint-disable */
/**
 * Horse Reservation API
 * 마장 예약 서비스 API
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface ScheduleTemplateRequest
 */
export interface ScheduleTemplateRequest {
    /**
     *
     * @type {ScheduleTemplateRequestDayOfWeekEnum}
     * @memberof ScheduleTemplateRequest
     */
    dayOfWeek: ScheduleTemplateRequestDayOfWeekEnum;
    /**
     *
     * @type {string}
     * @memberof ScheduleTemplateRequest
     */
    startTime: string;
    /**
     *
     * @type {string}
     * @memberof ScheduleTemplateRequest
     */
    endTime: string;
    /**
     *
     * @type {number}
     * @memberof ScheduleTemplateRequest
     */
    totalCapacity: number;
    /**
     *
     * @type {number}
     * @memberof ScheduleTemplateRequest
     */
    roundArenaCapacity: number;
    /**
     *
     * @type {{ [key: string]: number; }}
     * @memberof ScheduleTemplateRequest
     */
    classCapacities: { [key: string]: number; };
    /**
     *
     * @type {number}
     * @memberof ScheduleTemplateRequest
     */
    expectedConfigVersion: number;
    /**
     *
     * @type {string}
     * @memberof ScheduleTemplateRequest
     */
    reason: string;
}


/**
 * @export
 */
export const ScheduleTemplateRequestDayOfWeekEnum = {
    Monday: 'MONDAY',
    Tuesday: 'TUESDAY',
    Wednesday: 'WEDNESDAY',
    Thursday: 'THURSDAY',
    Friday: 'FRIDAY',
    Saturday: 'SATURDAY',
    Sunday: 'SUNDAY'
} as const;
export type ScheduleTemplateRequestDayOfWeekEnum = typeof ScheduleTemplateRequestDayOfWeekEnum[keyof typeof ScheduleTemplateRequestDayOfWeekEnum];


/**
 * Check if a given object implements the ScheduleTemplateRequest interface.
 */
export function instanceOfScheduleTemplateRequest(value: object): value is ScheduleTemplateRequest {
    if (!('dayOfWeek' in value) || value['dayOfWeek'] === undefined) return false;
    if (!('startTime' in value) || value['startTime'] === undefined) return false;
    if (!('endTime' in value) || value['endTime'] === undefined) return false;
    if (!('totalCapacity' in value) || value['totalCapacity'] === undefined) return false;
    if (!('roundArenaCapacity' in value) || value['roundArenaCapacity'] === undefined) return false;
    if (!('classCapacities' in value) || value['classCapacities'] === undefined) return false;
    if (!('expectedConfigVersion' in value) || value['expectedConfigVersion'] === undefined) return false;
    if (!('reason' in value) || value['reason'] === undefined) return false;
    return true;
}

export function ScheduleTemplateRequestFromJSON(json: any): ScheduleTemplateRequest {
    return ScheduleTemplateRequestFromJSONTyped(json, false);
}

export function ScheduleTemplateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ScheduleTemplateRequest {
    if (json == null) {
        return json;
    }
    return {

        'dayOfWeek': json['dayOfWeek'],
        'startTime': json['startTime'],
        'endTime': json['endTime'],
        'totalCapacity': json['totalCapacity'],
        'roundArenaCapacity': json['roundArenaCapacity'],
        'classCapacities': json['classCapacities'],
        'expectedConfigVersion': json['expectedConfigVersion'],
        'reason': json['reason'],
    };
}

export function ScheduleTemplateRequestToJSON(json: any): ScheduleTemplateRequest {
    return ScheduleTemplateRequestToJSONTyped(json, false);
}

export function ScheduleTemplateRequestToJSONTyped(value?: ScheduleTemplateRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'dayOfWeek': value['dayOfWeek'],
        'startTime': value['startTime'],
        'endTime': value['endTime'],
        'totalCapacity': value['totalCapacity'],
        'roundArenaCapacity': value['roundArenaCapacity'],
        'classCapacities': value['classCapacities'],
        'expectedConfigVersion': value['expectedConfigVersion'],
        'reason': value['reason'],
    };
}
