/* tslint:disable */
/* eslint-disable */
/**
 * Horse Reservation API
 * 마장 예약 서비스 API
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface ScheduleDateActionRequest
 */
export interface ScheduleDateActionRequest {
    /**
     *
     * @type {string}
     * @memberof ScheduleDateActionRequest
     */
    reason: string;
    /**
     *
     * @type {number}
     * @memberof ScheduleDateActionRequest
     */
    expectedVersion: number;
}

/**
 * Check if a given object implements the ScheduleDateActionRequest interface.
 */
export function instanceOfScheduleDateActionRequest(value: object): value is ScheduleDateActionRequest {
    if (!('reason' in value) || value['reason'] === undefined) return false;
    if (!('expectedVersion' in value) || value['expectedVersion'] === undefined) return false;
    return true;
}

export function ScheduleDateActionRequestFromJSON(json: any): ScheduleDateActionRequest {
    return ScheduleDateActionRequestFromJSONTyped(json, false);
}

export function ScheduleDateActionRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ScheduleDateActionRequest {
    if (json == null) {
        return json;
    }
    return {

        'reason': json['reason'],
        'expectedVersion': json['expectedVersion'],
    };
}

export function ScheduleDateActionRequestToJSON(json: any): ScheduleDateActionRequest {
    return ScheduleDateActionRequestToJSONTyped(json, false);
}

export function ScheduleDateActionRequestToJSONTyped(value?: ScheduleDateActionRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'reason': value['reason'],
        'expectedVersion': value['expectedVersion'],
    };
}
