/* tslint:disable */
/* eslint-disable */
/**
 * Horse Reservation API
 * 마장 예약 서비스 API
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface ScheduleActivationRequest
 */
export interface ScheduleActivationRequest {
    /**
     *
     * @type {boolean}
     * @memberof ScheduleActivationRequest
     */
    active: boolean;
    /**
     *
     * @type {number}
     * @memberof ScheduleActivationRequest
     */
    expectedConfigVersion: number;
    /**
     *
     * @type {string}
     * @memberof ScheduleActivationRequest
     */
    reason: string;
}

/**
 * Check if a given object implements the ScheduleActivationRequest interface.
 */
export function instanceOfScheduleActivationRequest(value: object): value is ScheduleActivationRequest {
    if (!('active' in value) || value['active'] === undefined) return false;
    if (!('expectedConfigVersion' in value) || value['expectedConfigVersion'] === undefined) return false;
    if (!('reason' in value) || value['reason'] === undefined) return false;
    return true;
}

export function ScheduleActivationRequestFromJSON(json: any): ScheduleActivationRequest {
    return ScheduleActivationRequestFromJSONTyped(json, false);
}

export function ScheduleActivationRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ScheduleActivationRequest {
    if (json == null) {
        return json;
    }
    return {

        'active': json['active'],
        'expectedConfigVersion': json['expectedConfigVersion'],
        'reason': json['reason'],
    };
}

export function ScheduleActivationRequestToJSON(json: any): ScheduleActivationRequest {
    return ScheduleActivationRequestToJSONTyped(json, false);
}

export function ScheduleActivationRequestToJSONTyped(value?: ScheduleActivationRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'active': value['active'],
        'expectedConfigVersion': value['expectedConfigVersion'],
        'reason': value['reason'],
    };
}
