/* tslint:disable */
/* eslint-disable */
/**
 * Horse Reservation API
 * 마장 예약 서비스 API
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface ScheduleTemplateDeleteRequest
 */
export interface ScheduleTemplateDeleteRequest {
    /**
     *
     * @type {number}
     * @memberof ScheduleTemplateDeleteRequest
     */
    expectedConfigVersion: number;
    /**
     *
     * @type {string}
     * @memberof ScheduleTemplateDeleteRequest
     */
    reason: string;
}

/**
 * Check if a given object implements the ScheduleTemplateDeleteRequest interface.
 */
export function instanceOfScheduleTemplateDeleteRequest(value: object): value is ScheduleTemplateDeleteRequest {
    if (!('expectedConfigVersion' in value) || value['expectedConfigVersion'] === undefined) return false;
    if (!('reason' in value) || value['reason'] === undefined) return false;
    return true;
}

export function ScheduleTemplateDeleteRequestFromJSON(json: any): ScheduleTemplateDeleteRequest {
    return ScheduleTemplateDeleteRequestFromJSONTyped(json, false);
}

export function ScheduleTemplateDeleteRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ScheduleTemplateDeleteRequest {
    if (json == null) {
        return json;
    }
    return {

        'expectedConfigVersion': json['expectedConfigVersion'],
        'reason': json['reason'],
    };
}

export function ScheduleTemplateDeleteRequestToJSON(json: any): ScheduleTemplateDeleteRequest {
    return ScheduleTemplateDeleteRequestToJSONTyped(json, false);
}

export function ScheduleTemplateDeleteRequestToJSONTyped(value?: ScheduleTemplateDeleteRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'expectedConfigVersion': value['expectedConfigVersion'],
        'reason': value['reason'],
    };
}
