/* tslint:disable */
/* eslint-disable */
/**
 * Horse Reservation API
 * 마장 예약 서비스 API
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TimeSlotClosureImpactResponse } from './TimeSlotClosureImpactResponse';
import {
    TimeSlotClosureImpactResponseFromJSON,
    TimeSlotClosureImpactResponseFromJSONTyped,
    TimeSlotClosureImpactResponseToJSON,
    TimeSlotClosureImpactResponseToJSONTyped,
} from './TimeSlotClosureImpactResponse';

/**
 *
 * @export
 * @interface TimeSlotClosureResponse
 */
export interface TimeSlotClosureResponse {
    /**
     *
     * @type {number}
     * @memberof TimeSlotClosureResponse
     */
    timeSlotId: number;
    /**
     *
     * @type {boolean}
     * @memberof TimeSlotClosureResponse
     */
    adminClosed: boolean;
    /**
     *
     * @type {boolean}
     * @memberof TimeSlotClosureResponse
     */
    closed: boolean;
    /**
     *
     * @type {TimeSlotClosureResponseStatusEnum}
     * @memberof TimeSlotClosureResponse
     */
    status: TimeSlotClosureResponseStatusEnum;
    /**
     *
     * @type {string}
     * @memberof TimeSlotClosureResponse
     */
    reason: string;
    /**
     *
     * @type {Date}
     * @memberof TimeSlotClosureResponse
     */
    startedAt: Date;
    /**
     *
     * @type {Date}
     * @memberof TimeSlotClosureResponse
     */
    completedAt?: Date;
    /**
     *
     * @type {Date}
     * @memberof TimeSlotClosureResponse
     */
    withdrawnAt?: Date;
    /**
     *
     * @type {number}
     * @memberof TimeSlotClosureResponse
     */
    version: number;
    /**
     *
     * @type {number}
     * @memberof TimeSlotClosureResponse
     */
    totalCount: number;
    /**
     *
     * @type {number}
     * @memberof TimeSlotClosureResponse
     */
    resolvedCount: number;
    /**
     *
     * @type {number}
     * @memberof TimeSlotClosureResponse
     */
    unresolvedCount: number;
    /**
     *
     * @type {number}
     * @memberof TimeSlotClosureResponse
     */
    progressPercent: number;
    /**
     *
     * @type {Array<TimeSlotClosureImpactResponse>}
     * @memberof TimeSlotClosureResponse
     */
    impacts: Array<TimeSlotClosureImpactResponse>;
}


/**
 * @export
 */
export const TimeSlotClosureResponseStatusEnum = {
    InProgress: 'IN_PROGRESS',
    Completed: 'COMPLETED',
    Withdrawn: 'WITHDRAWN'
} as const;
export type TimeSlotClosureResponseStatusEnum = typeof TimeSlotClosureResponseStatusEnum[keyof typeof TimeSlotClosureResponseStatusEnum];


/**
 * Check if a given object implements the TimeSlotClosureResponse interface.
 */
export function instanceOfTimeSlotClosureResponse(value: object): value is TimeSlotClosureResponse {
    if (!('timeSlotId' in value) || value['timeSlotId'] === undefined) return false;
    if (!('adminClosed' in value) || value['adminClosed'] === undefined) return false;
    if (!('closed' in value) || value['closed'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('reason' in value) || value['reason'] === undefined) return false;
    if (!('startedAt' in value) || value['startedAt'] === undefined) return false;
    if (!('version' in value) || value['version'] === undefined) return false;
    if (!('totalCount' in value) || value['totalCount'] === undefined) return false;
    if (!('resolvedCount' in value) || value['resolvedCount'] === undefined) return false;
    if (!('unresolvedCount' in value) || value['unresolvedCount'] === undefined) return false;
    if (!('progressPercent' in value) || value['progressPercent'] === undefined) return false;
    if (!('impacts' in value) || value['impacts'] === undefined) return false;
    return true;
}

export function TimeSlotClosureResponseFromJSON(json: any): TimeSlotClosureResponse {
    return TimeSlotClosureResponseFromJSONTyped(json, false);
}

export function TimeSlotClosureResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TimeSlotClosureResponse {
    if (json == null) {
        return json;
    }
    return {

        'timeSlotId': json['timeSlotId'],
        'adminClosed': json['adminClosed'],
        'closed': json['closed'],
        'status': json['status'],
        'reason': json['reason'],
        'startedAt': (new Date(json['startedAt'])),
        'completedAt': json['completedAt'] == null ? undefined : (new Date(json['completedAt'])),
        'withdrawnAt': json['withdrawnAt'] == null ? undefined : (new Date(json['withdrawnAt'])),
        'version': json['version'],
        'totalCount': json['totalCount'],
        'resolvedCount': json['resolvedCount'],
        'unresolvedCount': json['unresolvedCount'],
        'progressPercent': json['progressPercent'],
        'impacts': ((json['impacts'] as Array<any>).map(TimeSlotClosureImpactResponseFromJSON)),
    };
}

export function TimeSlotClosureResponseToJSON(json: any): TimeSlotClosureResponse {
    return TimeSlotClosureResponseToJSONTyped(json, false);
}

export function TimeSlotClosureResponseToJSONTyped(value?: TimeSlotClosureResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'timeSlotId': value['timeSlotId'],
        'adminClosed': value['adminClosed'],
        'closed': value['closed'],
        'status': value['status'],
        'reason': value['reason'],
        'startedAt': value['startedAt'].toISOString(),
        'completedAt': value['completedAt'] == null ? value['completedAt'] : value['completedAt'].toISOString(),
        'withdrawnAt': value['withdrawnAt'] == null ? value['withdrawnAt'] : value['withdrawnAt'].toISOString(),
        'version': value['version'],
        'totalCount': value['totalCount'],
        'resolvedCount': value['resolvedCount'],
        'unresolvedCount': value['unresolvedCount'],
        'progressPercent': value['progressPercent'],
        'impacts': ((value['impacts'] as Array<any>).map(TimeSlotClosureImpactResponseToJSON)),
    };
}
