/* tslint:disable */
/* eslint-disable */
/**
 * Horse Reservation API
 * 마장 예약 서비스 API
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface TimeSlotClosureActionRequest
 */
export interface TimeSlotClosureActionRequest {
    /**
     *
     * @type {string}
     * @memberof TimeSlotClosureActionRequest
     */
    reason: string;
    /**
     *
     * @type {number}
     * @memberof TimeSlotClosureActionRequest
     */
    expectedVersion: number;
}

/**
 * Check if a given object implements the TimeSlotClosureActionRequest interface.
 */
export function instanceOfTimeSlotClosureActionRequest(value: object): value is TimeSlotClosureActionRequest {
    if (!('reason' in value) || value['reason'] === undefined) return false;
    if (!('expectedVersion' in value) || value['expectedVersion'] === undefined) return false;
    return true;
}

export function TimeSlotClosureActionRequestFromJSON(json: any): TimeSlotClosureActionRequest {
    return TimeSlotClosureActionRequestFromJSONTyped(json, false);
}

export function TimeSlotClosureActionRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): TimeSlotClosureActionRequest {
    if (json == null) {
        return json;
    }
    return {

        'reason': json['reason'],
        'expectedVersion': json['expectedVersion'],
    };
}

export function TimeSlotClosureActionRequestToJSON(json: any): TimeSlotClosureActionRequest {
    return TimeSlotClosureActionRequestToJSONTyped(json, false);
}

export function TimeSlotClosureActionRequestToJSONTyped(value?: TimeSlotClosureActionRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'reason': value['reason'],
        'expectedVersion': value['expectedVersion'],
    };
}
