/* tslint:disable */
/* eslint-disable */
/**
 * Horse Reservation API
 * 마장 예약 서비스 API
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface TimeSlotClosureImpactResponse
 */
export interface TimeSlotClosureImpactResponse {
    /**
     *
     * @type {number}
     * @memberof TimeSlotClosureImpactResponse
     */
    reservationId: number;
    /**
     *
     * @type {string}
     * @memberof TimeSlotClosureImpactResponse
     */
    reservationStatusAtStart: string;
    /**
     *
     * @type {string}
     * @memberof TimeSlotClosureImpactResponse
     */
    currentStatus: string;
    /**
     *
     * @type {boolean}
     * @memberof TimeSlotClosureImpactResponse
     */
    resolved: boolean;
    /**
     *
     * @type {boolean}
     * @memberof TimeSlotClosureImpactResponse
     */
    moved: boolean;
    /**
     *
     * @type {number}
     * @memberof TimeSlotClosureImpactResponse
     */
    memberId: number;
    /**
     *
     * @type {string}
     * @memberof TimeSlotClosureImpactResponse
     */
    memberName: string;
    /**
     *
     * @type {string}
     * @memberof TimeSlotClosureImpactResponse
     */
    memberPhone: string;
    /**
     *
     * @type {string}
     * @memberof TimeSlotClosureImpactResponse
     */
    classType: string;
    /**
     *
     * @type {string}
     * @memberof TimeSlotClosureImpactResponse
     */
    paymentSource: string;
    /**
     *
     * @type {number}
     * @memberof TimeSlotClosureImpactResponse
     */
    couponId?: number;
}

/**
 * Check if a given object implements the TimeSlotClosureImpactResponse interface.
 */
export function instanceOfTimeSlotClosureImpactResponse(value: object): value is TimeSlotClosureImpactResponse {
    if (!('reservationId' in value) || value['reservationId'] === undefined) return false;
    if (!('reservationStatusAtStart' in value) || value['reservationStatusAtStart'] === undefined) return false;
    if (!('currentStatus' in value) || value['currentStatus'] === undefined) return false;
    if (!('resolved' in value) || value['resolved'] === undefined) return false;
    if (!('moved' in value) || value['moved'] === undefined) return false;
    if (!('memberId' in value) || value['memberId'] === undefined) return false;
    if (!('memberName' in value) || value['memberName'] === undefined) return false;
    if (!('memberPhone' in value) || value['memberPhone'] === undefined) return false;
    if (!('classType' in value) || value['classType'] === undefined) return false;
    if (!('paymentSource' in value) || value['paymentSource'] === undefined) return false;
    return true;
}

export function TimeSlotClosureImpactResponseFromJSON(json: any): TimeSlotClosureImpactResponse {
    return TimeSlotClosureImpactResponseFromJSONTyped(json, false);
}

export function TimeSlotClosureImpactResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TimeSlotClosureImpactResponse {
    if (json == null) {
        return json;
    }
    return {

        'reservationId': json['reservationId'],
        'reservationStatusAtStart': json['reservationStatusAtStart'],
        'currentStatus': json['currentStatus'],
        'resolved': json['resolved'],
        'moved': json['moved'],
        'memberId': json['memberId'],
        'memberName': json['memberName'],
        'memberPhone': json['memberPhone'],
        'classType': json['classType'],
        'paymentSource': json['paymentSource'],
        'couponId': json['couponId'] == null ? undefined : json['couponId'],
    };
}

export function TimeSlotClosureImpactResponseToJSON(json: any): TimeSlotClosureImpactResponse {
    return TimeSlotClosureImpactResponseToJSONTyped(json, false);
}

export function TimeSlotClosureImpactResponseToJSONTyped(value?: TimeSlotClosureImpactResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'reservationId': value['reservationId'],
        'reservationStatusAtStart': value['reservationStatusAtStart'],
        'currentStatus': value['currentStatus'],
        'resolved': value['resolved'],
        'moved': value['moved'],
        'memberId': value['memberId'],
        'memberName': value['memberName'],
        'memberPhone': value['memberPhone'],
        'classType': value['classType'],
        'paymentSource': value['paymentSource'],
        'couponId': value['couponId'],
    };
}
