/* tslint:disable */
/* eslint-disable */
/**
 * Horse Reservation API
 * 마장 예약 서비스 API
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface TimeSlotCapacityUpdateRequest
 */
export interface TimeSlotCapacityUpdateRequest {
    /**
     *
     * @type {number}
     * @memberof TimeSlotCapacityUpdateRequest
     */
    totalCapacity?: number;
    /**
     *
     * @type {number}
     * @memberof TimeSlotCapacityUpdateRequest
     */
    roundArenaCapacity?: number;
    /**
     *
     * @type {{ [key: string]: number; }}
     * @memberof TimeSlotCapacityUpdateRequest
     */
    classCapacities?: { [key: string]: number; };
}

/**
 * Check if a given object implements the TimeSlotCapacityUpdateRequest interface.
 */
export function instanceOfTimeSlotCapacityUpdateRequest(value: object): value is TimeSlotCapacityUpdateRequest {
    return true;
}

export function TimeSlotCapacityUpdateRequestFromJSON(json: any): TimeSlotCapacityUpdateRequest {
    return TimeSlotCapacityUpdateRequestFromJSONTyped(json, false);
}

export function TimeSlotCapacityUpdateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): TimeSlotCapacityUpdateRequest {
    if (json == null) {
        return json;
    }
    return {

        'totalCapacity': json['totalCapacity'] == null ? undefined : json['totalCapacity'],
        'roundArenaCapacity': json['roundArenaCapacity'] == null ? undefined : json['roundArenaCapacity'],
        'classCapacities': json['classCapacities'] == null ? undefined : json['classCapacities'],
    };
}

export function TimeSlotCapacityUpdateRequestToJSON(json: any): TimeSlotCapacityUpdateRequest {
    return TimeSlotCapacityUpdateRequestToJSONTyped(json, false);
}

export function TimeSlotCapacityUpdateRequestToJSONTyped(value?: TimeSlotCapacityUpdateRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'totalCapacity': value['totalCapacity'],
        'roundArenaCapacity': value['roundArenaCapacity'],
        'classCapacities': value['classCapacities'],
    };
}

