/* tslint:disable */
/* eslint-disable */
/**
 * Horse Reservation API
 * 마장 예약 서비스 API
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface WebAuthTokenResponse
 */
export interface WebAuthTokenResponse {
    /**
     *
     * @type {string}
     * @memberof WebAuthTokenResponse
     */
    accessToken: string;
    /**
     *
     * @type {string}
     * @memberof WebAuthTokenResponse
     */
    tokenType: string;
    /**
     *
     * @type {Date}
     * @memberof WebAuthTokenResponse
     */
    accessTokenExpiresAt: Date;
}

/**
 * Check if a given object implements the WebAuthTokenResponse interface.
 */
export function instanceOfWebAuthTokenResponse(value: object): value is WebAuthTokenResponse {
    if (!('accessToken' in value) || value['accessToken'] === undefined) return false;
    if (!('tokenType' in value) || value['tokenType'] === undefined) return false;
    if (!('accessTokenExpiresAt' in value) || value['accessTokenExpiresAt'] === undefined) return false;
    return true;
}

export function WebAuthTokenResponseFromJSON(json: any): WebAuthTokenResponse {
    return WebAuthTokenResponseFromJSONTyped(json, false);
}

export function WebAuthTokenResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): WebAuthTokenResponse {
    if (json == null) {
        return json;
    }
    return {

        'accessToken': json['accessToken'],
        'tokenType': json['tokenType'],
        'accessTokenExpiresAt': (new Date(json['accessTokenExpiresAt'])),
    };
}

export function WebAuthTokenResponseToJSON(json: any): WebAuthTokenResponse {
    return WebAuthTokenResponseToJSONTyped(json, false);
}

export function WebAuthTokenResponseToJSONTyped(value?: WebAuthTokenResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'accessToken': value['accessToken'],
        'tokenType': value['tokenType'],
        'accessTokenExpiresAt': value['accessTokenExpiresAt'].toISOString(),
    };
}
